### ISSUE TITLE
Docker installation: Your shell has not been properly configured to use 'conda activate'.

### ISSUE THREAD

**Issue by kyriakosschwarz** [chemprop/chemprop#100]
When trying to create a Docker image through
`docker build -t chemprop .
`
I get this error:
`Step 12/14 : RUN conda activate chemprop
 ---> Running in 1210dba161cc

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
`

I tried modifying the Dockerfile:
`SHELL ["/bin/bash", "-c"]
RUN conda init bash
RUN source "/opt/conda/bin/activate"
RUN conda create -n chemprop python=3.7
RUN conda activate chemprop
RUN conda install -c conda-forge rdkit
RUN pip install -e .
`

But I still get the same issue.

**Comment by swansonk14** [comment]
Hi @kyriakosschwarz, thanks for bringing up the issue! If that doesn't work, another thing you could try is changing `conda activate chemprop` to `source activate chemprop`. I've seen that this sometimes fixes the issue, especially on older versions of conda. Please let me know if this works or if you're still running into problems!

**Comment by kyriakosschwarz** [comment]
Thank you @swansonk14 , it worked with `source`

**Comment by yichuanma95** [comment]
Hi @kyriakosschwarz, I ran into the same issue you had with the original Dockerfile. After following your modifications to it, I finally got chemprop to work with Docker. Thanks.

```
SHELL ["/bin/bash", "-c"]
RUN conda init bash
RUN source "/opt/conda/bin/activate"
RUN conda create -n chemprop python=3.7
RUN source activate chemprop
RUN conda install -c conda-forge rdkit
RUN pip install -e .
```
