### ISSUE TITLE
[v2 QUESTION]: weight-column exposed in API?

### ISSUE THREAD

**Issue by dmoccia** [chemprop/chemprop#1004]
Hello-Thank you for the work you are doing porting over chemprop 1.0 -> 2.0.  The API control is a great addition!

**What are you trying to do?**
In v2 looks like data_weights_path has been changed to weight-column in the CLI, is there an equivalent call in the API?  If not are there plans to expose some more of the CLI features via the API?  Thank you for any information you can provide.

Dennis

**Comment by KnathanM** [comment]
You can [pass](https://github.com/chemprop/chemprop/blob/d34f83f1e66b676525661d0a0367360b40fa085a/chemprop/data/datapoints.py#L20) the data point weight when creating the data points like this:
```
mols = [...]
ys = np.random.rand(10, 1)
weights = np.random.rand(10)
data_points = [MoleculeDatapoint(mol, y, weight=weight) for mol, y, weight in zip(mols, ys, weights)]
```

Off hand, I can't think of any CLI features that aren't available via the API. We tried to have the CLI use the Chemprop core code like a user would. Usually we would figure out how to do something in a notebook first and then port that over to the CLI.

**Comment by dmoccia** [comment]
@KnathanM thank you for you quick response and nice example.  That is great to hear that most things are exposed in the API calls.  Thanks again!
