### ISSUE TITLE
Pretrained parameters

### ISSUE THREAD

**Issue by fylinhub** [chemprop/chemprop#101]
Hi, 
I'm running predict.py with cpu based on a pre-trained modeled trained with cuda. 

It shows some warnings (below) and completed. I'd like to know if those warnings would matter the results? Thank you.

Predicting with an ensemble of 1 models
  0%|                                                                                                                                  | 0/1 [00:00<?, ?it/s]Warning: Pretrained parameter "encoder.encoder.cached_zero_vector" cannot be found in model parameters.
Warning: Pretrained parameter "encoder.encoder.W_i.weight" cannot be found in model parameters.
Warning: Pretrained parameter "encoder.encoder.W_h.weight" cannot be found in model parameters.
Warning: Pretrained parameter "encoder.encoder.W_o.weight" cannot be found in model parameters.
Warning: Pretrained parameter "encoder.encoder.W_o.bias" cannot be found in model parameters.
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
Loading pretrained parameter "ffn.7.weight".
Loading pretrained parameter "ffn.7.bias".
100%|██

**Comment by sunhwan** [comment]
Looks like chemprop version mismatch between your pre-trained model and prediction script.

**Comment by fylinhub** [comment]
@sunhwan hi Sunhwan!! yes, those results were not right; and it would become normal when retraining with the new version. Thank you for getting back to me with this issue.

**Comment by swansonk14** [comment]
Hi @fylinhub, thank you for bringing up the issue! And thank you @sunhwan for identifying the problem. It is indeed an issue with some parameter names changing between chemprop versions, but if you retrain your model using the latest code, then it should work.
