### ISSUE TITLE
[v2 BUG]: rdkit_2d can not be calculated in v2 version

### ISSUE THREAD

**Issue by xiaoboy185** [chemprop/chemprop#1026]
**Describe the bug**

chemprop train: error: argument --molecule-featurizers/--features-generators: invalid choice: 'rdkit_2d' (choose from 'morgan_binary', 'morgan_count')

**Example(s)**
Provide some examples of where the current code fails. Feel free to share your actual code for additional context, but a minimal and isolated example is preferred.

**Expected behavior**
A clear and concise description of what you expected to happen. If there is correct, expected output, include that here as well.

**Error Stack Trace**
If the bug is resulting in an error message, provide the _full_ stack trace (not just the last line). This is helpful for debugging, especially in cases where you aren't able to provide a minimum/isolated working example with accompanying files.

**Screenshots**

**Environment**
- python version
- package versions: `conda list` or `pip list`
- OS

**Checklist**
- [ ] all dependencies are satisifed: `conda list` or `pip list` shows the packages listed in the `pyproject.toml`
- [ ] the unit tests are working: `pytest -v` reports no errors

**Additional context**

**Comment by JacksonBurns** [comment]
`rdkit_2d` is in `main` but not yet in an official release version. It will be available in v2.1.0 which is coming in the near future. Install ChemProp from `main` if you want to use this feature now.
