### ISSUE TITLE
[v2 BUG]: MPNN.load_from_checkpoint() should pass map_location through load_submodules() to torch.load()

### ISSUE THREAD

**Issue by mefortunato** [chemprop/chemprop#1028]
**Describe the bug**
When loading a model that was trained on a GPU on a CPU only machine, [torch.load()](https://github.com/chemprop/chemprop/blob/main/chemprop/models/model.py#L245) should be told to load on the appropriate device. The `map_location` provided to [`load_from_checkpoint()`](https://github.com/chemprop/chemprop/blob/main/chemprop/models/model.py#L255) should be passed to [`load_submodules()`](https://github.com/chemprop/chemprop/blob/main/chemprop/models/model.py#L244) and subsequently `torch.load()`

**Example(s)**
```python
import chemprop

chemprop.models.MPNN.load_from_checkpoint(<gpu_trained_model.ckpt>, map_location='cpu')
```

**Expected behavior**
A model trained on a GPU should be able to be loaded on a CPU only machine.

**Error Stack Trace**
I do not have a traceback on hand, but presumably it is the same error from https://github.com/chemprop/chemprop/issues/949 whose fix only addressed `MPNN.load_from_file()`.

**Comment by shihchengli** [comment]
Hi @mefortunato, thanks for pointing out this issue. I have opened a PR (#1029).
