### ISSUE TITLE
[v2 Example]: Classification example notebook

### ISSUE THREAD

**Issue by KnathanM** [chemprop/chemprop#1030]
I see that we don’t have examples of training a classification model, only regression. We should add that. It is straightforward to adapt the regression example in chemprop/examples/training.ipynb for multitask binary classification by doing the following:

1.	Replace target_columns = [‘lipo’] with a list of the column headers in your data file (maybe tests/data/classification/mol.csv). 
2.	Remove the lines scaler = train_dset.normalize_targets(), val_dset.normalize_targets(scaler), and output_transform = nn.UnscaleTransform.from_standard_scaler(scaler) (classification targets shouldn’t be normalized)
3.	Replace ffn = nn.RegressionFFN(output_transform=output_transform) with ffn = nn.BinaryClassificationFFN(n_tasks = len(target_columns)) 
4.	Replace metric_list = [nn.metrics.RMSEMetric(), nn.metrics.MAEMetric()] with metric_list = None (or a list of the metrics you want, AUROC is used by default)

**Comment by Jameel9** [comment]
I used the command line for classification after I manually changed the labels to 0 and 1 in my csv file.
I ran the command below 
chemprop train --data-path balanced_dataset_new.csv --task-type classification --smiles-columns smiles --target-columns bioactivity --epochs 50 --num-folds 5 --num-workers 23 --output-dir chempr_results_class. 

![chemprop_classif_terminal](https://github.com/user-attachments/assets/5e9adca7-4908-43e4-8531-7d4035293200)

Then I used the best model to predict new data (ground-truth classes are known) and saw how things went. to the best of my understanding, the output values are probabilities. The closer to 0 means the molecule is expected to be in the class 0, while values approaching 1 are class 1 molecules. Is that a correct approach?

**Comment by Jameel9** [comment]
> I see that we don’t have examples of training a classification model, only regression. We should add that. It is straightforward to adapt the regression example in chemprop/examples/training.ipynb for multitask binary classification by doing the following:
> 
> 1. Replace target_columns = [‘lipo’] with a list of the column headers in your data file (maybe tests/data/classification/mol.csv).
> 2. Remove the lines scaler = train_dset.normalize_targets(), val_dset.normalize_targets(scaler), and output_transform = nn.UnscaleTransform.from_standard_scaler(scaler) (classification targets shouldn’t be normalized)
> 3. Replace ffn = nn.RegressionFFN(output_transform=output_transform) with ffn = nn.BinaryClassificationFFN(n_tasks = len(target_columns))
> 4. Replace metric_list = [nn.metrics.RMSEMetric(), nn.metrics.MAEMetric()] with metric_list = None (or a list of the metrics you want, AUROC is used by default)

I followed the steps above and it worked fine. My question is where to find the evaluation of model performance during the training/validation to plot some stuff and see the performance?
In the command line run, a csv file (metrics.csv) in the training log directory is found.

Thanks in advance!

**Comment by JacksonBurns** [comment]
@Jameel9 please open a new issue
