### ISSUE TITLE
[v2 BUG]:  Hyperparameter Optimization Encountered FileNotFoundError

### ISSUE THREAD

**Issue by xiongguoli** [chemprop/chemprop#1032]
In both of notebook and CLI, when I am tring to perform hyperparameter optimization, the same error occurs.

FileNotFoundError                         Traceback (most recent call last)
File D:\Program Files (x86)\anaconda\envs\chemprop\Lib\pathlib.py:1116, in Path.mkdir(self, mode, parents, exist_ok)
   1115 try:
-> 1116     os.mkdir(self, mode)
   1117 except FileNotFoundError:

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\lily\\AppData\\Local\\Temp\\ray\\session_2024-09-24_16-54-38_009815_4304\\artifacts\\2024-09-24_19-40-09\\TorchTrainer_2024-09-24_19-40-09\\driver_artifacts\\TorchTrainer_01fd72e3_1_depth=2,ffn_hidden_dim=2000,ffn_num_layers=2,message_hidden_dim=500_2024-09-24_19-40-09'

**Comment by JacksonBurns** [comment]
Moved to: https://github.com/chemprop/chemprop/issues/1033
