### ISSUE TITLE
[v2 QUESTION]: Hyperparameter Optimization Encountered FileNotFoundError

### ISSUE THREAD

**Issue by xiongguoli** [chemprop/chemprop#1033]
In both of notebook and CLI, when I am tring to perform hyperparameter optimization, the same error occurs. I want to know how to fix it.
FileNotFoundError Traceback (most recent call last)
File D:\Program Files (x86)\anaconda\envs\chemprop\Lib\pathlib.py:1116, in Path.mkdir(self, mode, parents, exist_ok)
1115 try:
-> 1116 os.mkdir(self, mode)
1117 except FileNotFoundError:
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\Users\lily\AppData\Local\Temp\ray\session_2024-09-24_16-54-38_009815_4304\artifacts\2024-09-24_19-40-09\TorchTrainer_2024-09-24_19-40-09\driver_artifacts\TorchTrainer_01fd72e3_1_depth=2,ffn_hidden_dim=2000,ffn_num_layers=2,message_hidden_dim=500_2024-09-24_19-40-09'

**Comment by xiongguoli** [comment]
> Chemprop is installed on your D: drive but ray is trying to use your C: drive for saving its temporary files. I think this is because the demo notebook makes the temp directory on the same drive as the notebook, which is presumably on C: - try specifying a valid directory on your D: drive as the temp directory for ray.

Thanks，I have changed the temp directory, but it doesn't work.

**Comment by shihchengli** [comment]
@xiongguoli I think this discussion (https://discuss.ray.io/t/winapi-createprocess-executable-args-filenotfounderror-winerror-2/5943/9) in the ray forum would be helpful.

**Comment by JacksonBurns** [comment]
Thanks @shihchengli 

When I ran this locally there was an additional warning that is quite helpful to know:
```
2024-09-25 12:11:03,549	WARNING trial.py:647 -- The path to the trial log directory is too long (max length: 260. Consider using `trial_dirname_creator` to shorten the path. Path: C:\Users\CHEMEG~1\AppData\Local\Temp\ray\session_2024-09-25_12-10-47_603636_35940\artifacts\2024-09-25_12-11-03\TorchTrainer_2024-09-25_12-11-03\driver_artifacts\TorchTrainer_c4356f00_1_depth=2,ffn_hidden_dim=2000,ffn_num_layers=2,message_hidden_dim=500_2024-09-25_12-11-03
```

Changing this:
```python
tune_config = tune.TuneConfig(
    metric="val_loss",
    mode="min",
    num_samples=2, # number of trials to run
    scheduler=scheduler,
    search_alg=search_alg,
)
```
to this:
tune_config = tune.TuneConfig(
    metric="val_loss",
    mode="min",
    num_samples=2, # number of trials to run
    scheduler=scheduler,
    search_alg=search_alg,
    trial_dirname_creator=lambda trial: str(trial.trial_id),  # <- add this line
)
```
fixed it for me.

@xiongguoli please try this and let us know if it works.

**Comment by xiongguoli** [comment]
It does work to some extent. However, another error RuntimeError arose, and the trial status were ERROR. I don't know if this issue is depend on my own local environment.
![1](https://github.com/user-attachments/assets/29b38df5-e53c-4e59-af3f-7d22e45a4823)
![2](https://github.com/user-attachments/assets/f6f80e88-4818-4fcc-a47a-c49f802bcc50)

**Comment by shihchengli** [comment]
@xiongguoli What is the pytorch version you installed? If it is v2.4, please downgrade it to older version.

**Comment by xiongguoli** [comment]
> @xiongguoli What is the pytorch version you installed? If it is v2.4, please downgrade it to older version.
yes，it is version 2.4.0, which version should I choose? v2.3.1?

**Comment by shihchengli** [comment]
as long as it is not v2.4

**Comment by xiongguoli** [comment]
> as long as it is not v2.4
Thanks a lot, I changed the torch version to 2.3.1 and the code ran smoothly. yeah~
