### ISSUE TITLE
[v2 QUESTION]: classification task

### ISSUE THREAD

**Issue by Jameel9** [chemprop/chemprop#1035]
Hi chemprop team,

First, thank you for your work and dedication to this helpful package.
I used the command line interface for classification after I manually changed the labels to 0 and 1 in my csv file.
I ran the command below
chemprop train --data-path balanced_dataset_new.csv --task-type classification --smiles-columns smiles --target-columns bioactivity --epochs 50 --num-folds 5 --num-workers 23 --output-dir chempr_results_class.  

chemprop_classif_terminal

Then I used the best model to predict new data (ground-truth classes are known) and saw how things went. to the best of my understanding, the output values are probabilities. The closer to 0 means the molecule is expected to be in the class 0, while values approaching 1 are class 1 molecules. Is that a correct approach?

Another thing is that I tried the python interface for a binary classification task, but I couldn't find the output/log of model evaluation (performance during the training/validation) to plot some stuff and see the performance.
In the command line run, a csv file (metrics.csv) in the training log directory is found.

Thanks in advance!

**Comment by JacksonBurns** [comment]
>> The closer to 0 means the molecule is expected to be in the class 0, while values approaching 1 are class 1 molecules. Is that a correct approach?

At a high level, yes. We have other methods to quantify uncertainty forthcoming, but this will give you a coarse idea of the output.

>> Another thing is that I tried the python interface for a binary classification task, but I couldn't find the output/log of model evaluation (performance during the training/validation) to plot some stuff and see the performance.

ChemProp logs intermediate results to tensorboard, when it is installed. You can see them by starting `tensorboard --logdir {your logging directory}`. If you don't have tensorboard installed, ChemProp warns you and uses CSV logging, so there would be a CSV file with intermediate results in the logging directory instead.
