### ISSUE TITLE
Parallel Operation in Chemprop for hyperparameter optimization

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#1043]
Hello,
I was wondering how we could speed up hyperparameter optimization in Chemprop. Is requesting multiple GPU in my slurm job enough to accelerate the hyperparameter optimization or do we need to add any specific arguments/ commands?
Thanks
Best,
Soo

**Comment by shihchengli** [comment]
Requesting multiple GPUs for a single trial can definitely help. You can also consider running multiple trials at the same time. For example, if you want to train on 4 trials simultaneously and each trial uses one GPU, you need to specify `--raytune-num-gpus 4` and `--raytune-max-concurrent-trials 4` via the CLI (see our [documentation](https://chemprop.readthedocs.io/en/main/tutorial/cli/hpopt.html#hyperparameter-optimization)). The current CLI only supports multi-GPU training. If you have a multi-node GPU setup, you would need to modify some code and run it on your notebook.
https://github.com/chemprop/chemprop/blob/main/examples/hpopting.ipynb
