### ISSUE TITLE
[v2 QUESTION]: Encounter errors when train models. Please help me.

### ISSUE THREAD

**Issue by langcaijinjiangyan** [chemprop/chemprop#1044]
I try to train models in followed command:
`chemprop train -t regression -i data/simple-data.csv -s isosmiles -o model`

This is my input data:
[simple-data.csv](https://github.com/user-attachments/files/17289943/simple-data.csv)

This is the result:

> Wrote config file to model\config.toml
> [15:08:51] **Explicit valence for atom # 1 Cl, 7, is greater than permitted**
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\chemprop.exe\__main__.py", line 7, in <module>
> op\cli\main.py", line 80, in main
>     func(args)
>   File "C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\chemprop\cli\train.py", line 75, in func
>     main(args)
>   File "C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\chemprop\cli\train.py", line 978, in main
>     splits = build_splits(args, format_kwargs, featurization_kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\chemprop\cli\train.py", line 585, in build_splits
>     all_data = build_data_from_files(
>                ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\chemprop\cli\utils\parsing.py", line 340, in build_data_from_files
>     mol_data, rxn_data = make_datapoints(
>                          ^^^^^^^^^^^^^^^^
>   File "C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\chemprop\cli\utils\parsing.py", line 267, in make_datapoints
>     MoleculeDatapoint(
>   File "<string>", line 14, in __init__
>   File "C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\chemprop\data\datapoints.py", line 79, in __post_init__
>     raise ValueError("Input molecule was `None`!")
> ValueError: Input molecule was `None`!

I found that errors occur when the last line molecule **O=Cl(=O)(=O)F** is added to the training data.
It seems that chemprop does not support 7-valent chlorine.
Or this is because any other reasons?

Please help me! Thanks!

**Comment by JacksonBurns** [comment]
The version of RDKit you have installed does not support this species. Consider opening an issue on the RDKit repository for further assistance.
