### ISSUE TITLE
Interpret.py error using tox21 data

### ISSUE THREAD

**Issue by domgurvic** [chemprop/chemprop#107]
Using provided tox21 data and examples in the README: 

Command: 

python interpret.py --data_path data/tox21.csv --checkpoint_dir tox21_checkpoints --property_id 1 --features_generator rdkit_2d_
normalized --no_features_scaling

Error:

Loading pretrained parameter "encoder.encoder.0.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.0.W_i.weight".
Loading pretrained parameter "encoder.encoder.0.W_h.weight".
Loading pretrained parameter "encoder.encoder.0.W_o.weight".
Loading pretrained parameter "encoder.encoder.0.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
Moving model to cuda
smiles,NR-AR,rationale,rationale_score
['CCOc1ccc2nc(S(N)(=O)=O)sc2c1'],0.023,,
['CCN1C(=O)NC(c2ccccc2)C1=O'],0.030,,
Traceback (most recent call last):
  File "interpret.py", line 7, in <module>
    chemprop_interpret()
  File "/cluster/uz_lab/dgurvic/chemprop_latest/chemprop/interpret.py", line 335, in chemprop_interpret
    interpret(args=InterpretArgs().parse_args())
  File "/cluster/uz_lab/dgurvic/chemprop_latest/chemprop/utils.py", line 402, in wrap
    result = func(*args, **kwargs)
  File "/cluster/uz_lab/dgurvic/chemprop_latest/chemprop/interpret.py", line 316, in interpret
    prop_delta=args.prop_delta
  File "/cluster/uz_lab/dgurvic/chemprop_latest/chemprop/interpret.py", line 263, in mcts
    mol = Chem.MolFromSmiles(smiles)
TypeError: No registered converter was able to produce a C++ rvalue of type std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > from this Python object of type list

It looks like MolFromSmiles in mcts function receives list of smiles rather than single smile?

**Comment by hesther** [comment]
Thanks so much for reporting, and sorry for not getting back to you earlier. We will fix this bug very soon.
