### ISSUE TITLE
[v2 BUG]: Bug with `--splits-column`

### ISSUE THREAD

**Issue by yunsiechung** [chemprop/chemprop#1073]
**Describe the bug**
Hi, I am a senior scientist from Merck and we are part of the MLPDS Consortium. 
An error occur whenever `-splits-column` input argument is used for training. The input argument is a string like `--splits-column split`, but Chemprop expects it to be a list, causing an error and aborting the job.

**Example(s)**
I ran the exact example provided on Chemprop v2 documentation.

`chemprop train --splits-column split -i dummy_data_with_split.csv -t regression`

with dummy_data_with_split.csv
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/chunyuns/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/chunyuns/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

smiles | property | split
-- | -- | --
C | 1 | train
CC | 2 | train
CCC | 3 | test
CCCC | 4 | val
CCCCC | 5 | val
CCCCCC | 6 | test

</body>

</html>

**Error Stack Trace**
And this returns the following error message:

> Traceback (most recent call last):
  File "/home/chunyuns/.conda/envs/chemprop_v2/bin/chemprop", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/chunyuns/git_repo/chemprop/chemprop/cli/main.py", line 85, in main
    func(args)
  File "/home/chunyuns/git_repo/chemprop/chemprop/cli/train.py", line 83, in func
    args = process_train_args(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chunyuns/git_repo/chemprop/chemprop/cli/train.py", line 526, in process_train_args
    input_cols, target_cols = get_column_names(
                              ^^^^^^^^^^^^^^^^^
  File "/home/chunyuns/git_repo/chemprop/chemprop/cli/utils/parsing.py", line 84, in get_column_names
    df_cols = pd.read_csv(path, index_col=False, nrows=0).columns.tolist()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chunyuns/.conda/envs/chemprop_v2/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chunyuns/.conda/envs/chemprop_v2/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chunyuns/.conda/envs/chemprop_v2/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chunyuns/.conda/envs/chemprop_v2/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/chunyuns/.conda/envs/chemprop_v2/lib/python3.11/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dummy_data_with_split.csv'

**Environment**
I am using the latest `main` branch and installed chemprop from source using pip
- python version: 3.11.10
- package versions: same as what will be installed when installed from source using pip
- OS: Linux

**How to Fix**
This can be fixed by modifying the code in `chemprop/cli/utils/parsing.py`.
On line 56 and line 99, 
Current code: `not in set(input_cols + (ignore_cols or []) + (splits_col or []) + (weight_col or []))`
After fix: `not in set(input_cols + (ignore_cols or []) + ([splits_col] or []) + (weight_col or []))`

Whether `weight_col` should be changed to `[weight_col]` or not should also be investigated.
`ignore_cols` could be left as it is since `--ignore-columns split` did not result in the error.

**Comment by KnathanM** [comment]
Hi Yunsie,

Thank you for pointing out this error. I'm not really sure how I didn't notice it in the last six months... We are releasing a new version of Chemprop tomorrow and will include this fix. Take a look at #1074 where I implement your fix.

**Comment by yunsiechung** [comment]
Hi Nathan,
Thank you so much for a quick fix! I will close this now.
