### ISSUE TITLE
[v2 QUESTION]: How to incorporate x_d calculated under DFT theory in front of FNN layers

### ISSUE THREAD

**Issue by yyyzzz111** [chemprop/chemprop#1087]
**What are you trying to do?**
I want to use chemprop to train a set of my own data for regression prediction of molecular physical properties, the csv file contains a column of smiles, target and an additional column of molecular features.

**Previous attempts**
**I didn't add x_d at first, and the whole code works fine.
But when I added the extra x_d, after that the trainer process started reporting errors as follows: The problem is that the FNN layer has the wrong number of input features**

Cell In[282], line 1
----> 1 trainer.fit(mpnn, train_loader, val_loader)

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\lightning\pytorch\trainer\trainer.py:538, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    536 self.state.status = TrainerStatus.RUNNING
    537 self.training = True
--> 538 call._call_and_handle_interrupt(
    539     self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    540 )

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\lightning\pytorch\trainer\call.py:47, in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     45     if trainer.strategy.launcher is not None:
     46         return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
---> 47     return trainer_fn(*args, **kwargs)
     49 except _TunerExitException:
     50     _call_teardown_hook(trainer)

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\lightning\pytorch\trainer\trainer.py:574, in Trainer._fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    567 assert self.state.fn is not None
    568 ckpt_path = self._checkpoint_connector._select_ckpt_path(
    569     self.state.fn,
    570     ckpt_path,
    571     model_provided=True,
    572     model_connected=self.lightning_module is not None,
    573 )
--> 574 self._run(model, ckpt_path=ckpt_path)
    576 assert self.state.stopped
    577 self.training = False

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\lightning\pytorch\trainer\trainer.py:981, in Trainer._run(self, model, ckpt_path)
    976 self._signal_connector.register_signal_handlers()
    978 # ----------------------------
    979 # RUN THE TRAINER
    980 # ----------------------------
--> 981 results = self._run_stage()
    983 # ----------------------------
    984 # POST-Training CLEAN UP
    985 # ----------------------------
    986 log.debug(f"{self.__class__.__name__}: trainer tearing down")

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\lightning\pytorch\trainer\trainer.py:1023, in Trainer._run_stage(self)
   1021 if self.training:
   1022     with isolate_rng():
-> 1023         self._run_sanity_check()
   1024     with torch.autograd.set_detect_anomaly(self._detect_anomaly):
   1025         self.fit_loop.run()

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\lightning\pytorch\trainer\trainer.py:1052, in Trainer._run_sanity_check(self)
   1049 call._call_callback_hooks(self, "on_sanity_check_start")
   1051 # run eval step
-> 1052 val_loop.run()
   1054 call._call_callback_hooks(self, "on_sanity_check_end")
   1056 # reset logger connector

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\lightning\pytorch\loops\utilities.py:178, in _no_grad_context.<locals>._decorator(self, *args, **kwargs)
    176     context_manager = torch.no_grad
    177 with context_manager():
--> 178     return loop_run(self, *args, **kwargs)

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\lightning\pytorch\loops\evaluation_loop.py:135, in _EvaluationLoop.run(self)
    133     self.batch_progress.is_last_batch = data_fetcher.done
    134     # run step hooks
--> 135     self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
    136 except StopIteration:
    137     # this needs to wrap the `*_step` call too (not just `next`) for `dataloader_iter` support
    138     break

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\lightning\pytorch\loops\evaluation_loop.py:396, in _EvaluationLoop._evaluation_step(self, batch, batch_idx, dataloader_idx, dataloader_iter)
    390 hook_name = "test_step" if trainer.testing else "validation_step"
    391 step_args = (
    392     self._build_step_args_from_hook_kwargs(hook_kwargs, hook_name)
    393     if not using_dataloader_iter
    394     else (dataloader_iter,)
    395 )
--> 396 output = call._call_strategy_hook(trainer, hook_name, *step_args)
    398 self.batch_progress.increment_processed()
    400 if using_dataloader_iter:
    401     # update the hook kwargs now that the step method might have consumed the iterator

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\lightning\pytorch\trainer\call.py:319, in _call_strategy_hook(trainer, hook_name, *args, **kwargs)
    316     return None
    318 with trainer.profiler.profile(f"[Strategy]{trainer.strategy.__class__.__name__}.{hook_name}"):
--> 319     output = fn(*args, **kwargs)
    321 # restore current_fx when nested context
    322 pl_module._current_fx_name = prev_fx_name

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\lightning\pytorch\strategies\strategy.py:411, in Strategy.validation_step(self, *args, **kwargs)
    409 if self.model != self.lightning_module:
    410     return self._forward_redirection(self.model, self.lightning_module, "validation_step", *args, **kwargs)
--> 411 return self.lightning_module.validation_step(*args, **kwargs)

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\chemprop\models\model.py:160, in MPNN.validation_step(self, batch, batch_idx)
    159 def validation_step(self, batch: TrainingBatch, batch_idx: int = 0):
--> 160     self._evaluate_batch(batch, "val")
    162     bmg, V_d, X_d, targets, weights, lt_mask, gt_mask = batch
    164     mask = targets.isfinite()

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\chemprop\models\model.py:180, in MPNN._evaluate_batch(self, batch, label)
    178 mask = targets.isfinite()
    179 targets = targets.nan_to_num(nan=0.0)
--> 180 preds = self(bmg, V_d, X_d)
    181 weights = torch.ones_like(weights)
    183 if self.predictor.n_targets > 1:

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\module.py:1736, in Module._wrapped_call_impl(self, *args, **kwargs)
   1734     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1735 else:
-> 1736     return self._call_impl(*args, **kwargs)

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\module.py:1747, in Module._call_impl(self, *args, **kwargs)
   1742 # If we don't have any hooks, we want to skip the rest of the logic in
   1743 # this function, and just call forward.
   1744 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1745         or _global_backward_pre_hooks or _global_backward_hooks
   1746         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1747     return forward_call(*args, **kwargs)
   1749 result = None
   1750 called_always_called_hooks = set()

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\chemprop\models\model.py:139, in MPNN.forward(self, bmg, V_d, X_d)
    135 def forward(
    136     self, bmg: BatchMolGraph, V_d: Tensor | None = None, X_d: Tensor | None = None
    137 ) -> Tensor:
    138     """Generate predictions for the input molecules/reactions"""
--> 139     return self.predictor(self.fingerprint(bmg, V_d, X_d))

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\module.py:1736, in Module._wrapped_call_impl(self, *args, **kwargs)
   1734     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1735 else:
-> 1736     return self._call_impl(*args, **kwargs)

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\module.py:1747, in Module._call_impl(self, *args, **kwargs)
   1742 # If we don't have any hooks, we want to skip the rest of the logic in
   1743 # this function, and just call forward.
   1744 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1745         or _global_backward_pre_hooks or _global_backward_hooks
   1746         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1747     return forward_call(*args, **kwargs)
   1749 result = None
   1750 called_always_called_hooks = set()

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\chemprop\nn\predictors.py:164, in RegressionFFN.forward(self, Z)
    163 def forward(self, Z: Tensor) -> Tensor:
--> 164     return self.output_transform(self.ffn(Z))

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\module.py:1736, in Module._wrapped_call_impl(self, *args, **kwargs)
   1734     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1735 else:
-> 1736     return self._call_impl(*args, **kwargs)

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\module.py:1747, in Module._call_impl(self, *args, **kwargs)
   1742 # If we don't have any hooks, we want to skip the rest of the logic in
   1743 # this function, and just call forward.
   1744 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1745         or _global_backward_pre_hooks or _global_backward_hooks
   1746         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1747     return forward_call(*args, **kwargs)
   1749 result = None
   1750 called_always_called_hooks = set()

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\container.py:250, in Sequential.forward(self, input)
    248 def forward(self, input):
    249     for module in self:
--> 250         input = module(input)
    251     return input

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\module.py:1736, in Module._wrapped_call_impl(self, *args, **kwargs)
   1734     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1735 else:
-> 1736     return self._call_impl(*args, **kwargs)

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\module.py:1747, in Module._call_impl(self, *args, **kwargs)
   1742 # If we don't have any hooks, we want to skip the rest of the logic in
   1743 # this function, and just call forward.
   1744 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1745         or _global_backward_pre_hooks or _global_backward_hooks
   1746         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1747     return forward_call(*args, **kwargs)
   1749 result = None
   1750 called_always_called_hooks = set()

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\container.py:250, in Sequential.forward(self, input)
    248 def forward(self, input):
    249     for module in self:
--> 250         input = module(input)
    251     return input

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\module.py:1736, in Module._wrapped_call_impl(self, *args, **kwargs)
   1734     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1735 else:
-> 1736     return self._call_impl(*args, **kwargs)

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\module.py:1747, in Module._call_impl(self, *args, **kwargs)
   1742 # If we don't have any hooks, we want to skip the rest of the logic in
   1743 # this function, and just call forward.
   1744 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1745         or _global_backward_pre_hooks or _global_backward_hooks
   1746         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1747     return forward_call(*args, **kwargs)
   1749 result = None
   1750 called_always_called_hooks = set()

File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\linear.py:125, in Linear.forward(self, input)
    124 def forward(self, input: Tensor) -> Tensor:
--> 125     return F.linear(input, self.weight, self.bias)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x301 and 300x300)

**Screenshots**
**Some of my training code is below, and I'm not sure how I should properly add x-d to the input features.**
# data
smiles_column = 'smiles'
target_columns = ['target']
x_d_columns = ['LEAmax']  #LEAmax is the molecular descriptor for my additional calculations, a set of floating point data

df_input = pd.read_csv(input_path)
smis = df_input.loc[:, smiles_column].values
ys_raw = df_input.loc[:, target_columns].values
ys = np.log1p(ys_raw)
x_d =  df_input.loc[:, x_d_columns].values

all_data = [data.MoleculeDatapoint.from_smi(smi, y, x_d=x_d) for smi, y ,x_d in zip(smis, ys, x_d)]
mols = [d.mol for d in all_data]  # RDkit Mol objects are use for structure based splits
train_indices, val_indices, test_indices = data.make_split_indices(mols, "random", (0.8, 0.1, 0.1))  # unpack the tuple into three separate lists
train_data, val_data, test_data = data.split_data_by_indices(
    all_data, train_indices, val_indices, test_indices
)
featurizer = featurizers.SimpleMoleculeMolGraphFeaturizer()

train_dset = data.MoleculeDataset(train_data[0], featurizer)
scaler = train_dset.normalize_targets()

val_dset = data.MoleculeDataset(val_data[0], featurizer)
val_dset.normalize_targets(scaler)

test_dset = data.MoleculeDataset(test_data[0], featurizer)
train_loader = data.build_dataloader(train_dset, num_workers=num_workers)
val_loader = data.build_dataloader(val_dset, num_workers=num_workers, shuffle=False)
test_loader = data.build_dataloader(test_dset, num_workers=num_workers, shuffle=False)

mp_bond = nn.BondMessagePassing()
agg = nn.MeanAggregation()
# x_d
X_d_scaler = train_dset.normalize_inputs("X_d")
val_dset.normalize_inputs("X_d", X_d_scaler)
X_d_transform = ScaleTransform.from_standard_scaler(X_d_scaler)

output_transform = nn.UnscaleTransform.from_standard_scaler(scaler)
ffn = nn.RegressionFFN(output_transform=output_transform)

batch_norm = True
metric_list = [nn.metrics.MSE(), nn.metrics.R2Score(), nn.metrics.MAE()] # Only the first metric is used for training and early stopping
mpnn = models.MPNN(mp_bond, agg, ffn, batch_norm,  metric_list, X_d_transform=X_d_transform)
checkpointing = ModelCheckpoint(
    "checkpoints",  # Directory where model checkpoints will be saved
    "best-{epoch}-{val_loss:.2f}",  # Filename format for checkpoints, including epoch and validation loss
    "val_loss",  # Metric used to select the best checkpoint (based on validation loss)
    mode="min",  # Save the checkpoint with the lowest validation loss (minimization objective)
    save_last=True,  # Always save the most recent checkpoint, even if it's not the best
)

trainer = pl.Trainer(
    logger=False,
    enable_checkpointing=True, # Use `True` if you want to save model checkpoints. The checkpoints will be saved in the `checkpoints` folder.
    enable_progress_bar=True,
    accelerator="auto",
    devices=1,
    max_epochs=75, # number of epochs to train for
    callbacks=[checkpointing], # Use the configured checkpoint callback
)
trainer.fit(mpnn, train_loader, val_loader)

**Comment by shihchengli** [comment]
Please refer to the module notebook (https://chemprop.readthedocs.io/en/main/tutorial/python/models/predictor.html#Input-dimension).
