### ISSUE TITLE
[v2 QUESTION]: How do I specify a specific GPU when I have multiple GPUs?

### ISSUE THREAD

**Issue by yaosichao0915** [chemprop/chemprop#1095]
I need to specify a specific GPU when I have multiple GPUs. Considering CLI "--data_seeds" seems to control the total GPU to use. Could anynoe tell me whether this can be done by CLI, and how?

**Comment by shihchengli** [comment]
You should use `--devices` to control which gpu device(s) to use. It will be passed directly to the lightning ``Trainer()`` (must be a single string of comma separated devices, e.g. '1, 2' if specifying multiple devices).
