### ISSUE TITLE
[v2 QUESTION]: predictions with v1_rdkit_2d_normalized

### ISSUE THREAD

**Issue by yaosichao0915** [chemprop/chemprop#1096]
If I train my model with flag --molecule-featurizers v1_rdkit_2d_normalized --no-descriptor-scaling, I am wondering how to use the trained model to predict the new ones. Assuming I want to use jupyter notebook to do this, how that would be different from the predicting.ipynb in the examples.

**Comment by JacksonBurns** [comment]
@KnathanM do we have a "Chemprop as a module" demo notebook for predicting with feature generators?

**Comment by KnathanM** [comment]
This [notebook](https://chemprop.readthedocs.io/en/latest/tutorial/python/featurizers/molecule_featurizers.html) is the closest one. 

I think this is as simple as using:
```
from chemprop.featurizers.molecule import  V1RDKit2DNormalizedFeaturizer
from chemprop.utils import make_mol

molecule_featurizer = V1RDKit2DNormalizedFeaturizer()
mols = [make_mol(smi, keep_h=False, add_h=False) for smi in smis]
test_data = [data.MoleculeDatapoint(mol, x_d=molecule_featurizer(mol)) for mol in mols]
```
instead of 
```
test_data = [data.MoleculeDatapoint.from_smi(smi) for smi in smis]
```
in `predicting.ipynb`.
