### ISSUE TITLE
[v2 QUESTION]: Which activation functions can be passed to the activation parameters of Regression FFN( )?

### ISSUE THREAD

**Issue by DengFeng-Zuo** [chemprop/chemprop#1099]
**What are you trying to do?**
I need to find the optimal hyperparameters for the ffn layer, but I haven't found any instructions on how to define the search space for hyperparameters of the activation function.What other activation functions can be passed in besides “relu”? Is the name of the activation function case sensitive?

**Previous attempts**
If possible, provide some examples of what you've already tried and what the output was.

**Screenshots**
![微信截图_1](https://github.com/user-attachments/assets/1d4c398e-5087-434f-8afc-a15493d53b34)
![微信截图2](https://github.com/user-attachments/assets/6663ff1c-75e0-4fa8-907f-3a8c115e7b3f)

**Comment by shihchengli** [comment]
For HPO, you can try our hpopt CLI (https://chemprop.readthedocs.io/en/main/tutorial/cli/hpopt.html) with 
`--search-parameter-keywords activation` to search for activation functions. Choices include `relu`, `leakyrelu`, `prelu`, `tanh`, `selu`, and `elu`. It is not case sensitive as it will be changed to upper case [here](https://github.com/chemprop/chemprop/blob/main/chemprop/utils/utils.py#L12-L16).
