### ISSUE TITLE
[v2 BUG]: Tracking metric gets overwritten when --num-replicates is greater than 1

### ISSUE THREAD

**Issue by am2145** [chemprop/chemprop#1102]
**Describe the bug**
When using the --tracking-metric argument for early stopping, a `Key Error` occurs if --num-replicates is greater than 1. I suspect this is due to line 1098 in `train.py` where `args.tracking_metric` is overwritten during the first replicate, so subsequent replicates encounter an issue on line 1097 when searching through `MetricRegistry`.

**Comment by shihchengli** [comment]
@am2145  thanks for reporting this issue. You are right that this is due to the overwritten of this variable. I have opened an PR #1105.
