### ISSUE TITLE
predictions with v1_rdkit_2d_normalized and no scaling

### ISSUE THREAD

**Issue by yaosichao0915** [chemprop/chemprop#1116]
This [notebook](https://chemprop.readthedocs.io/en/latest/tutorial/python/featurizers/molecule_featurizers.html) is the closest one. 

I think this is as simple as using:
```
from chemprop.featurizers.molecule import  V1RDKit2DNormalizedFeaturizer
from chemprop.utils import make_mol

molecule_featurizer = V1RDKit2DNormalizedFeaturizer()
mols = [make_mol(smi, keep_h=False, add_h=False) for smi in smis]
test_data = [data.MoleculeDatapoint(mol, x_d=molecule_featurizer(mol)) for mol in mols]
```
instead of 
```
test_data = [data.MoleculeDatapoint.from_smi(smi) for smi in smis]
```
in `predicting.ipynb`.

_Originally posted by @KnathanM in https://github.com/chemprop/chemprop/issues/1096#issuecomment-2463033546_

**Comment by yaosichao0915** [comment]
I have tried with these codes, at least it worked with no error but the predictions were different from the CLI version. I guess there is something not right with the scaling part, since I added the --no-descriptor-scaling flag in the CLI version.

**Comment by JacksonBurns** [comment]
@KnathanM please see above

**Comment by yaosichao0915** [comment]
I found a bug in my own code, it's fine now, thank you for your solution
