### ISSUE TITLE
protein sequence embeddings as auxiliary features

### ISSUE THREAD

**Issue by mmagithub** [chemprop/chemprop#1117]
Hi,
I was wondering if the current Chemprop implementation supports using protein sequence embeddings, such as ESM embeddings, as auxiliary features. Specifically, I have a protein-ligand interaction dataset for multiple targets against multiple ligands data (y variable is Ki or ic50) and would like to train a Chemprop model that incorporates these protein sequence embeddings as input features. Additionally, would it be possible to make predictions for entirely new or existing protein-ligand pairs using such a model?

If this functionality is available, is it possible to finetune the pretrained model on a smaller dataset and use the fine-tuned model to make novel predictions, say for an entirely new protein-ligand pairs?

Thanks
Marawan

**Comment by JacksonBurns** [comment]
Hi @mmagithub Chemprop doesn't explicitly support generation of these features, but you can generate them yourself and pass them in via the [`--descriptors-path`](https://chemprop.readthedocs.io/en/latest/cmd.html#featurization-args) argument. You could then use this model in the way you have suggested, yes.

You can fine tune a pre-trained model with transfer learning using [these arguments](https://chemprop.readthedocs.io/en/latest/cmd.html#transfer-learning-args).

All of the above functionality is also available when coding in Python, see the [tutorials](https://chemprop.readthedocs.io/en/latest/tutorial/python/index.html).
