### ISSUE TITLE
[v2 BUG]: ValueError when saving chemprop predictions to file

### ISSUE THREAD

**Issue by am2145** [chemprop/chemprop#1125]
**Describe the bug**
I'm encountering an error when running chemprop predict through the CLI where saving of predictions fails.

**Example(s)**
The prediction script I'm attempting to run is the most basic case: inference on a single trained model: 

<img width="475" alt="image" src="https://github.com/user-attachments/assets/d2dfa46e-15e5-443c-ae16-e1dfff3c1b15" />

The predict dataloader and inference part appear to work fine, but a Value error occurs when saving these predictions to file (full traceback below). It seems like the test predictions are in two batches which causes an issue when trying to assign them to a column the test dataframe, but I'm not sure why this is happening. 

**Error Stack Trace**
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/44362e0f-add7-4bff-8cf9-f8f1a3271c20" />

**Comment by shihchengli** [comment]
Hi @am2145, are you doing inference on 31 instances with 2 GPUs? If so, you might need to use a single GPU or run entirely on the CPU to make the predictions.

**Comment by am2145** [comment]
Yes, that was it. I had copied over a training script which had the CUDA_VISIBLE_DEVICES setting commented out as training supports multiple GPUs. Thanks @shihchengli!
