### ISSUE TITLE
[v2 QUESTION]: Who is the optimal parameter?

### ISSUE THREAD

**Issue by jia-huang** [chemprop/chemprop#1126]
After I use the following command to find the optimal parameters, I need to use the optimal parameters for the next training. However, I cannot find a file named "best_config.toml" in the results folder. Which toml file should I use from the folder?

chemprop hpopt --data-path tests/data/regression.csv \
    --task-type regression \
    --search-parameter-keywords depth ffn_num_layers message_hidden_dim \
    --hpopt-save-dir results

chemprop train --data-path tests/data/regression.csv \
    --config-path results/best_config.toml
    
    
![截图](https://github.com/user-attachments/assets/c9fba41b-3eb7-4196-93f2-2722b2914b0c)

**Comment by shihchengli** [comment]
It should be saved under your results folder, unless your hpopt was run successfully.

**Comment by jia-huang** [comment]
> It should be saved under your results folder, unless your hpopt was run successfully.

My hpopt has successfully finished running, but the result files I received are shown in the image below, and I don't see a best_config.toml file.

![截图](https://github.com/user-attachments/assets/2eb51d58-2a53-4362-8519-a6e0aed40246)

**Comment by shihchengli** [comment]
After running hpopt, have you seen any information about "Best hyperparameters saved to: ..."?

**Comment by jia-huang** [comment]
> s

yes , i got it ,thank you!
