### ISSUE TITLE
[v2 QUESTION]: python module equivalents of -atom-features-path and --atom-descriptors-path

### ISSUE THREAD

**Issue by kozaczki** [chemprop/chemprop#1128]
Hi, I am trying to put some extra features on atoms in molecules, and I am a bit confused as to what is the python module equivalent of command line module  -atom-features-path and --atom-descriptors-path? Thank you

**Comment by JacksonBurns** [comment]
You pass them to `MoleculeDatapoint` on initialization, see: https://chemprop.readthedocs.io/en/latest/tutorial/python/data/datapoints.html#Extra-features-and-descriptors
