### ISSUE TITLE
[v2 QUESTION]: test dataset of ensemble 

### ISSUE THREAD

**Issue by jia-huang** [chemprop/chemprop#1130]
When using the following commands for training, is the test set the same for each model? If it is the same, how can we adjust the settings to ensure that each model's test set is different?

chemprop train --data-path FDA-smiles.csv --task-type classification --output-dir FDA_checkpoints_rdkit_2d-hpopt-20ensembl-8 --molecule-featurizers v1_rdkit_2d_normalized --no-descriptor-scaling **--ensemble-size 20** --config-path best_config_zidong.toml --epochs 30

 Additionally, how can we configure the settings to implement 20-fold cross-validation during training?

**Comment by shihchengli** [comment]
If you use `--ensemble-size`, it trains 20 models on the same data split. To run 20-fold cross-validation, you need to create a JSON file with 20 splits on your own (an example can be found [here](https://chemprop.readthedocs.io/en/main/tutorial/cli/train.html#id3)).
