### ISSUE TITLE
Multiprocessing sets global variables back to default in MoleculeDataLoader (Python 3.8, macOS)

### ISSUE THREAD

**Issue by hesther** [chemprop/chemprop#115]
In Python 3.8 on macOS, the default to spawn parallel processes was changed from "fork" to "spawn", which causes all global variables to be reinitialised to their default values when using MoleculeDataLoader in parallel, so that all global variables are wrong within the data loader. This affects e.g. the atom features, or caching.

For those who want to use Chemprop with Python 3.8 on macOS: run with `--num_workers 0`.

I suggest getting rid of the global variables in the long run, so that running Chemprop across different OSs and python versions does not cause more problems in the future. I will update this issue with corresponding thoughts later this week.

**Comment by davidegraff** [comment]
the overreliance on global variables is a limitation of the core code. It's something that'll be fixed with v2!
