### ISSUE TITLE
The  --atom_descriptors does not work with the predict.py ?

### ISSUE THREAD

**Issue by bartl88** [chemprop/chemprop#120]
I'm trying to add an atom based descriptor as atom feature, as has been described in the last release notes.
This nicely works! 

python train.py --dataset_type regression --save_dir Models/Model0 --data_path train_100.csv --atom_descriptors feature --atom_descriptors_path train_100.pkl --split_sizes 0.9 0.1 0

Now however if I try to use the predict.py: 
python predict.py --test_path test_10.csv --preds_path Predictions/model0.csv --checkpoint_dir Models/Model0/ --atom_descriptors feature --atom_descriptors_path test_10.pkl
**I get an error: ValueError: expected sequence of length 133 at dim 1 (got 134)** 

It does run if I discard the --atom* flags (so python predict.py --test_path test_10.csv --preds_path Predictions/model0.csv --checkpoint_dir Models/Model0/ ) But these predictions don't make any sense.

Are the --atom_descriptor flags used by the predict.py, or am I doing something wrong? If needed I can attach the example files.

**Comment by mliu49** [comment]
Thanks for reporting this issue! I think we are aware of this and a fix is in the pipeline. You can check out the current status in PR #114.

**Comment by hesther** [comment]
Thanks! If you want to use predict.py straight away, you could add the three lines in chemprop/train/make_predictions.py as in PR [114](https://github.com/chemprop/chemprop/pull/114/files) - let me know if you need help!

As a minor comment: running without the `--atom_descriptors feature` flag changes the atom features serving as input to the MPNN, so the predictions will be nonsense. To prevent users from accidentally doing so, we should add a little check, similar to checking the molecular feature arguments in `make_predictions()`. Will add this to PR 114 now.

**Comment by bartl88** [comment]
Thanks Hester and Max!
That works, and is better in terms of performance on the test set :)

**Comment by hesther** [comment]
Thanks for reporting! PR 114 was just merged - pulling the update will fix the issue.
