### ISSUE TITLE
atom_descriptors

### ISSUE THREAD

**Issue by Xu22** [chemprop/chemprop#121]
How can I add atom_descriptors to your model?

**Comment by hesther** [comment]
You can load atom descriptors from a sdf, npz or pkl file via the command line option `--atom_descriptors_path <path_to_file>` and use the descriptors either via `--atom_descriptors feature` (as extra atom features during the molecule featurization, that is, they are added to the regular atom features before the MPNN) or via `--atom_descriptors descriptor` (atomic descriptors are concatenated to the atomic feature vector after MPNN before aggregating the atoms to a molecule).

The data file should look like:
- `.npz` descriptors are saved as 2D array for each molecule in the order of that in the data.csv
- `.pkl` / `.pckl` / `.pickle` containing a pandas dataframe with smiles as index and numpy array of descriptors as columns
- `.sdf` containing all mol blocks with descriptors as entries

Hope this helps!

**Comment by Xu22** [comment]
Thanks a lot!
