### ISSUE TITLE
Error Building SciPy

### ISSUE THREAD

**Issue by daverdude** [chemprop/chemprop#123]
I have been using chemprop since early last year and recently had to rebuild the program, but I have continuously been met with an error while building the wheels for SciPy (Error with PEP 517). Not sure if the dependencies listed in the requirements txt file are outdated, but I have not been able to solve this issue.

**Comment by hesther** [comment]
Thanks for reporting. Could you provide some more details about which OS you are using, and which python version? Specifically, I have seen problems with building scipy when on python 3.9. If this is the case, downgrading to python 3.6, 3.7 or 3.8 and rebuilding chemprop will solve the problem for now, until we have looked into this more.

**Comment by hesther** [comment]
If you are using Conda, the easiest way to do so may be to set up a new Conda environment with a specific python version by changing `python>=3.6` to e.g. `python=3.8` in `environment.yml.` You might also want to change the name of the environment in the first line. Creating the environment via `conda env create -f environment.yml`, activating it, and rebuilding chemprop should work then.
