### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by Xu22** [chemprop/chemprop#124]
Can you provide the internal data to me? Thank you !

**Comment by hesther** [comment]
Dear Xu22, I am not quite sure whether I understand your request correctly. Chemprop comes with a number of datasets in compressed format, if you want to use them, simply decompress them:

`tar -xvzf data.tar.gz`

in the chemprop folder, which will give you a `data` folder with a few datasets. If this was not what you were asking for, let me know!
