### ISSUE TITLE
Risk of shared library incompatibility

### ISSUE THREAD

**Issue by mliu49** [chemprop/chemprop#129]
The currently recommended installation method introduces a risk of shared library incompatibility due to mixed use of conda and pip. The following import error is the result. A similar error was previously reported in #42.

```
  File "/app/chemprop/__init__.py", line 1, in <module>
    import chemprop.data
  File "/app/chemprop/data/__init__.py", line 1, in <module>
    from .data import (
  File "/app/chemprop/data/data.py", line 8, in <module>
    from rdkit import Chem
  File "/opt/conda/lib/python3.8/site-packages/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import DataStructs
  File "/opt/conda/lib/python3.8/site-packages/rdkit/DataStructs/__init__.py", line 13, in <module>
    from rdkit.DataStructs import cDataStructs
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/conda/lib/python3.8/site-packages/rdkit/DataStructs/cDataStructs.so)
```

The issue appears to stem from the fact that the rdkit conda package is linked using relative paths to the conda installed shared library (in `conda/lib`), while the pytorch pip package is ultimately linked to the system libraries (in `/usr/lib`) due to the the default search order for libraries. So if the system libstdc++ version is older than the conda version, this error may be encountered.

The other complicating factor is that import order matters. So if pytorch is imported before rdkit (as done in `chemprop.data`), then python will load the older system library, after which rdkit will encounter the import error. However, if rdkit is imported first, python will load the newer conda library, after which pytorch will also load successfully.

This was discovered and debugged using Docker, but it should also apply to normal installs.

For anyone who is encountering this error, the easiest way to fix it is to add the `conda/lib` directory (exact location depends on where anaconda is installed) to `LD_LIBRARY_PATH`, e.g. `export LD_LIBRARY_PATH=/opt/conda/lib`. However, permanently adding the `conda/lib` directory to `LD_LIBRARY_PATH` is not recommended since it may also interfere with system functionality.

I think a potential long term solution would be to install pytorch using conda instead of pip.

**Comment by nbosc** [comment]
Same issue here.

**Comment by davidegraff** [comment]
this is not a problem any more with the current environment specification
