### ISSUE TITLE
Hyperopt Memory Error

### ISSUE THREAD

**Issue by nathanmlim** [chemprop/chemprop#130]
When running `chemprop_hyperopt`, I eventually run into this error
```
RuntimeError: CUDA out of memory. Tried to allocate 798.00 MiB (GPU 3; 11.93 GiB total capacity; 8.51 GiB already allocated; 555.50 MiB free; 10.89 GiB reserved in total by PyTorch)
```
then the whole process stops. Is there a way to get hyperopt to continue trying out the other parameters instead of killing the whole process?

**Comment by cjmcgill** [comment]
In terms of the cuda memory, if this is the machine you want to run on, then it does you no good to optimize above your available gpu memory. You may be better off figuring out which end of the search space is using too much memory and then reduce that space in `chemprop/hyperparameter_optimization.py`. I would supply a save_dir argument when you run so you can see what the last iteration it was working on before it fails. You may also want to reduce your batch size to get in under the limit.

The optimization steps are contained within the hyperopt `fmin` function and that doesn't have any built-in exception handling options, so anything we could do is likely to be messy. I think there's a potentially place where you could add a try/except yourself in the `objective` function in `chemprop/hyperparameter_optimization.py`, but it may not behave as expected. I tried this with a toy version of your problem but yours may act very differently.

You could try replacing lines 73-74
```
        # Cross validate
        mean_score, std_score = cross_validate(args=hyper_args, train_func=run_training)
```
With
```
        try:
            # Cross validate
            mean_score, std_score = cross_validate(args=hyper_args, train_func=run_training)
        except RuntimeError:
            mean_score = float('inf') if hyper_args.minimize_score else 0
            std_score = 0
```

**Comment by nathanmlim** [comment]
I was able to complete a run of hyperparameter optimization just by reducing the batchsize
