### ISSUE TITLE
Hyperparameter Optimization

### ISSUE THREAD

**Issue by nathanmlim** [chemprop/chemprop#134]
Is there a way to use the hyperparameter optimization code you have here to optimize some of the parameters for the sklearn RandomForest model? Particularly looking at trying various radius lengths for morgan fingerprints and the number of trees.

**Comment by hesther** [comment]
@nathanmlim, sorry for the very late response - I have not a lot of experience with the sklearn options in chemprop but think the code in chemprop/hyperparameter_optimization.py should be easily adaptable - I can try to write to it this weekend if you are still interested!

**Comment by kevingreenman** [comment]
We are closing all enhancement requests for chemprop v1.x, as we will not have time to implement these before the upcoming release of [chemprop v2.0](https://github.com/chemprop/chemprop/issues/517). If there is still interest in this enhancement, please open a new issue after the release of v2.0.
