### ISSUE TITLE
Pip installation doesn't include schema.sql for web app

### ISSUE THREAD

**Issue by mefortunato** [chemprop/chemprop#136]
When installing from pypi, it looks like `chemprop/web/app/schema.sql` does not get included in the install. This causes an error like the one below when running the web app.

```
FileNotFoundError: [Errno 2] No such file or directory: '<PYTHONPATH>/chemprop/web/app/schema.sql'
```

I think the "data" file can be included in `setup.py` https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html

**Comment by davidegraff** [comment]
We'll fix the web app one of these days in a separate repo. For now, it is unfortunately broken and not maintained
