### ISSUE TITLE
Error with gpu option

### ISSUE THREAD

**Issue by matany58** [chemprop/chemprop#141]
I run the predict.py and use the gpu option  (--gpu 1) but I received the error invalid choice: 1 (choose from)

Please how do you use the gpu option.

**Comment by cjmcgill** [comment]
That is what the error looks like when no cuda-capable gpus detected. Under normal operation that error would return a list of integer labels inside the parentheses. 

Do you know if you have a nvidia gpu that works for cuda? If you know that you should have a compatible gpu, there could be a driver issue causing it not to be recognized. 

You can check if pytorch recognizes a cuda enabled device with `torch.cuda.is_available()` in python.

**Comment by cjmcgill** [comment]
Closing this issue but please reopen if you have updates or follow ups that you would like to discuss.
