### ISSUE TITLE
Error with find_sim_mols.py

### ISSUE THREAD

**Issue by daverdude** [chemprop/chemprop#143]
Hey team,

I am receiving the following error type after executing the command below. I am pretty sure the SMILES used in the datasets I am using are able to be parsed by RDKit so I am not sure how to move forward here. I have updated conda base and rdkit, but neither has solved the issue.

(chemprop) [daviddelgadillo@localhost chemprop]$ python scripts/find_similar_mols.py --test_path data/broad_repurposing_library.csv --train_path data/expanded_external_library.csv --save_path pred/sim_mols/broad_repurposing_library_expanded_external_sim_mols.csv --distance_measure tanimoto
WARNING:root:No normalization for BCUT2D_MWHI
WARNING:root:No normalization for BCUT2D_MWLOW
WARNING:root:No normalization for BCUT2D_CHGHI
WARNING:root:No normalization for BCUT2D_CHGLO
WARNING:root:No normalization for BCUT2D_LOGPHI
WARNING:root:No normalization for BCUT2D_LOGPLOW
WARNING:root:No normalization for BCUT2D_MRHI
WARNING:root:No normalization for BCUT2D_MRLOW
Loading data
100%|█████████████████████████████████████| 6111/6111 [00:01<00:00, 4502.02it/s]
100%|█████████████████████████████████████| 2624/2624 [00:00<00:00, 4583.99it/s]
Computing tanimoto vectors
  0%|                                                  | 0/6111 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/daviddelgadillo/chemprop/scripts/find_similar_mols.py", line 196, in <module>
    save_similar_mols(
  File "/home/daviddelgadillo/chemprop/scripts/find_similar_mols.py", line 173, in save_similar_mols
    similar_mols = find_similar_mols_from_file(
  File "/home/daviddelgadillo/chemprop/scripts/find_similar_mols.py", line 140, in find_similar_mols_from_file
    return find_similar_mols(
  File "/home/daviddelgadillo/chemprop/scripts/find_similar_mols.py", line 72, in find_similar_mols
    test_fps = [Chem.RDKFingerprint(m.mol) for m in tqdm(test_data)]
  File "/home/daviddelgadillo/chemprop/scripts/find_similar_mols.py", line 72, in <listcomp>
    test_fps = [Chem.RDKFingerprint(m.mol) for m in tqdm(test_data)]
**Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.RDKFingerprint(list)
did not match C++ signature:
    RDKFingerprint(RDKit::ROMol mol, unsigned int minPath=1, unsigned int maxPath=7, unsigned int fpSize=2048, unsigned int nBitsPerHash=2, bool useHs=True, double tgtDensity=0.0, unsigned int minSize=128, bool branchedPaths=True, bool useBondOrder=True, boost::python::api::object atomInvariants=0, boost::python::api::object fromAtoms=0, boost::python::api::object atomBits=None, boost::python::api::object bitInfo=None)**

**Comment by hesther** [comment]
Recent changes (allowing multi-molecule input) have changed the data structure from a single molecule to a list of molecules, and it seems like we have overlooked a detail in the `find_similar_mols.py` script (this is why Python complains that it was given a list instead of a RDKit molecule). For a quick and dirty fix (assuming you are using single molecules), you can change line  72 in `find_similar_mols.py` to 
`test_fps = [Chem.RDKFingerprint(m.mol) for m[0] in tqdm(test_data)]`
to make your analysis work, but we will also work on a more professional fix.

**Comment by cjmcgill** [comment]
@daverdude we have had a couple of rounds of code change recently that affects smiles processing (that may have solved or may have caused the problem). Can you confirm that you are on the current master branch?

**Comment by fhvermei** [comment]
Should be fixed with Pull request #144.
There are no errors for 'embedding' or 'morgan'!
