### ISSUE TITLE
could not covert string to float

### ISSUE THREAD

**Issue by aminemosbah** [chemprop/chemprop#15]

**Comment by aminemosbah** [comment]
hi get error when trying to train the model
Fold 0
{'activation': 'ReLU',
 'atom_messages': False,
 'batch_size': 50,
 'bias': False,
 'checkpoint_dir': None,
 'checkpoint_path': None,
 'checkpoint_paths': None,
 'config_path': None,
 'crossval_index_dir': None,
 'crossval_index_file': None,
 'cuda': True,
 'data_path': 'Atbvsgarlic.csv',
 'dataset_type': 'classification',
 'depth': 3,
 'dropout': 0.0,
 'ensemble_size': 1,
 'epochs': 30,
 'features_generator': None,
 'features_only': False,
 'features_path': None,
 'features_scaling': True,
 'ffn_hidden_size': 300,
 'ffn_num_layers': 2,
 'final_lr': 0.0001,
 'folds_file': None,
 'gpu': None,
 'hidden_size': 300,
 'init_lr': 0.0001,
 'log_frequency': 10,
 'max_data_size': None,
 'max_lr': 0.001,
 'metric': 'auc',
 'minimize_score': False,
 'multiclass_num_classes': 3,
 'no_cache': False,
 'num_folds': 1,
 'num_lrs': 1,
 'quiet': False,
 'save_dir': 'tox21_checkpoints/fold_0',
 'save_smiles_splits': False,
 'seed': 0,
 'separate_test_features_path': None,
 'separate_test_path': None,
 'separate_val_features_path': None,
 'separate_val_path': None,
 'show_individual_scores': False,
 'split_sizes': [0.8, 0.1, 0.1],
 'split_type': 'random',
 'test': False,
 'test_fold_index': None,
 'undirected': False,
 'use_compound_names': False,
 'use_input_features': None,
 'val_fold_index': None,
 'warmup_epochs': 2.0}
Loading data
  0% 0/12 [00:00<?, ?it/s][19:50:15] SMILES Parse Error: syntax error while parsing: Ajoene
[19:50:15] SMILES Parse Error: Failed parsing SMILES 'Ajoene' for input: 'Ajoene'
Traceback (most recent call last):
  File "chemprop/train.py", line 11, in <module>
    cross_validate(args, logger)
  File "/content/chemprop/chemprop/train/cross_validate.py", line 29, in cross_validate
    model_scores = run_training(args, logger)
  File "/content/chemprop/chemprop/train/run_training.py", line 49, in run_training
    data = get_data(path=args.data_path, args=args, logger=logger)
  File "/content/chemprop/chemprop/data/utils.py", line 151, in get_data
    ) for i, line in tqdm(enumerate(lines), total=len(lines))
  File "/content/chemprop/chemprop/data/utils.py", line 151, in <listcomp>
    ) for i, line in tqdm(enumerate(lines), total=len(lines))
  File "/content/chemprop/chemprop/data/data.py", line 66, in __init__
    self.targets = [float(x) if x != '' else None for x in line[1:]]
  File "/content/chemprop/chemprop/data/data.py", line 66, in <listcomp>
    self.targets = [float(x) if x != '' else None for x in line[1:]]
ValueError: could not convert string to float: 'C=CCSSC=CCS(=O)CC=C'
  0% 0/12 [00:00<?, ?it/s]

**Comment by lhirschfeld** [comment]
I'm sorry you're running into this problem. Is it possible that the second (or later) column in your csv has smile strings? By default, the the train script expects the first column in the csv to have smile strings and all later columns to have numeric labels.

**Comment by aminemosbah** [comment]
thanks, awesome job lhirschfeld  is it possible to train the model on customized regressors (descriptors)
do we need to overwrite configuration scripts?

**Comment by lhirschfeld** [comment]
Happy to help. By custom regressors do you mean custom input features? If so, ChemProp does support them. You can find more information here: https://github.com/chemprop/chemprop#custom-features. Please let us know if you have any other issues!
