### ISSUE TITLE
Train and validate models using chemprop as a Python library

### ISSUE THREAD

**Issue by iwwwish** [chemprop/chemprop#155]
Thank you very much for contributing this repo to the community. I have been using the command line module to train/validate models that I use in the production later. Is there a way one could load data, train and validate models in Python using chemprop as a library? I am hoping to use it as one of the approaches in a pipeline to automate model building and deployment.

Thanks,
Vishal

**Comment by cjmcgill** [comment]
Hi @iwwwish , this is a way that you can use chemprop. To use the code this way, you would want to set your entry points at the level of functions that take (almost) only the processed arguments as inputs: `cross_validate` (for training), `make_predictions`, and `molecule_fingerprint`.

You would enter processed args that you generated through something like the below example, for the appropriate type of args for your purpose. When doing this, you would supply a list to the `parse_args` class function, including anything that you would enter as command line arguments ordinarily.

`train_args=TrainArgs().parse_args(['--data_path',data_path,'--config_path',train_config_path,'--dataset_type',dataset_type])`

This would allow you to have your models and predictions saved at specified paths as you would when using chemprop normally. These functions do have some returns, but it might not be exactly what you want for setting up a pipeline (thinking specifically of `cross_validate` which returns to you the test set rmse rather than individual predictions or errors).

**Comment by JasonYCHuang** [comment]
Hi @iwwwish 

This works for me. Please change the path to your model in arguments.

```python
import chemprop

smiles = [
    ['CC(C)C(C)(C)C'],
    ['Clc1ccc(c(Cl)c1Cl)c2c(Cl)cc(Cl)c(Cl)c2Cl'],
]

# Build arguments
arguments = [
    '--test_path', 'None',
    '--preds_path', 'None',
    '--checkpoint_paths', './checkpoints/PATH_TO_YOUR_MODEL.pt',
    '--no_cuda',
]

# Parse arguments
args = chemprop.args.PredictArgs().parse_args(arguments)

# Run predictions
preds = chemprop.train.make_predictions(args=args, smiles=smiles)
preds

```

**Comment by iwwwish** [comment]
Hi @cjmcgill, hi @JasonYCHuang,

Thank you for the suggestions. I could successfully train a model and make predictions. Though I would like to have the models within the code (to be used further in the pipeline), I think I can live with this for now.

```
from chemprop.args import TrainArgs, PredictArgs
from chemprop.train import cross_validate, run_training, make_predictions

# training arguments
train_args = [
    '--data_path', '../data/training.csv',
    '--dataset_type', 'classification',
    '--save_dir', '../models/',
    '--num_folds', '1',
]

# prediction arguments
test_args = [
    '--test_path', '../data/test.csv',
    '--preds_path', '../predictions/pred.csv',
    '--checkpoint_dir', '../models/',
    '--num_workers', '0',
]

# train model
mean_score, std_score = cross_validate(args=TrainArgs().parse_args(train_args), train_func=run_training)

# make predictions
preds = make_predictions(args=PredictArgs().parse_args(test_args))
```

Best,
Vishal

**Comment by cjmcgill** [comment]
Hi @iwwwish , glad this works for you. What is it further that you would like to be able to do in your pipeline?

If you want the model as an object in your code, you can use `load_checkpoint` from `chemprop.utils` to load in the model that you trained during your training step.

**Comment by iwwwish** [comment]
Hi @cjmcgill,

Thanks again for the hint. I am building a chemprop model within my pipeline in which jobs would be running on AWS batch. So, I thought it would be an extra effort to save the models and predictions to S3 and load them back to access them further in the script. But thinking twice, I felt it is a good idea to run it this way as I would have a persistent URL on S3 for the model files that I could use later in production environment if needed. Do you think it make sense?

Best,
Vishal

**Comment by cjmcgill** [comment]
@iwwwish , I don't have particular experience setting up that kind of pipeline and don't have advice for you on what best-practices might be. What you describe sounds reasonable though and I don't see a reason to think it wouldn't work.

Good luck! And please let us know if you have questions or problems or suggestions for features that would be useful for your situation.

**Comment by iwwwish** [comment]
@cjmcgill , thank you! for example, i would like `cross_validate` to return me the model(s) directly. i understand that one could load the trained model into the code using `load_checkpoint`, but i am not sure if i would have complete read/write flexibility on AWS S3 when my code executes on AWS Batch.

In my very first attempt, I could get chemprop work on Batch with the data stored on S3, but could not see the model and prediction files saved at the specified paths on S3. so if I have the model file i can write it as an S3 object using Python libraries like `boto3`. i hope i explained better this time.

**Comment by cjmcgill** [comment]
So you won't have read permissions to the models while the batch is running? Or is the pathing weird so when you reference a file location it ends up not being where you expect it to be?

As part of the training, there actually is a step where old models are loaded from checkpoint to evaluate performance on the test set. So I think that loading from a checkpoint would be possible. 

The inability to read scratch files would be a major problem for AWS I would think, so it is something that is probably possible somehow. AWS support people would probably be the right people to ask for issues reading scratch or for issues with pathing.

As far as changing cross_validate to have the model as output, that is not a change that would be possible. It would require a major change to the software. But more importantly: any solution of that type would actually require a load_checkpoint step so I think that the real thing we need to do here is figure out why you're having trouble loading from checkpoints.

If you have a particular error message that is being thrown that could help. 

Unrelated: the behavior of the number of workers on predictions is kind of weird. It might be worth trying it out without specifying workers to see if that's causing something weird.

**Comment by iwwwish** [comment]
@cjmcgill thanks for reopening the issue. I figured out that it was an issue related to permissions. I think I can deal with this on the AWS end. Regarding the number of workers for predictions, it worked fine on the AWS compute environment without explicitly specifying the number of workers. but it failed to work locally (i believe due to #115, which is why i had to specify `num_workers = 0` in my code). here's the error I got otherwise:

```
Traceback (most recent call last):
  File "chemprop_local.py", line 24, in <module>
    preds = make_predictions(args=PredictArgs().parse_args(test_args))
  File "/Users/siramshettyv2/anaconda3/envs/chemprop/lib/python3.8/site-packages/chemprop/utils.py", line 410, in wrap
    result = func(*args, **kwargs)
  File "/Users/siramshettyv2/anaconda3/envs/chemprop/lib/python3.8/site-packages/chemprop/train/make_predictions.py", line 107, in make_predictions
    model_preds = predict(
  File "/Users/siramshettyv2/anaconda3/envs/chemprop/lib/python3.8/site-packages/chemprop/train/predict.py", line 27, in predict
    for batch in tqdm(data_loader, disable=disable_progress_bar, leave=False):
  File "/Users/siramshettyv2/anaconda3/envs/chemprop/lib/python3.8/site-packages/tqdm/std.py", line 1176, in __iter__
    for obj in iterable:
  File "/Users/siramshettyv2/anaconda3/envs/chemprop/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/Users/siramshettyv2/anaconda3/envs/chemprop/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/Users/siramshettyv2/anaconda3/envs/chemprop/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "/Users/siramshettyv2/anaconda3/envs/chemprop/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 87015) exited unexpectedly
(chemprop) NCATS-2072374-M:scripts siramshettyv2$ /Users/siramshettyv2/anaconda3/envs/chemprop/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by cjmcgill** [comment]
Okay, @iwwwish it sounds like you're well on your way to a solution then. Let me know if you have other trouble.

**Comment by hesther** [comment]
Am closing this issue, since it seems to be solved. @iwwwish please feel free to write another issue/ reopen this one if you need further assistance.
