### ISSUE TITLE
predict.py TypeError

### ISSUE THREAD

**Issue by domgurvic** [chemprop/chemprop#16]
Hi, excellent model all together, amazing work. 

I get an error after I train (with no issues) the model and attempt to predict on a new set of smiles. 

I tried changing the model, the smiles for prediction, but i keep running into same issue, here is the full output:

python predict.py --test_path rep_drugs.csv --checkpoint_dir save --preds_path rep_preds.csv
Loading training args
Loading data
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5794/5794 [00:01<00:00, 5280.02it/s]
Validating SMILES
Test size = 5,794
Predicting with an ensemble of 2 models
  0%|                                                                                                                                                                                 | 0/2 [00:00<?, ?it/s]Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
  0%|                                                                                                                                                                               | 0/116 [00:00<?, ?it/s]
  0%|                                                                                                                                                                                 | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "predict.py", line 8, in <module>
    make_predictions(args)
  File "/home/user/Desktop/chemprop-master/chemprop/train/make_predictions.py", line 72, in make_predictions
    scaler=scaler
  File "/home/user/Desktop/chemprop-master/chemprop/train/predict.py", line 39, in predict
    batch_preds = model(batch, features_batch)
  File "/home/user/anaconda3/envs/chemprop/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/Desktop/chemprop-master/chemprop/models/model.py", line 88, in forward
    output = self.ffn(self.encoder(*input))
  File "/home/user/anaconda3/envs/chemprop/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/Desktop/chemprop-master/chemprop/models/mpn.py", line 187, in forward
    output = self.encoder.forward(batch, features_batch)
  File "/home/user/Desktop/chemprop-master/chemprop/models/mpn.py", line 73, in forward
    features_batch = torch.from_numpy(np.stack(features_batch)).float()
  File "<__array_function__ internals>", line 6, in stack
TypeError: dispatcher for __array_function__ did not return an iterable

Not sure what the issue is.

**Comment by siahuat0727** [comment]
I met the same error when I run training with `features_generator`.
The `predict.py`  seems didn't load `features_generator` automatically.
Try `python predict.py  --features_generator <some generator>  --...(some other args)`.

**Comment by domgurvic** [comment]
That solved it! 

Thank you for that. Just like you said, I needed to add same "--feature_generator" flag when predicting as I used in training.
