### ISSUE TITLE
why I can't download the Antibiotics checkpoints , I need help

### ISSUE THREAD

**Issue by su-chao** [chemprop/chemprop#161]
Hi,

I can't download the Antibiotics checkpoints provided here: http://chemprop.csail.mit.edu/checkpoints

I don't know why download the Antibiotics checkpoints always failed , 

if you can do it ,please send the zip to my email  hnnu_nc@163.com or 810275605@qq.com

Thanks! Thanks! Thanks!

**Comment by hesther** [comment]
I will email you in a few minutes, I have them on file!
