### ISSUE TITLE
Split_sizes keyword does not work if separate test file is given

### ISSUE THREAD

**Issue by hesther** [chemprop/chemprop#168]
I just noticed that the `--split_sizes` keyword does not work if a test file is given via `--separate_test_path` (the data given in `--data_path` is always split in a 80/20 ratio in this case). It seems like a bug to me, and I think that being able to specify the split ratios (with 0 test ratio) would be very useful in this case (or we should give a warning that it doesn't work, currently it does not throw an error, just uses the wrong split ratios). Any preferences?

**Comment by cjmcgill** [comment]
This also occurs when a separate Val path is provided. So we'll need to support each combo case. And I'm not sure how it interacts with --num_folds<>1.

**Comment by hesther** [comment]
I see .... I just tried having different folds with `--separate_test_path` and it produces different train/val splits (with 0.8/0.2 ratio) and then tests on the same test data (which I think is the correct way to do cross validation, see e.g. [sklearn](https://scikit-learn.org/stable/_images/grid_search_cross_validation.png)). However, this is not what default Chemprop does (without the separate test path), it produces independent splits (with different validation and test sets each) - is this intended?

**Comment by cjmcgill** [comment]
I don't know. It doesn't seem like something that would be intentional.
