### ISSUE TITLE
Add check_reproducbility to TrainArgs

### ISSUE THREAD

**Issue by marcosfelt** [chemprop/chemprop#176]
In some jupyter environments Tap's check_reproducibility argument causes problems because it interferes with other git processes. It would be nice to be able selectively turn that off. 

Happy to submit a PR for this.

**Comment by hesther** [comment]
Hi @marcosfelt, thanks for raising this issue! Could you describe in more detail what the problem exactly is and under which circumstances you encounter it, so we can take a look into whether it might be worth introducing an additional argument, or whether it might be a a very isolated problem that would better be addressed with a custom, local fix? I couldn't really reproduce it. Also, what would your ideas be to fix it (feel free to just describe in a few words)? Thanks!

**Comment by marcosfelt** [comment]
@hesther Thanks for the response. I'm actually a bit busy right now and can't get back on the system where I saw the error. I'll close the issue for now and reopen when I have some time.
