### ISSUE TITLE
ESOL data

### ISSUE THREAD

**Issue by songyuanbing6** [chemprop/chemprop#179]
Thank you very much for this excellent work！Congratulations！

I don't find the esol.csv in the data.tar.gz. Can you provide the esol.csv ?

Thank you for your help.

**Comment by hesther** [comment]
Dear @songyuanbing6 , thank you very much for your kind words. The solubility dataset is named `delaney.csv` (not `esol.csv`, and should be in `data.tar.gz`). Happy computing!

**Comment by songyuanbing6** [comment]
ok.I have found. Thank you very much.
