### ISSUE TITLE
environment.yml installs cpu instead of gpu version of pytorch and torchvision

### ISSUE THREAD

**Issue by aksub99** [chemprop/chemprop#183]
Hi,
Thanks for the great framework!

Wanted to bring to your notice that the installation from the `environment.yml` file seems to install `cpu` versions of `pytorch` and `torchvision` instead of `gpu` ones. I found that this is because it installs `pytorch` and `torchvision`  from the `conda-forge` channel instead of the `pytorch` channel. I managed to resolve this issue by installing `pytorch` and `torchvision` separately from the `pytorch` channel. 

I was also able to reproduce this issue on the docker installation since that makes use of the same yml file.

**Comment by mliu49** [comment]
Thanks for reporting this! I think the available packages changed at some point which led to the conda-forge version getting pulled instead of the pytorch version. We'll update the environment file to make sure the correct package is installed.

**Comment by aksub99** [comment]
Great! Thanks @mliu49 !

**Comment by davidegraff** [comment]
@mliu49 was this fixed / can we close?
