### ISSUE TITLE
graph convolution

### ISSUE THREAD

**Issue by songyuanbing6** [chemprop/chemprop#184]
Hi！
Thanks for the great framework!
1.Where is graph convolution represented in the code ? 
2.Which class of graph convolution is used ?

**Comment by hesther** [comment]
Chemprop is a directed message-passing neural network, which is a type of graph convolutional neural net. You can read more in the corresponding article, especially the SI [here](https://pubs.acs.org/doi/abs/10.1021/acs.jcim.9b00237)

The code concerning the message passing steps can be found in chemprop/models/mpn.py

**Comment by songyuanbing6** [comment]
Does Graph convolutional network refer to the whole framework, not just a part of the framework in the article？

**Comment by hesther** [comment]
Chemprop has two parts:
1) MPNEncoder: directed Message Passing Neural Network (this is one form of graph convolution). It takes the molecular graph as input, with some initial atom and bond features, and iteratively updates these representations to arrive at new atom features. They are then summed or averaged (depending on your hyperparameters) to a molecular representation (=embedding of the molecular graph)
2) FFN: a vanilla feed-forward neural net, which takes the embedding of the molecular graph and relates it to your target properties. This is not a graph convolution. 

Both MPNEncoder and FFN are trained at the same time. You can think of it as similar to regular CNNs for images, they also have a convolutional part (with filtering and pooling steps), and after some iterations pass the flattened embeddings to a standard feed-forward neural net.

Does this answer your questions? (I am not sure whether I got it completely)

**Comment by songyuanbing6** [comment]
Thank you very much for your reply. 
 Your reply is very helpful to me. 
Congratulations on your excellent framework at the same time.

**Comment by songyuanbing6** [comment]
I have another question. 
Is graph convolution the same thing as graph convolutional neural network？
Is it graph convolutional neural network abbreviated graph convolution？（a logogram？）

**Comment by hesther** [comment]
Some people use it as being the same. Technically, graph convolutional neural networks (or also graph convolutional networks, or GCNNs) refer to your whole model which usually consists of a several layers of graph convolutions (each filter which produces new atom/edge or bond/vertex information based on the structure of the graph).

**Comment by songyuanbing6** [comment]
ok！
Thank you very much！
