### ISSUE TITLE
Interpreting: all smiles are failed for parsing

### ISSUE THREAD

**Issue by chupvl** [chemprop/chemprop#19]
https://github.com/chemprop/chemprop#Interpreting 
SMILES on the page cannot be parsed. all of them.

**Comment by swansonk14** [comment]
Hi @chupvl, thanks for pointing that out! It turns out that was a markdown issue since markdown was interpreting some brackets as markdown symbols and was hiding them, thereby making the shown SMILES invalid. We've now fixed it so the SMILES on the README should be correct.

**Comment by chupvl** [comment]
just to be clear: they failed from parsing for my model, so it's not linked with the README file. Otherwise, can you please provide example of the visualization of the fragment?
