### ISSUE TITLE
How to add Rdkit Features exactly?

### ISSUE THREAD

**Issue by Jiang-Lu-CAS** [chemprop/chemprop#20]
If I want to add DFs Rdkit features in my calculation. Should we add "--features_generator rdkit_2d_normalized --no_features_scaling" in every steps, such as Hyperparameter Optimization, train, predict, Interpreting? or I just need add them when train model.
Thank you~

**Comment by qiangsir** [comment]
Hi
I can't understand the specific format of this training file. Could you give me an example file?

**Comment by swansonk14** [comment]
Hi @Jiang-Lu-CAS, thank you for your question! You do need to add them at every step. The feature computation is done outside of the model itself, so even when a trained model is loaded (as happens when you use predict.py) you still need to specify the features.
