### ISSUE TITLE
Using customized metrics as loss functions

### ISSUE THREAD

**Issue by vigneshwari16** [chemprop/chemprop#201]
It would be really helpful, if the users have an option to specify some other metrics, as a loss function. Atleast, I would be interested in using Mathews correlation coefficient or F1 score as a loss function for classification models. Is there a possibility to implement this?

**Comment by cjmcgill** [comment]
Hi @vigneshwari16, this may become a part of a feature we are currently working on. I'll update you here when there is some progress to report.
