### ISSUE TITLE
Small bug with resume_experiment model

### ISSUE THREAD

**Issue by hesther** [chemprop/chemprop#205]
The new argument `--resume_experiment` only checks for existing folds, not ensembles within the fold. For example, if the following models are already present: 
```
fold_0/model_0
fold_1/model_0
fold_2/model_0
```
`--resume_experiment --num_folds 4` will add `fold_3/model_0`, but `--resume_experiment --num_folds 3 --ensemble_size 3` will not do any training at all, because folds 0-2 are already present and ensembles are not checked. This is only a minor bug, but reporting so we don't forget to fix it in the future.

**Comment by kevingreenman** [comment]
We are closing all bug reports that we don't have time to fix before the release of v1.7 this month, and unfortunately this is one of them. We will soon release [Chemprop v2.0](https://github.com/chemprop/chemprop/issues/517) and do not plan to maintain/support v1.x any longer. If anyone has time to open a PR that fixes this bug before the end of January 2024, we will review it and consider including it in v1.7.
