### ISSUE TITLE
Extra Atom and Bond Descriptors

### ISSUE THREAD

**Issue by cjmcgill** [chemprop/chemprop#213]
There seems to be a bug when extra atom descriptors/features and extra bond descriptors are used in the same model. Appears that they may try to use the same scaler object and thus have the wrong size of the scaler vectors for mean and std for bond descriptors (as it was set for the atoms). Error goes away when `--no_atom_descriptor_scaling` and `--no_bond_features_scaling` are selected.

```
scaler.py line 52, in transform
    transformed_with_nan = (X - self.means) / self.stds
ValueError: operands could not be broadcast together with shapes (38,2) (4,) 
```

**Comment by yunsiechung** [comment]
This bug can be fixed by adding two lines to `chemprop/train/run_training.py` as shown in this commit dff7f528dc0a06ab9253a081b04ca838afeb4665.

I can make a pull request for this!

**Comment by cjmcgill** [comment]
@yunsiechung that would be marvelous!

**Comment by hesther** [comment]
Am closing this since we fixed it :)
