### ISSUE TITLE
Model interpretation in Python script takes several minutes

### ISSUE THREAD

**Issue by iwwwish** [chemprop/chemprop#214]
Hello!

I am trying to implement model interpretation within my ML pipeline. The interpretation instructions provided in the README work perfectly fine when I tried them on command line. Then, I tried to include this into my code by writing a small function. The method works but it takes several minutes to provide an output unlike the command line which returns the result immediately. I tried this with just one compound: `Clc1ccc(c(Cl)c1Cl)c2c(Cl)cc(Cl)c(Cl)c2Cl`

I would really appreciate your help in fixing this. Code and output below.

Best,
Vishal

Code:

```
import tempfile
import time
import pandas as pd
import sys
sys.path.insert(0, './predictors/chemprop')
from chemprop.args import InterpretArgs
from chemprop.interpret import interpret

def get_interpretation(kekule_smiles_df):

    start = time.time()
    intrprt_df = pd.DataFrame()

    with tempfile.NamedTemporaryFile(delete=True) as temp:

        kekule_smiles_df.to_csv(temp.name + '.csv', index=None)

        # interpretation arguments
        intrprt_args = [
        '--data_path', temp.name + '.csv',
        '--checkpoint_path', './models/pampa/gcnn_model.pt',
        '--property_id', '1',
        ]

        # slightly modified the interpret method to return a dataframe for further use
        intrprt_df = interpret(args=InterpretArgs().parse_args(intrprt_args))
        temp.close()
    end = time.time()
    print(f'{end - start} seconds to interpret {kekule_smiles_df.shape[0]} molecules')
    return intrprt_df
```

Output:

```
Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
smiles,score,rationale,rationale_score
ClC1=C(Cl)C(Cl)=C(C2=C(Cl)C(Cl)=C(Cl)C=C2Cl)C=C1,0.981,Clc1c[cH:1]c(Cl)[cH:1]c1[CH3:1],1.000
1469.1523442268372 seconds to interpret 1 molecules
```

**Comment by hesther** [comment]
Just to clarify: On the command line it doesn't take that long? That is very odd...

**Comment by iwwwish** [comment]
Hello @hesther 

Yes, it doesn't take that long on command line which I too think is odd. Keeping this aside, when a test set with hundreds of compounds is passed, even the command line version takes a lot of time to finish interpret all of them. I guess that's because the MCTS algorithm takes longer time to process larger molecules. But at least it keeps printing the interpretation for each molecule as it is processed.

Thanks in advance for looking into it.

Best,
Vishal

**Comment by iwwwish** [comment]
Thank you @hesther. I am not sure I'll be able to do this myself completely. But if I were to get around it, I will definitely open a PR.

**Comment by kevingreenman** [comment]
We are closing all enhancement requests for chemprop v1.x, as we will not have time to implement these before the upcoming release of [chemprop v2.0](https://github.com/chemprop/chemprop/issues/517). If there is still interest in this enhancement, please open a new issue after the release of v2.0.

Note: we do not currently plan to implement the interpret function in v2.
