### ISSUE TITLE
Multi-target Multi-fold 1-ensemble

### ISSUE THREAD

**Issue by cjmcgill** [chemprop/chemprop#219]
It looks like there might be an error when training a multi-target regression model with multiple folds but only 1 ensemble.

Creating this error for me to look back at later.

**Comment by kevingreenman** [comment]
We are closing all bug reports that we don't have time to fix before the release of v1.7 this month, and unfortunately this is one of them. We will soon release [Chemprop v2.0](https://github.com/chemprop/chemprop/issues/517) and do not plan to maintain/support v1.x any longer. If anyone has time to open a PR that fixes this bug before the end of January 2024, we will review it and consider including it in v1.7.
