### ISSUE TITLE
Conda install procedure might result in wrongly linked dynamic library?

### ISSUE THREAD

**Issue by jasperhyp** [chemprop/chemprop#228]
Please refer to [this post](https://github.com/rdkit/rdkit/discussions/4758) in RDkit for details.

Briefly, I followed the conda install instructions (`Install from PyPI`) in the `README.md` file, but the dynamic library `libstdc++.so.6` linked to RDkit is wrongly set up to the system one rather than the one in the conda environment.  I restarted a new conda env following the same procedure but the same issue continues to happen.  Not sure if anything in the install procedure might have resulted in this.  I can now work it around but I hope I can set the conda env up correctly.  Would appreciate your advice!

**Comment by mliu49** [comment]
HI @jasperhyp, this is a known issue which may occur in some systems. Sorry we haven't gotten around to updating with a permanent solution. You can find some additional details about the error in issue #129.

Another potential solution would be to install all of the dependencies via conda using the existing environment.yml file:
```bash
conda env create -f environment.yml
conda activate chemprop
pip install chemprop
```

This does require downloading the environment.yml file or cloning the entire repo, which is not ideal.

**Comment by jasperhyp** [comment]
> HI @jasperhyp, this is a known issue which may occur in some systems. Sorry we haven't gotten around to updating with a permanent solution. You can find some additional details about the error in issue #129.
> 
> Another potential solution would be to install all of the dependencies via conda using the existing environment.yml file:
> 
> ```shell
> conda env create -f environment.yml
> conda activate chemprop
> pip install chemprop
> ```
> 
> This does require downloading the environment.yml file or cloning the entire repo, which is not ideal.

Thank you Max.  I would stick to the workaround `export LD_LIBRARY_PATH=/opt/conda/envs/chemprop/lib:$LD_LIBRARY_PATH` suggested by the RDkit maintainer in this case.
