### ISSUE TITLE
Multi-task learning about both regression task and classification task

### ISSUE THREAD

**Issue by SejeongPark8354** [chemprop/chemprop#237]
First of all, thank you for your wonderful work regarding molecule property prediction. 
I have a question about multi-task learning using chemprop.
Can I run multi-task learning about both regression task and classification task simultaneously using chemprop?

**Comment by cjmcgill** [comment]
Hi, I'm sorry but we don't have a configuration for doing this. Multi-task jobs need to be all the same dataset type (regression, classification, multiclass, spectra). This is for a few different reasons: to make the calculations more efficient, to make the gradients from the tasks more likely to be of similar magnitude, to make the data pre- and post-processing uniform, to have a way to evaluate the validation set into one topline score, etc. So unfortunately, this is something that crosses a lot of different parts of the code and wouldn't be easy to create a development version that allowed for multiple types.

**Comment by SejeongPark8354** [comment]
Thank you for your fast response and detailed explanation. 
I understand what you said and agree with you. 
Thank you again.
