### ISSUE TITLE
[FEATURE]: pre-commits

### ISSUE THREAD

**Issue by davidegraff** [chemprop/chemprop#248]
**Is your feature request related to a problem? Please describe.**
We should add pre-commit checks to enforce a consistent code style and lint automatically

**Use-cases/examples of this new feature**
Adding a new commit

**Discussion**
Linting with flake8 is a quick pre-commit that can catch fatal errors before they are even pushed. These are currently caught using the action we have right now, but for everyone's sake, they should never even be allowed to be pushed (unless there's a critical reason.) We can also use pre-commits to enforce a single code style on the entire repo. I format all my code with: `black -l 100 --skip-magic-trailing-comma` and I like the look of it, but we can choose other code formatters too. This is good for a repository with many contributors because it can be jarring to move from one source file to another as a reader when the style changes abruptly.

**Comment by mliu49** [comment]
+1 on formatting with black - I'm currently in the process of implementing that for ASKCOS, though with all default settings.

**Comment by davidegraff** [comment]
👍  I resisted for a while but then found myself just manually formatting to the black style

**Comment by muammar** [comment]
black is the way to go. I can submit a PR with that if you want to.

**Comment by davidegraff** [comment]
think we've actually decided against formal `pre-commit` usage but will gradually move all code over to `black` formatting
