### ISSUE TITLE
[FEATURE]: Run molecules through feature generators in batches rather than as single molecules

### ISSUE THREAD

**Issue by colinrsmall** [chemprop/chemprop#250]
**Is your feature request related to a problem? Please describe.**
When loaded data is run through feature generators, datapoints are passed as single molecules to each feature generator rather than in batches. This can dramatically slow down feature generation for generators that rely on pre-computation or loading that is independent of the molecule passed to the generator. For example, if we wish to use an external ML model that is saved to the disk as a feature generator, the model must be read and loaded individually for every single molecule in the dataset.

**Discussion**
This might drastically change how molecules and their feature generators are used. Perhaps depending on user set flags (I can imagine use cases where generators should be run per-molecule rather than per-batch), an easy fix for this is to run a batch of molecules through the generator and save them to the existing features attribute in MoleculeDatapoint? Maybe it's simple to add a flag like "--precompute_features" in which case all smiles are run through provided generators in chemprop/data/utils.get_data()?

**Comment by davidegraff** [comment]
Could you point me to roughly the spot in the codebase where this change would occur?

**Comment by colinrsmall** [comment]
Sure. The main changes would likely be in chemprop/features_generator.py and the get_data() function in chemprop/data/utils.

If you look at the [get_data()](https://github.com/chemprop/chemprop/blob/ac6bc9f52fbde17789fd844d7f1244e558150f01/chemprop/data/utils.py#L223) function in chemprop/data/utils, you will see that features for molecules in a dataset are loaded in two ways. 

1. The user supplies paths to a files containing feature data. These files are read, and the features associated with them are [appended to a list](https://github.com/chemprop/chemprop/blob/ac6bc9f52fbde17789fd844d7f1244e558150f01/chemprop/data/utils.py#L294), the index of which corresponds to the index of the molecule the features are associated with. Later, during construction of the MoleculeDataset, [each molecule is constructed as a MoleculeDatapoint with their associated features in the list](https://github.com/chemprop/chemprop/blob/ac6bc9f52fbde17789fd844d7f1244e558150f01/chemprop/data/utils.py#L410). These features are accessed later during training, prediction, etc.

2. The user supplies a list of generators to use instead of passing files with feature data pre-computed. This list is [passed individually](https://github.com/chemprop/chemprop/blob/ac6bc9f52fbde17789fd844d7f1244e558150f01/chemprop/data/utils.py#L409) to each MoleculeDatapoint constructed in the MoleculeData. In the constructor for MoleculeDatapoint, the Molecule object for that datapoint is passed to each provided generator, and the output from the generators are appended to the list of features for that datapoint. Thus, each provided generator function is called once per molecule in the data which can introduce unnecessary runtime as described in the original issue.

In get_data(), I can imagine checking for a flag (like "--precompute_features", etc.), running the entire list of molecules through a single call of each provided generator, and saving the generated features to a features list that works in the same way that the features list works when paths to feature files are provided.

This will require changing [the generator functions in chemprop/features/features_generators.py](https://github.com/chemprop/chemprop/blob/ac6bc9f52fbde17789fd844d7f1244e558150f01/chemprop/features/features_generators.py) since each generator is setup to only take in a single molecule. They could be changed to take in a Union[Molecule, list[Molecule]] or something along those lines.

<details>
  <summary>Here's a use case for a custom feature generator I'm using in one of my own models.</summary>
  
Here's my generator.
  ```
@register_features_generator('antibiotic_target')
def custom_features_generator(mol: Molecule) -> np.ndarray:
    # If you want to use the SMILES string
    smiles = Chem.MolToSmiles(mol, isomericSmiles=True) if type(mol) != str else mol
    
    arguments = [
        '--test_path', '/dev/null',
        '--preds_path', '/dev/null',
        '--checkpoint_dir', "antibiotic_target_predictor",
        '--features_generator', 'morgan'
    ]

    args = chemprop.args.PredictArgs().parse_args(arguments)
    preds = np.array(chemprop.train.make_predictions(args=args, smiles=[[smiles]]))[0]

    return preds
  ```

 Because each call to a generator only passes a single molecule, the chemprop backend for loading, running, and saving my antibiotic_target_predictor model is run separately for every single molecule in the data. If instead the generators allow the passing of lists of molecules as input, I could very easily call chemprop.train.make_predictions for my antibiotic_target_predictor and pass in the list of smiles in the data.
</details>

Hope that all makes sense.
