### ISSUE TITLE
Chemprop pretrained models unavailable

### ISSUE THREAD

**Issue by dor132** [chemprop/chemprop#255]
Hello,
I am trying to train a model using transfer learning.
Seems like chemprop's website is down and I can't reach your provided pretrained models at this [link](https://chemprop.readthedocs.io/en/latest/chemprop.csail.mit.edu).

Is there another place I can reach your pretrained models?

Thank you in advance,
Dor.

**Comment by cjmcgill** [comment]
The website does appear to be down and we are looking into it. Please pardon the interruption while we get the models hosted again.

**Comment by dor132** [comment]
Hi, thanks for your reply.
Is this going to be fixed soon?

**Comment by cjmcgill** [comment]
Still working on it. There's some complications I wasn't expecting. I hope it doesn't take too much longer but it's hard to be sure at this point.

**Comment by dor132** [comment]
Okay, thank you! 😄

**Comment by cjmcgill** [comment]
@dor132 the website is back up! Thanks for making us aware of the issue.

**Comment by dor132** [comment]
Hi, thank you!
However the link I provided is still not found (Maze Found), is this okay and the page does not exist anymore?

**Comment by cjmcgill** [comment]
I’m not totally sure what the link you provided was supposed to point to. However this below link goes to the chemprop website, where you can download checkpoints for antibiotics, sars, and COVID models. Let me know if this is what you’re looking for or if you have something else in mind. 

http://chemprop.csail.mit.edu/

**Comment by dor132** [comment]
Hi, it is what I need. However downloading Antibiotics.zip fails because the file is incomplete for some reason...

**Comment by cjmcgill** [comment]
We’ve run into that problem specifically before. Not sure why some people can download from there and some can’t. I, like you, can’t fully download it there. However there is a smaller link on that page at the bottom of the block of text where you can download equivalent files from google drive instead.

**Comment by dor132** [comment]
It does work.
Thank you very much!

**Comment by cjmcgill** [comment]
Sorry about the hassle!
