### ISSUE TITLE
[QUESTION]: problems about uncertainty fork

### ISSUE THREAD

**Issue by lglglang** [chemprop/chemprop#263]
**What are you trying to do?**
Great thanks for your work!
I am a freshman about ML, and trying to install the chemprop with uncertainty: https://github.com/gscalia/chemprop/tree/uncertainty, use it to build some models.

The chemprop have been installed by source in this web(not the Scalia's work, for I have seen you have update the environment.yml file to get the dependencies), but I can not make it when trying to train and predict with the code about generating uncertainty.  

The error is : ''chemprop_train: error: unrecognized arguments: --aleatoric'' and also when train the model with the additional flag` --epistemic mc_dropout`

I use the wrong code or my env just can not work the uncertainty problem?

**Screenshots**
![image](https://user-images.githubusercontent.com/102843926/161365369-25939e2d-5ac7-46d6-9825-fe786e6dc9d9.png)
![image](https://user-images.githubusercontent.com/102843926/161365379-ae0f6fdd-4c50-41db-af67-0965b430d310.png)

Thanks for your reading!

**Comment by davidegraff** [comment]
it looks like you’re trying to run code from the fork on the current main branch. That  won’t work because we haven’t merged the commits from there. Your best bet is to try and fork the current main branch and then merge the commutes in the uncertainty fork before running your code again. Of course, that’s easier said than done because that fork is over two years old at this point

**Comment by lglglang** [comment]
> it looks like you’re trying to run code from the fork on the current main branch. That won’t work because we haven’t merged the commits from there. Your best bet is to try and fork the current main branch and then merge the commutes in the uncertainty fork before running your code again. Of course, that’s easier said than done because that fork is over two years old at this point

Ok, I will have a try. Thank you.
