### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by rchae01** [chemprop/chemprop#264]
**Describe the bug**
I get an error "AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'" when trying to run hyperparameter optimization. I think other Bug reports have mentioned this before and the merge "AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'" #245 have already fixed this issue, but even when I update chemprop to the latest version the issue still persists. I also tried to install chemprop from source but unfortunately wasn't able to do so successfully. I was wondering if the version of chemprop installed with Pypi doesn't have the newest edits yet and if so when it would be updated. Any guidance would be greatly appreciated!

**Example(s)**

Error message:
C:\Users\LangerLab641>chemprop_hyperopt --data_path C:\Users\LangerLab641\Documents\Rachel\fda+65k+icb_chemprop.csv --dataset_type classification --target_columns ’t = 1.5’ --num_iters 10 --config_save_path C:\Users\LangerLab641\Documents\Rachel\config.json --hyperopt_checkpoint_dir C:\Users\LangerLab641\Documents\Rachel
WARNING:root:No normalization for BCUT2D_MWHI
WARNING:root:No normalization for BCUT2D_MWLOW
WARNING:root:No normalization for BCUT2D_CHGHI
WARNING:root:No normalization for BCUT2D_CHGLO
WARNING:root:No normalization for BCUT2D_LOGPHI
WARNING:root:No normalization for BCUT2D_LOGPLOW
WARNING:root:No normalization for BCUT2D_MRHI
WARNING:root:No normalization for BCUT2D_MRLOW
No manual trials loaded as part of hyperparameter search
Initiating trial with seed 6
Loaded 0 previous trials
Parameters assigned with random search, 10 random trials remaining
  0%|                                                                            | 0/1 [00:00<?, ?trial/s, best loss=?]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\chemprop\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\chemprop\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\chemprop\Scripts\chemprop_hyperopt.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\chemprop\lib\site-packages\chemprop\hyperparameter_optimization.py", line 164, in chemprop_hyperopt
    hyperopt(args=HyperoptArgs().parse_args())
  File "C:\ProgramData\Anaconda3\envs\chemprop\lib\site-packages\chemprop\utils.py", line 574, in wrap
    result = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\chemprop\lib\site-packages\chemprop\hyperparameter_optimization.py", line 129, in hyperopt
    fmin(
  File "C:\ProgramData\Anaconda3\envs\chemprop\lib\site-packages\hyperopt\fmin.py", line 540, in fmin
    return trials.fmin(
  File "C:\ProgramData\Anaconda3\envs\chemprop\lib\site-packages\hyperopt\base.py", line 671, in fmin
    return fmin(
  File "C:\ProgramData\Anaconda3\envs\chemprop\lib\site-packages\hyperopt\fmin.py", line 586, in fmin
    rval.exhaust()
  File "C:\ProgramData\Anaconda3\envs\chemprop\lib\site-packages\hyperopt\fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "C:\ProgramData\Anaconda3\envs\chemprop\lib\site-packages\hyperopt\fmin.py", line 279, in run
    **new_ids, self.domain, trials, self.rstate.integers(2 ** 31 - 1)
AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'**
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\chemprop\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\LANGER~1\\AppData\\Local\\Temp\\tmpkee6wos6\\quiet.log'

**Expected behavior**
I expected the hyperparameter optimization to start running.

**Environment**
- python version 3.8
- 
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
Babel                         2.9.1
certifi                       2021.10.8
charset-normalizer            2.0.12
chemprop                      1.4.1
click                         8.1.2
cloudpickle                   2.0.0
colorama                      0.4.4
cycler                        0.11.0
descriptastorus               2.3.0.6
docutils                      0.17.1
Flask                         2.1.1
fonttools                     4.31.2
future                        0.18.2
greenlet                      1.1.2
hyperopt                      0.2.7
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.3
itsdangerous                  2.1.2
Jinja2                        3.1.1
joblib                        1.1.0
kiwisolver                    1.4.2
MarkupSafe                    2.1.1
matplotlib                    3.5.1
munkres                       1.1.4
mypy-extensions               0.4.3
networkx                      2.7.1
numpy                         1.22.3
packaging                     21.3
pandas                        1.4.2
pandas-flavor                 0.2.0
Pillow                        9.1.0
pip                           21.2.2
protobuf                      3.20.0
py4j                          0.10.9.5
pycairo                       1.21.0
Pygments                      2.11.2
pyparsing                     3.0.7
python-dateutil               2.8.2
pytz                          2022.1
reportlab                     3.5.68
requests                      2.27.1
scikit-learn                  1.0.2
scipy                         1.8.0
setuptools                    58.0.4
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        4.5.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    1.4.34
tensorboardX                  2.5
threadpoolctl                 3.1.0
torch                         1.11.0
tqdm                          4.64.0
typed-argument-parser         1.7.2
typing_extensions             4.1.1
typing-inspect                0.7.1
unicodedata2                  14.0.0
urllib3                       1.26.9
Werkzeug                      2.1.1
wheel                         0.37.1
wincertstore                  0.2
xarray                        2022.3.0
zipp                          3.8.0

- OS: Windows

**Checklist**
- [v] all dependencies are satisifed: `conda list` shows the packages listed in the `README`
- [v] the unit tests are working: `pytest -v` reports no errors

**Additional context**

**Comment by shihchengli** [comment]
I think the 1.4.1 version doesn't include this PR. You can solve this issue by changing the version of hyperopt to 0.2.5 (pip install hyperopt==0.2.5).

**Comment by cjmcgill** [comment]
The upload to pypi of version 1.4.2 will likely happen later this month.
