### ISSUE TITLE
[QUESTION]: Hello, how do I get the ROC_AUC scores of the training sets? although it is expensive, but I need it 

### ISSUE THREAD

**Issue by su-chao** [chemprop/chemprop#268]
**What are you trying to do?**
Hello, how do I get the ROC_AUC scores of the training sets? although it is expensive, but I need it 

**Previous attempts**
I can get test or val scores through the model, but how to get train scores  ?

**Comment by hesther** [comment]
You could save your data splits (if you haven’t done so already) and your model using `—save_splits —save_dir <your_directory>` and then use the prediction function of chemprop using the saved training set for `—test_path`

**Comment by su-chao** [comment]
> You could save your data splits (if you haven’t done so already) and your model using `—save_splits —save_dir <your_directory>` and then use the prediction function of chemprop using the saved training set for `—test_path`

thanks ! --save_smiles_splits  is right

**Comment by hesther** [comment]
Oops (was texting from my phone), you are right about the keyword, thanks for correcting! Let me know whether your issue was solved, so I can close it.

**Comment by cjmcgill** [comment]
I believe this issue is resolved. If not please feel free to reopen.
