### ISSUE TITLE
Install Chemprop1.5.0

### ISSUE THREAD

**Issue by nedaojaghlou** [chemprop/chemprop#272]
I want to try loss_functio: Bounded_mse and this loss function is not working with chemprop1.4. I need to install Chemprop 1.5
I tried to clone the last version from the git but it looks like it's still version 1.4. Can you please let me know how can I access the latest version? Thanks!

**Comment by davidegraff** [comment]
1.5 should be coming in the next few days. We're wrapping up a few PRs and once that's done you should be good to go.

**Comment by cjmcgill** [comment]
Even though the version label said 1.4.1, the loss functions should have been included in the master when you installed, unless you installed from the tagged commit specifically.

Regardless, v1.5.0 has just been tagged so any new install you do will include it.
