### ISSUE TITLE
Tried unsuccessfully to use chemprop to interpret the results of a 4-class classification model I trained.

### ISSUE THREAD

**Issue by greenmossball** [chemprop/chemprop#275]
**What are you trying to do?**
I'm trying to use chemprop to interpret the results of a 4-class classification model I trained.
**Previous attempts**
Looking at your code and error message output I'm guessing that It is meant to interpret a single scalar values, not discrete classes.

**Comment by cjmcgill** [comment]
Hi @greenmossball. If I'm understanding correctly, you mean you have a task that has four mutually exclusive classes? You would use '--dataset_type multiclass --num_classes 4' as part of your input arguments. And in your data file with targets, you would want to assign each an integer of 0/1/2/3 depending on which class it's in. 

If I've misunderstood and you actually have four separate binary classes, '--dataset_type classification' and then have four columns of targets with 0/1 classes.

**Comment by greenmossball** [comment]
Thank you for your prompt reply. When I train I do have to use those arguments but when I interpret (thru chemprop_interpret) it does not recognize the arguments.

**Comment by cjmcgill** [comment]
Oh I'm sorry, I fully misunderstood you, I thought you were just training. Let me see if I can find a good answer for you.

**Comment by cjmcgill** [comment]
Closing because I think this is resolved. However if you have followup questions please reopen this issue.
