### ISSUE TITLE
[QUESTION]: Pretrained model object

### ISSUE THREAD

**Issue by devpunjabi** [chemprop/chemprop#277]
Can you provide an example as to how to use a pretrained model object with Pytorch ? 
(To attached new layers to the pretrained model and train newly attached layers)

**Comment by devpunjabi** [comment]
>

**Comment by devpunjabi** [comment]
Sorry for closing by mistake. 
I asked this question because it is not as straight forward to load state dict with a chemprop saved model. As the model needs MoleculeModel() object and this makes it complicated

**Comment by davidegraff** [comment]
the `MoleculeModel` class inherits from `nn.Module` so it supports saving/loading `state_dicts` like my example above

**Comment by davidegraff** [comment]
I'm not sure what you're trying to accomplish in that code snippet above:
- there's no detailed stack trace, so I don't know **where** the error is coming from
- it's not clear what `path_graph` represents. It's likely the result of `torch.save(f, nn.Module)`, but I don't know what the specific call that created it is. As a result, I have no idea what the structure/type of the the variable `state` is
- *if it was the result of* `torch.save(f, MoleculeModel)`, there's no `args` attribute of a `MoleculeModel`, so the `state["args"]` access is confusing me
- the code snippet is not directly related to your question. You're asking about loading previous model weights, but this code snippet is about initializing a `MoleculeModel` from a previous `.pt` file

**Comment by davidegraff** [comment]
a more general note is that I can't really help you if your examples use files on your local machine. You'll need to provide a minimal working example to properly diagnose what's going on

**Comment by devpunjabi** [comment]
The model was created using : 
```
chemprop_train --data_path data/data.csv --dataset_type classification --save_dir dmpnn_checkpoints
```
For loading weights we need the MoleculeModel object first. Therefore the initialization code. This itself is not functioning, so I cant go further. 
Code : 
```
import torch
from src.utils.molecule_model import MoleculeModel
from src.utils.mpn import MPN
from src.utils.args import TrainArgs

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

###path where the trained model was saved
path_grph = '/home/dev/Documents/dev/dmpnn_checkpoints/fold_0/model_0/model.pt'

state = torch.load(path_grph, map_location=lambda storage, loc: storage)
args = TrainArgs()
args.dataset_type = 'classification'
#### I tried setting this to false because of the expection. But does not work either.
args.reaction = False

```

Here is the stack trace : 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_5056/3249615126.py in <module>
     20 
     21 # Build model
---> 22 graph_model = MoleculeModel(args)
     23 
     24 print(graph_model)

~/Documents/dev/src/utils/molecule_model.py in __init__(self, args)
     53             self.softplus = nn.Softplus()
     54 
---> 55         self.create_encoder(args)
     56         self.create_ffn(args)
     57 

~/Documents/dev/src/utils/molecule_model.py in create_encoder(self, args)
     63         :param args: A :class:`~chemprop.args.TrainArgs` object containing model arguments.
     64         """
---> 65         self.encoder = MPN(args)
     66 
     67         if args.checkpoint_frzn is not None:

~/Documents/dev/src/utils/mpn.py in __init__(self, args, atom_fdim, bond_fdim)
    169         """
    170         super(MPN, self).__init__()
--> 171         self.reaction = args.reaction
    172         self.reaction_solvent = args.reaction_solvent
    173         self.atom_fdim = atom_fdim or get_atom_fdim(overwrite_default_atom=args.overwrite_default_atom_features,

TypeError: get_atom_fdim() got an unexpected keyword argument 'is_reaction'
```

**Comment by cjmcgill** [comment]
It looks like your line numbers are a little different than mine and your file `molecule_model.py` is a different file name than mine, so I guess you're on a development fork for this.

The keyword argument `is_reaction` was added to the function `get_atom_fdim` in PR #246 about 3 months ago. The new argument added to `get_atom_fdim` in `featurization.py` was added in the same commit as the line in `mpn.py` that added the keyword to the function call. But it appears you have it in the function call but not in the function?

Is it possible that you have mixed install files from different commits? Or did you have a manual change in `featurization.py` that would have removed that keyword?

**Comment by devpunjabi** [comment]
Thank you for the clarification. The issues was as you mentioned.
A few pointers though :
- When running model with predetermined splits, the Exception does not say val_fold_index is also required. It only says test_fold_index is required. I spent a lot of time looking into the code to figure this out. 
- Also no where the file format for folds_file is mentioned. 
```
chemprop_train --data_path './data/dpnn.csv' --dataset_type classification --save_dir dmpnn_checkpoints --folds_file './cv_splits.pickle' --split_type predetermined --val_fold_index 1 --test_fold_index 2
```
