### ISSUE TITLE
[QUESTION]: Writting all columns to the test_pred.csv/test_full.csv file

### ISSUE THREAD

**Issue by pkiruba** [chemprop/chemprop#278]
**What are you trying to do?**
Hi, I am trying to train the model with the `--save_preds` option. After training, the `test_preds.csv` is generated and the data has only two columns, i.e., smiles and the target_values, though I would also want to write the remaining columns which are in my data csv file.

Is there any option where it can also write other columns to the test output file?

**Comment by cjmcgill** [comment]
The `--save_preds` argument saves results in a more limited way than chemprop does in a more limited way than predict.py does, where prediction outputs have more capabilities like being calculated across cross validation folds, with secondary outputs like uncertainty, and with some options controlling what to return if any molecules are invalid.

So I don't have a direct argument that does what you're looking for. But I do have two options that may get you where you need. 
- Use `--save_smiles_splits` to save the data file portion that went to each of the train/val/test splits. These split files include all extra columns, so between them and your save_preds output, you should have everything you need.
- After you run a train.py job, you can then go back and run a predict.py job. Either on your whole data file or perhaps on the test split as saved by `--save_smiles_splits` during training. The output from predict.py will include the extra columns (though will overwrite the target columns).

**Comment by pkiruba** [comment]
Hi @cjmcgill, Thanks for the different options. Is `--save_smiles_splits` really saving the extra columns to the train/val/test data file portions? In my case, I still see only the smiles and target value columns in the train/val/test split csv files. 
This is my data file used for training
```
smiles,p_np,names,othernames
[Cl].CC(C)NCC(O)COc1cccc2ccccc12,1,cmp1,smi1
C(=O)(OC(C)(C)C)CCCc1ccc(cc1)N(CCCl)CCCl,1,cmp2,smi2
c12c3c(N4CCN(C)CC4)c(F)cc1c(c(C(O)=O)cn2C(C)CO3)=O,1,cmp3,smi3
C1CCN(CC1)Cc1cccc(c1)OCCCNC(=O)C,1,cmp4,smi4
Cc1onc(c2ccccc2Cl)c1C(=O)N[C@H]3[C@H]4SC(C)(C)[C@@H](N4C3=O)C(O)=O,1,cmp5,smi5
CCN1CCN(C(=O)N[C@@H](C(=O)N[C@H]2[C@H]3SCC(=C(N3C2=O)C(O)=O)CSc4nnnn4C)c5ccc(O)cc5)C(=O)C1=O,1,cmp6,smi6
CN(C)[C@H]1[C@@H]2C[C@H]3C(=C(O)c4c(O)cccc4[C@@]3(C)O)C(=O)[C@]2(O)C(=O)\C(=C(/O)NCN5CCCC5)C1=O,1,cmp7,smi7
Cn1c2CCC(Cn3ccnc3C)C(=O)c2c4ccccc14,1,cmp8,smi8
COc1ccc(cc1)[C@@H]2Sc3ccccc3N(CCN(C)C)C(=O)[C@@H]2OC(C)=O,1,cmp9,smi9
```
This is the output generated after the below command
`chemprop_train --data_path data/bbbp.csv --dataset_type classification --save_dir bbbp_checkpoints_binary_cross_entropy_metrics_with_dummy_columns --save_preds --save_smiles_splits --metric binary_cross_entropy`

train_full.csv
```
smiles,p_np
Cc1onc(N[S](=O)(=O)c2ccc(N)cc2)c1,1.0
C1=CC(=CC=C1\C(C2=CC=CN=C2)=C\CNC)Br,1.0
CCCCCc1cc(O)c2[C@@H]3C=C(C)CC[C@H]3C(C)(C)Oc2c1,1.0
[C@]2(C1=CC(=CC=C1)O)([C@H](CN(C)CC2)C)CCC,1.0
CCc1cc(ccn1)C(N)=S,1.0
C1=CC=CC2=C1C(CC3=C(N2C)C=CC=C3)NC,1.0
C(C(Cl)(Cl)Cl)OC(OCC(Cl)(Cl)Cl)=O,1.0
[C@H](OC1=C(C=CC=C1)C)(C2=CC=CC=C2)CCNC,1.0
[C@H]23[C@@]([C@@]1(C(=CC(=O)C=C1)[C@H](C2)F)C)([C@H](C[C@]4([C@H]3C[C@@H](C)[C@@H]4C(COC(C(C)(C)C)=O)=O)C)O)F,1.0
```

Thanks for the second option. I'm aware of it already and `predict.py` includes the extra columns from my initial data file.

**Comment by cjmcgill** [comment]
Oh! You're right @pkiruba . I misread the code there, I'm sorry about that. I'm afraid then going through the predict function is the only option that I see for you right now.

I think this is something that could be added reasonably. I will take a look at how it could be implemented.

**Comment by pkiruba** [comment]
Hi @cjmcgill, Thanks for your prompt reply. I will use predict.py for my predictions.
