### ISSUE TITLE
[QUESTION]: Checkpoints issue

### ISSUE THREAD

**Issue by fdaqin** [chemprop/chemprop#287]
Thank you for such a great tool! My problem is simple, that is, we want to predict some properties using chemprop. 
However, after I opened the web interface, I found that the checkpoint drop-down box was empty. So my question is does chemprop provide some pretrained models or do I need to train the model by myself based on the relevant dataset? Thanks!

![image](https://user-images.githubusercontent.com/33869719/170174694-44cb33b4-e1e4-4ae0-a5e0-3e2d335f99c3.png)

**Comment by cjmcgill** [comment]
Hi, sorry for the terrible delay on an answer. The primary purpose of chemprop is to be a platform for you to train models with your own data. There isn't a bank of pretrained models that come with the code. However, there are some good published chemprop models out there that may be worth looking at.
https://doi.org/10.5281/zenodo.6527882
https://zenodo.org/record/5573027

**Comment by fdaqin** [comment]
Thanks! got it!
