### ISSUE TITLE
[QUESTION]: Is input canonical or isomeric smiles?

### ISSUE THREAD

**Issue by mad-scientist-in-training** [chemprop/chemprop#293]
Hello!

I'm currently creating a dataset that I plan to put through ChemProp. I'm going through PubChem to assemble to molecules I need. However, some of the compounds have multiple smiles formats (see below).

![image](https://user-images.githubusercontent.com/70981989/173619140-4edfca77-712f-489c-aa13-8fcb42ec3f34.png)

Does the algorithm take in isomeric or canonical smiles, or does it matter? 

Thanks!

Camille

**Comment by cjmcgill** [comment]
Hi! Chemprop can accept either, they are both proper SMILES. Isomeric SMILES can provide some extra information about your molecule, like cis/trans or R/S chirality. If you want Chemprop to be able to differentiate between molecules using that stereo information, then you'll want to use isomeric.

**Comment by mad-scientist-in-training** [comment]
Ok awesome! Thank you! Last question - does the annotation have to be consistent? Like do they have to be all canonical or all isomeric, or can you mix?

**Comment by mad-scientist-in-training** [comment]
Hi, 

Thank you so much for the thorough answer! Much appreciated!

Best, 

Camille
