### ISSUE TITLE
[QUESTION]: Regarding interpretation

### ISSUE THREAD

**Issue by mad-scientist-in-training** [chemprop/chemprop#300]
Hi again!

Two questions:

1. I'm reading that you can use multiple inputs to identify a single target, and I just want to make sure that I have that right. For example, if I'm trying to train the model to decide whether a compound will have a shorter or greater half life, could I also put in relevant information in other columns (like Lipinski score) that might be helpful to train the model? 
2. Question regarding the interpretation of the model (specifically, the chemprop.interpret script). Does the output show you which parts of the molecule the model used to decide the target value that it predicts? For example in my project, is the output the functional group(s) that had the most weight in helping the model decide whether the molecule will overall have a longer/shorter half-life? 

Thank you!!

Camille

**Comment by cjmcgill** [comment]
1. Yes, it is often a good idea to co-train with targets that you think are related. So your data file would have a column for the thing you care about and a separate column for the thing you think would be related. Your model will then make predictions for both things, and they can help each other out if they are significantly related. You can co-train even when you have gaps in your data for either of the targets and it will still be helpful, and you won't need it for brand new predictions outside your dataset.

Now, if this other quantity is something that you will always have access to, even when making new predictions for things outside your dataset, then there is a better option. You can add them in as extra features. You can input a separate csv using `--features_path path/to/features.csv` where this additional information is stored in the same datapoint order as in your data file where your targets are (needs a column header, but no column for the smiles as it's assumed to correspond to your other file). This is typically a way to add additional data that the model can make better use of. The downside is that if you set up your model with this extra feature, it becomes strictly required to use the model. You can't have any gaps in the feature file and you can't make new predictions for things where you don't have that feature.

2. The interpret function has a limited scope of applicability, and I'm afraid that my understanding of it is a little bit limited as well. I believe that it will output the substructure that most contributed to a positive result being positive. Specifically though, it is just for positive results in classification jobs, and it sounds like your task is a regression task. Though you could potentially train a separate model where you did a classifier that was positive for half lives above or below some critical value and then use interpret on that. I don't have enough experience with it to tell you if that would be fruitful though.

**Comment by mad-scientist-in-training** [comment]
This is great, thank you so much :)

Camille
