### ISSUE TITLE
[QUESTION]: how to handle mixed continuous-categorical data?

### ISSUE THREAD

**Issue by GLPG-GT** [chemprop/chemprop#303]
Suppose you have experimental activity data, say pIC50's at some target for a set of compounds, but the experiment was only able to measure activity in the interval [5, 9.5], below and above which the data are reported as '< 5' or '> 9.5', respectively. This means of course that some data are continuous, other data categorical.

I saw a 'bounded_mse' option to handle such data in chemprop, but - please correct me if I am wrong - when I looked at the code, it seemed to me that it only strips the qualifier, i.e. any data with '< 5' becomes 5, and '> 9.5' becomes 9.5.
Then, if I understand correctly, the model will always output continuous values in regression mode, so if it predicts a pIC50 of 5, 4, 3, ..., -1..., for compounds that have '< 5' as the original pIC50, it will simply add to the mse a corresponding squared residual using the fixed un-censored value (5): (5-5)^2, (5-4)^2, (5-3)^2, ..., (5-(-1))^2, ...,?
But in fact the model is 'right' in predicting a value below 5 for a compound that has '< 5', so why should it add a relatively large squared residual contribution to the mse for such a prediction?

This case is quite frequent in practice, especially with ADMET data, and censored values are often a substantial fraction of the total data points, so the information they bring is valuable and should be used rather than, e.g. filtered out. And indeed, various approaches to handle such cases are described in the literature, most notably censored regression methods (such as Tobit), which were also implemented in some packages (e.g. https://github.com/fabsig/KTBoost).

Is this aspect already addressed by chemprop by some option I missed? And if not, is there any plan to include it in future releases?

Thanks

**Comment by cjmcgill** [comment]
Hi, the case you're describing is the intended use-case for bounded_mse.

The inequalities do indeed get used in the loss function. In the code, it does strip out the < and > for the values stored in the targets data attribute. However, it also stores the locations of the < and > in the gt_targets and lt_targets attributes. You can see this in the `chemprop/data/utils.py get_inequality_targets()`. 

These attributes then tell the the loss function when to censor loss values. The bounded_mse loss ignores predictions within the covered inequality range. So for a '>3' target the losses would be {0:9, 1:4, 2:1, 3:0, 4:0, 5:0}.

**Comment by cjmcgill** [comment]
If I'm understanding the link properly, it has a set upper and lower limit. With bounded_mse, the limits are set on a datapoint by datapoint basis, so you could have a mix of different assay sources with different ranges or have flexibility to make judgements on individual points that may need them.

**Comment by GLPG-GT** [comment]
Thank you very much! I had indeed misunderstood how it worked, apologies.
And indeed, it sounds better than just setting fixed left and right thresholds.

**Comment by GLPG-GT** [comment]
An additional observation.  
I tried just now training a multi-task model with sparse data that were partly censored (qualified with '>' and '<'), and I got an error saying 'operands could not be broadcast together with shapes...'.  
I looked at possible issues with my data, but I could find none.  
I tried reducing the number of columns to model, in case they were too many (65). But no, even with just 2 columns to model, same error (only with different numbers after 'shapes...').  
Only when I reduced the columns to model to just one, it worked, although much more slowly than when I started with a dense csv with only that same column (+SMILES).  
And the same data seem to work well (still running now) if I remove all qualifiers and use 'mse' and 'rmse' as loss_function and metric, respectively, in the TrainArgs, with no other change anywhere else.  

Is the 'bounded_mse' method perhaps limited to single task modelling? Or is this unexpected?

Here is the list of args I used:

args = TrainArgs()

args.from_dict({
        'dataset_type' : 'regression',
        'data_path' : dataPath
        })

args.hidden_size = 300
args.depth = 3
args.ffn_num_layers = 2
args.dropout = 0.2
args.bias = False
args.activation = 'ReLU'
args.max_lr = 0.0005
args.epochs = 50
args.ffn_hidden_size = args.hidden_size
args.save_dir = saveDir
args.extra_metrics = ["r2"]
args.show_individual_scores = True
args.ignore_columns = cols_to_ignore
args.smiles_columns = SMILES_colname
args.save_preds = True
args.loss_function = 'bounded_mse'
args.metric = 'bounded_rmse'
args.num_folds = 5
args.split_type = 'random'
args.split_sizes = [0.8, 0.1, 0.1]
args.seed = 55641

cross_validate(args = args, train_func = run_training)

**Comment by cjmcgill** [comment]
This is unexpected but you may have found a bug in the implementation. Could you paste in the error trace back?

**Comment by GLPG-GT** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/data/Projects/try.ipynb Cell 36 in <cell line: 54>()
     51 args.split_sizes = [0.8, 0.1, 0.1]
     52 args.seed = 55641
---> 54 cross_validate(args = args, train_func = run_training)

File /data/software/conda/envs/chemprop151_GT/lib/python3.8/site-packages/chemprop/utils.py:538, in timeit.<locals>.timeit_decorator.<locals>.wrap(*args, **kwargs)
    535 @wraps(func)
    536 def wrap(*args, **kwargs) -> Any:
    537     start_time = time()
--> 538     result = func(*args, **kwargs)
    539     delta = timedelta(seconds=round(time() - start_time))
    540     info = logging.getLogger(logger_name).info if logger_name is not None else print

File /data/software/conda/envs/chemprop151_GT/lib/python3.8/site-packages/chemprop/train/cross_validate.py:116, in cross_validate(args, train_func)
    113         model_scores = json.load(f)
    114 # Otherwise, train the models
    115 else:
--> 116     model_scores = train_func(args, data, logger)
    118 for metric, scores in model_scores.items():
    119     all_scores[metric].append(scores)

File /data/software/conda/envs/chemprop151_GT/lib/python3.8/site-packages/chemprop/train/run_training.py:275, in run_training(args, data, logger)
    273 if isinstance(scheduler, ExponentialLR):
...
    142     preds,
    143 )
    144 return mean_squared_error(targets, preds, squared=False)

ValueError: operands could not be broadcast together with shapes (1396,) (65,)

**Comment by cjmcgill** [comment]
A fix for this is in PR #308. The implementation of the inequalities in the evaluation metrics is broken. Until the PR is reviewed and merged, you can run using `--metric rmse` to train with the inequality included but neglect it in evaluation or you can train on branch that was created for that PR.
