### ISSUE TITLE
[BUG]: TypeError appears when using mve_weighting with ence

### ISSUE THREAD

**Issue by shihchengli** [chemprop/chemprop#305]
**Describe the bug**
If `--calibration_method mve_weighting --evaluation_methods ence` is used, the TypeError will appear in L256 in uncertainty_evaluator.py. That's because original_scaling is an integer, not a list. The value of scaling in the calibrator object is assigned as 1 in L449 in uncertainty_calibrator.py. A similar error would also be raised when using `interval` as `regression_calibrator_metric`. To solve this problem, L449 and L451 in uncertainty_calibrator.py can be modified from a single value to a list with repeated values in the shape of the number of tasks.

**Example(s)**
TypeError: 'int' object is not subscriptable

**Additional context**
Suggested code: L448-451 in uncertainty_calibrator.py
```
        if self.regression_calibrator_metric == "stdev":
            self.scaling = np.repeat(1, targets.shape[1])
        else:  # interval
            self.scaling = np.repeat(erfinv(self.interval_percentile / 100) * np.sqrt(2), targets.shape[1])
```

**Comment by kevingreenman** [comment]
We are closing all bug reports that we don't have time to fix before the release of v1.7 this month, and unfortunately this is one of them. We will soon release [Chemprop v2.0](https://github.com/chemprop/chemprop/issues/517) and do not plan to maintain/support v1.x any longer. If anyone has time to open a PR that fixes this bug before the end of January 2024, we will review it and consider including it in v1.7.
