### ISSUE TITLE
Document Machine Requirements / Runtime

### ISSUE THREAD

**Issue by Miserlou** [chemprop/chemprop#31]
Hello, all! Fantastic work!

In your papers and GitHub documentation, I haven't found anything about that RAM/GPU/Time requirements for reproducing your results. Can this be done in a reasonable time on a normal workstation, or does it require an HPC cluster?

Cheers!,
Rich

**Comment by swansonk14** [comment]
Hi Rich,

Thank you for your interest in chemprop and thank you for the question! For small datasets (~1000 molecules), it's possible to train on a standard laptop with only CPUs within a few minutes. However, for larger datasets and larger chemprop models, training will be very slow without a GPU. The specific RAM/GPU/Time requirements vary primarily based on dataset size, but even our largest dataset (ChEMBL with ~500,000 molecules) can train on a GPU in just a few hours.

I'll add some of this information to the README and I hope this helps!

Best,
Kyle
