### ISSUE TITLE
[QUESTION]: Is the feed-forward layer of the model a predicted value?

### ISSUE THREAD

**Issue by PussInCode** [chemprop/chemprop#313]
I don't quite understand what the meaning of this feed-forward layer is, whether it is possible to define parameters such as the network depth of the feed-forward layer yourself
https://github.com/chemprop/chemprop/blob/442a1602b670f173de166f987eab64396571ee98/chemprop/models/model.py#L196
https://github.com/chemprop/chemprop/blob/442a1602b670f173de166f987eab64396571ee98/chemprop/models/model.py#L101

**Comment by cjmcgill** [comment]
Models trained in Chemprop have two component models, operating in series. The first is a message passing neural network model that acts on the molecular graph (the encoder in the code you referenced), taking information about local atoms and bonds at specific locations in the graph and passing it to adjacent locations sequentially with message passing operations. The output of the mpnn is then aggregated across all the atoms of a molecule into a single vector for the molecule. This vector is then sent as input to a feed forward network (ffn in the code), where it is processed through linear neural network layers to reach the predicted output of the model. 

There are parameter settings that apply separately to the mpn and ffn portions. The parameter "depth" controls how many passes to make in the mpn and "hidden_size" controls the hidden representation size used in the mpn. The parameter "ffn_num_layers" sets how many linear layers are included in the ffn and "ffn_hidden_size" sets the hidden size used at intermediate layers in the ffn.

**Comment by PussInCode** [comment]
thanks，I got it
