### ISSUE TITLE
[QUESTION]: Chemprop can in-depth study in the sense of multitasking?

### ISSUE THREAD

**Issue by PussInCode** [chemprop/chemprop#315]
- I'm confused about chemprop multitasking，the multitasking in the tutorial is just a model for multiple goals or a multitasking model where related tasks will perform better？
![image](https://user-images.githubusercontent.com/38970840/184470972-e501733d-b77a-40ae-a939-610a72ffbadc.png)

**Comment by kevingreenman** [comment]
Using a multi-task model to predict multiple properties simultaneously may or may not perform better than using separate models for each individual task. This will be different for every set of properties and can only be known empirically by testing both methods. Generally, one can expect that properties that are correlated with one another or that are related to similar underlying physical mechanisms will benefit from multi-task learning, but this isn't always the case.

**Comment by PussInCode** [comment]
ok,I got it,thanks

**Comment by PussInCode** [comment]
I am still not sure if you have implemented the function of multi-task training, have the loss function and network structure of multi-task synchronous training been completed?

**Comment by kevingreenman** [comment]
Chemprop has always been able to train on multiple tasks simultaneously, as described in your screenshot above. Are you having some trouble or running into errors when you try to do this? If you can provide more details about what you're trying to do and/or any error messages you're getting, we can give you more specific advice.

**Comment by kevingreenman** [comment]
Closing this issue now, feel free to reopen if you have more questions related to this
