### ISSUE TITLE
[BUG]: setting checkpoint_dir in PredictArgs() causes an error, one has to set checkpoint_paths

### ISSUE THREAD

**Issue by GLPG-GT** [chemprop/chemprop#319]
We have trained an ensemble of 5 regression models.  
We now want to calculate some predictions from a file, including ensemble uncertainty.  
As per [instructions](https://chemprop.readthedocs.io/en/latest/args.html#predict-arguments:~:text=the%20atom%20features.-,checkpoint_dir,%3D%20None,-%C2%B6), we try:
![image](https://user-images.githubusercontent.com/96192927/187905858-f65ef4fc-694d-447e-be60-ddd1293f9700.png)
```
args = PredictArgs()
args.checkpoint_dir = path_to_models_dir
args.uncertainty_method = 'ensemble'
args.test_path = path_to_test_csv_to_predict
args.smiles_columns = ['SMILES']
args.preds_path = path_to_predictions_with_unc
out = make_predictions(args = args)
```
`path_to_models_dir` is a path to the main folder where all the models are (ending in '/').

Result:
![image](https://user-images.githubusercontent.com/96192927/187905753-c93d3616-ceba-462d-8ca3-6f4152ab356f.png)

However, if we `glob` the `.pt` files ourselves into list ` path_to_model_pts` and do instead:
```
args = PredictArgs()
args.checkpoint_paths = path_to_model_pts
args.uncertainty_method = 'ensemble'
args.test_path = path_to_test_csv_to_predict
args.smiles_columns = ['SMILES']
args.preds_path = path_to_predictions_with_unc
```

Then the predictions and their ensemble uncertainties are calculated and saved.

Isn't the expectation that when one supplies the `checkpoint_dir`, the `checkpoint_paths` are created automatically?

**Comment by kevingreenman** [comment]
Thanks for reporting this issue. The `checkpoint_paths` are created from the `checkpoint_dir` [here](https://github.com/chemprop/chemprop/blob/442a1602b670f173de166f987eab64396571ee98/chemprop/args.py#L188) under `CommonArgs`. Some predict arguments (such as `checkpoint_dir`) are in `CommonArgs` because they're shared by training.

I tried reproducing your issue using the command line and some test files available in the repo, but the following works without error.
```
python ~/chemprop/train.py --data_path ~/chemprop/tests/data/regression.csv --dataset_type regression --save_dir ~/chemprop/tests/ --epochs 3 --ensemble_size 3

python ~/chemprop/predict.py --test_path ~/chemprop/tests/data/regression.csv --checkpoint_dir ~/chemprop/tests/ --preds_path preds.csv --ensemble_variance
```
I'm continuing to investigate.

**Comment by GLPG-GT** [comment]
Thank you.
Yes, I saw that all these path and dir parameters were in `CommonArgs` rather than in `PredictArgs`.
However, in our case one worked and the other didn't, despite the fact that I defined them in `PredictArgs`. So I thought it might be a bug.

Because of how we have set up our workflows, we tend to use wrappers like `make_predictions` rather than the command line. I would not know how to pass the args in any other way.

https://chemprop.readthedocs.io/en/latest/train.html#:~:text=chemprop.train.make_predictions.make_predictions
![image](https://user-images.githubusercontent.com/96192927/187967815-797f5940-1146-4f07-b40b-3b51e134331e.png)

Thank you again for looking into this. If there is some way to pass the dir parameter to the wrapper, it would be great.

**Comment by oscarwumit** [comment]
Thanks for the input. Our main task is to ensure Chemprop works via regular call from the command line interface. Currently we have limited support if you want to customize or selectively import Chemprop functions via API. Thus, the issue reported here is not a bug, but more of the need for additional features. We value your input and we will work on this in future releases. Thanks.
