### ISSUE TITLE
[QUESTION]: on Interpretation

### ISSUE THREAD

**Issue by mad-scientist-in-training** [chemprop/chemprop#320]
Hello!

I was able to use the interpret script for the classification model I trained, but I just have a question (maybe it's basic- this is a relatively new field to me) about the interpretation of the rationale. 

For example, I ran this molecule and got the following: 

SMILES: CN1C(=NNC1=O)CN2C=CC(=C(C2=O)OC3=CC(=CC(=C3)C#N)Cl)C(F)(F)F
classification: 0.997443318367004
rationale: Clc1cc([CH3:1])cc([OH:1])c1
rationale score: 1

I'm using Chemdraw to draw the molecule from the SMILES string, but I don't really know what I'm looking at for the rationale. Are the atoms connected? Are they listed in order or how they are used in the rationale, but not connected at all? For example, is Cl separate from the c1 next to it, or is this saying this as one long connected set of atoms? is c1 the first carbon next to Cl? 

I guess in general I'm just trying to figure out how to enter the rationale string into chemdraw so I can highlight the parts of the molecule that were the most important for the classification. 

Thank you so much!!

Camille

**Comment by kevingreenman** [comment]
Hi Camille, thanks for your question. I think the easiest way to draw the rationale in a ChemDraw file is to paste it as a SMILES string. The rationale should function like any other SMILES string. The ":1" indicate the atom(s) at which the rationale is connected to the rest of the molecule. 

Hopefully that helps. Feel free to re-open this issue and post more comments if that doesn't solve your problem or if you have additional questions.
