### ISSUE TITLE
[QUESTION]: Is it possible to hyperoptimise the parameters on pre featurized data?

### ISSUE THREAD

**Issue by KGrewal1** [chemprop/chemprop#321]
Currently trying to optimise the hyperparameter on a model using rdkit features generator, causing the features generator to run on every cycle of optimisation as opposed to only once at the start.
Is it possible to run the features generator directly on a featurized MoleculeDataset as opposed to reading from a file.
Current Code
```
  arguments = [
      '--data_path', 'sol_train.csv',
      '--dataset_type', 'regression',
      '--num_iters', '20',
      '--config_save_path', 'config_reg.json',
      '--features_generator', 'rdkit_2d_normalized',
      '--search_parameter_keywords', 'all',
      '--no_features_scaling'
  ]
  args = chemprop.args.HyperoptArgs().parse_args(arguments)
  chemprop.hyperparameter_optimization.hyperopt(args = args)
```

**Comment by davidegraff** [comment]
unfortunately, it doesn't look like there's much you can do here short of editing the source:
1. the objective function in a hyperoptimization performs [cross-validation](https://github.com/chemprop/chemprop/blob/master/chemprop/hyperparameter_optimization.py#L87) of the model
2. in each call to the [`cross_validate` function](https://github.com/chemprop/chemprop/blob/442a1602b670f173de166f987eab64396571ee98/chemprop/train/cross_validate.py#L22), we [load the data](https://github.com/chemprop/chemprop/blob/442a1602b670f173de166f987eab64396571ee98/chemprop/train/cross_validate.py#L75)
3. in the [`get_data` function](https://github.com/chemprop/chemprop/blob/442a1602b670f173de166f987eab64396571ee98/chemprop/data/utils.py#L226) we build a `MoleculeDatapoint` [for each datapoint](https://github.com/chemprop/chemprop/blob/442a1602b670f173de166f987eab64396571ee98/chemprop/data/utils.py#L410)
4. a `MoleculeDatapoint` generates its extra features on-the-fly [at initialization](https://github.com/chemprop/chemprop/blob/442a1602b670f173de166f987eab64396571ee98/chemprop/data/data.py#L115)

If this is severely rate-limiting for you, I would recommend something along the lines of (i) defining an additional `features` argument of a `MoleculeDataset` that holds an `n x d` array, where the `i`th entry is the precomputed molecule-level features for molecule `i` and (ii) overriding the `features` atrribute of each `MoleculeDatapoint` inside the initializer of the `MoleculeDataset`

**Comment by cjmcgill** [comment]
I have an alternative that you could do it in a slightly manual way. You can use the save_features.py script in the chemprop/scripts directory to generate a npz features file that corresponds to your data file. Then in your hyperparameter optimzation, you input that features npz files with --features_path.

**Comment by KGrewal1** [comment]
Thanks: reading in from a features file seems to have worked. Much appreciated.
