### ISSUE TITLE
[QUESTION]: Chemprop_predict set_num_threads 

### ISSUE THREAD

**Issue by frozenarm** [chemprop/chemprop#322]
Is there a way to control the number of threads that chemprop is using when running chempro_predict on CPU?

Pytorch has:

torch.set_num_threads(int)
Sets the number of threads used for intraop parallelism on CPU.

I am seeing high CPU usage when running on server. I am looking a way to restrict it.

**Comment by shihchengli** [comment]
Thanks for your asking. I just took a look at how to set the number of threads used for intra operations on CPU. By default, pytorch will use all the available cores on the computer. We can use `torch.get_num_threads()` get the default threads number. As for how to restrict it, apart from setting the number of threads via `torch.set_num_threads()`, we can also set the env variable `OMP_NUM_THREADS` or `MKL_NUM_THREADS` to set the number of threads. Before you running the program, you can do `export OMP_NUM_THREADS=num_threads` in which `num_threads` is the number of threads you want to use.

**Comment by kevingreenman** [comment]
Closing this issue now, feel free to re-open if you have additional questions.
