### ISSUE TITLE
[QUESTION]: generating MoleculeDataset with SMILES and additional features (NOT CSV INPUT)

### ISSUE THREAD

**Issue by iwwwish** [chemprop/chemprop#323]
**What are you trying to do?**
I have a GCNN model built using chemprop that takes SMILES and an additional (binary) feature as inputs. When predicting test compounds, I am not loading data from a CSV file (in this case I could simply provide path to the file containing additional features for the test compounds as an argument to `chemprop_predict` method). But I have the SMILES available in a list object in Python. So, I went ahead and tried to generate a MoleculeDataset object using the utility method `get_data_from_smiles` available in `chemprop/data/utils.py`. But I see that [the method](https://github.com/chemprop/chemprop/blob/442a1602b670f173de166f987eab64396571ee98/chemprop/data/utils.py#L440) takes a list of feature generators as argument but not the additional features. Therefore, I modified the method as follows: 

**Previous attempts**
```
def get_data_from_smiles_with_additional_features(smiles: List[str],
                         skip_invalid_smiles: bool = True,
                         logger: Logger = None,
                         features: List = None,
                         features_generator: List[str] = None) -> MoleculeDataset:
    """
    Converts SMILES to a MoleculeDataset.

    :param smiles: A list of SMILES strings.
    :param skip_invalid_smiles: Whether to skip and filter out invalid smiles.
    :param logger: Logger.
    :param features: List of additional features
    :param features_generator: List of features generators.
    :return: A MoleculeDataset with all of the provided SMILES.
    """
    debug = logger.debug if logger is not None else print

    data = MoleculeDataset([
        MoleculeDatapoint(
            smiles=smile,
            features=feature,
            row=OrderedDict({'smiles': smile}),
            features_generator=features_generator
        ) for smile, feature in zip(smiles, features)
    ])

    # Filter out invalid SMILES
    if skip_invalid_smiles:
        original_data_len = len(data)
        data = filter_invalid_smiles(data)

        if len(data) < original_data_len:
            debug(f'Warning: {original_data_len - len(data)} SMILES are invalid.')

    return data
```

**Question**
The predictions I obtain using this method match the predictions from command line when using an additional file with the same features. However, I have only used a single feature (i.e., one column in a file). Is there a better way to deal with this when I have  multiple additional features?

Thank you,
Vishal

**Comment by shihchengli** [comment]
```
from chemprop.features import load_features
# Load features
if features_path is not None:
    features_data = []
    for feat_path in features_path:
        features_data.append(load_features(feat_path))  # each is num_data x num_features
    features_data = np.concatenate(features_data, axis=1)
else:
    features_data = None
```
Thanks for your asking. The above code is a demonstration of reading additional features from different .csv files. You can iterate the `features_data` and take each element as the attribute of `features` in each `MoleculeDatapoint` object.

**Comment by iwwwish** [comment]
Hi @shihchengli

Thank you for your answer. When I am using a trained model to predict new compounds, I am not loading features from a CSV file. Let me be clear this time:

1. I trained a model using SMILES and additional features (this was done via command line as follows). The additional features are nothing but predictions from a previous model:

```
python train.py --data_path training.csv --dataset_type classification --save_dir chemprop_model2/ --features_path training_model1_preds.csv --no_features_scaling
```

2. Next, I am using the trained model in my Python script. For test compounds, I have a list of SMILES and a list of additional features. I am transforming the SMILES and the features into a MoleculeDataset as follows:

```
full_data = get_data_from_smiles_with_additional_features(smiles=smiles, features=additional_features)
# some more lines of code here
dataset = MoleculeDataset([full_data[i] for i in sorted(full_to_valid_indices.keys())])
data_loader = MoleculeDataLoader(dataset=dataset, batch_size=1, num_workers=0)
model_preds = predict(model=model, data_loader=data_loader, scaler=scaler)
```

**Question**: The modified function `get_data_from_smiles_with_additional_features` works when I have a single list of features. How should I go about loading data when I have multiple lists of features?

Thanks!

**Comment by shihchengli** [comment]
In the case of a single list, I think the shape of your `additional_features` is (num_data, 1). As for multiple lists of features, you can just let the shape of `additional_features` be (num_data, num_features).

**Comment by iwwwish** [comment]
That worked! Thank you.

Is there a way to obtain information from the model file itself whether it takes additional features as input and if yes, the expected shape of the additional features?

Best,
Vishal

**Comment by shihchengli** [comment]
```
import torch
from chemprop.args import TrainArgs
path = '/path/to/checkpoint'
state = torch.load(path, map_location=lambda storage, loc: storage)
args = TrainArgs()
args.from_dict(vars(state["args"]), skip_unsettable=True)
args.features_size  # expected shape of the additional features
```
@iwwwish You can use the above code to get the size of molecular features. I will close this issue now. If you have other questions about Chemprop, feel free to open a new issue.
