### ISSUE TITLE
[QUESTION]: Is the num_folds keyword ignored when split type is not CV?

### ISSUE THREAD

**Issue by oiao** [chemprop/chemprop#334]
First of all, thanks a lot for releasing and maintaining the package.
My question is regarding the `num_folds` keyword which does not seem to behave in an expected way in combination with `split_type=random_with_repeated_smiles` (or any split type other than _'cv'_ it seems). The issue I had is that regardless of the provided `num_folds` argument, training:test:validation splits always resulted in the default 80:10:10%.
Checking the code it seems that the only instance where the number of folds is actually relevant is here

https://github.com/chemprop/chemprop/blob/2d00296a394e7eba470fe986c6554d0f77bc7913/chemprop/data/utils.py#L542-L562

Is this the intended behavior? This is not very clear from the README - one would expect this to work with all split types. Moreover, `num_folds` and `split_sizes` should be mutually exclusive. 

Many thanks for the clarification!

**Comment by cjmcgill** [comment]
Hi! The cv and cv-no-test split types are the split type options that use a traditional cross-validation where data are constrained to appear in the test set only once in the crossvalidation and the fraction of data in the test split is (1/num_folds). Indeed, when these split types are selected, split_sizes is ignored.

For all other split types, we use a non-traditional definition of crossvalidation. Each fold makes its own split independently. The random seed for each fold is different and the resulting splits are different, all adhering to the `split_sizes` fractions. The traditional crossvalidation requirement of a datapoint showing up in the test set only once is not imposed. This definition is useful for several reasons: more easily parallelizable, scalable to arbitrary sizes, stable model training avoiding small validation sizes for large numbers of folds, only needing one fold of splits held in memory at a time, ability to add marginal additional folds later, avoid interactions between the cv split size constraints and constraints of scaffold splitting.

I hope that clarifies the setting for you. This distinction should be made clear in the readme.

If you need a different splitting handling, there is always the option to split your data into folds externally and then provide them to chemprop as separate val/test sets or as indices as a index_predetermined split (primarily used for dev).

**Comment by oiao** [comment]
Thanks for the reply, that makes it clear. Indeed, maybe adding this to the README would be a good idea.
