### ISSUE TITLE
Does SMILES Canonicalization Affect Performance?

### ISSUE THREAD

**Issue by Miserlou** [chemprop/chemprop#34]
Sorry again to bother!

Quick question - should molecules be rendered into a "canonical" SMILES format before training, or does the model learn the features regardless? My intuition is that yes, they should all be canonicalized, and if you did this for your experiments, what method did you use to canonicalize?

Cheers!
R

**Comment by swansonk14** [comment]
Hi Rich,

No worries and thank you for the good questions! Canonicalization is actually not necessary for chemprop. Unlike some machine learning methods which apply neural networks directly to the SMILES string, we first convert the SMILES string to a molecular graph and then apply neural networks to the graph representation of the molecule. This is why chemprop is a "graph neural network," also known as a "message passing neural network". Therefore, as long as two SMILES strings represent the same molecule, they will have the same molecular graph and will be processed by chemprop in exactly the same way.

I hope this helps and as usual, please let us know if you have any other questions!

Best,
Kyle
