### ISSUE TITLE
Logo not visible with GitHub in Dark Mode

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#340]
Can we replace the current logo file's transparent background with a white background to make it visible in dark mode? Right now it looks like black text on a black background to me.

**Comment by davidegraff** [comment]
yeah it's a transparent SVG- we'd need to add a white background to it to fix that. Also, the san serif typeface is not embedded in the SVG and the serif typeface looks not great 😨

**Comment by shihchengli** [comment]
Yeah! I will fix it. Which typeface is better?

**Comment by davidegraff** [comment]
oh sorry for never responding. The san-serif definitely looks better!

**Comment by shihchengli** [comment]
@davidegraff Thanks! I just created a PR.

**Comment by kevingreenman** [comment]
@shihchengli your updated images look like they should work, but for some reason it's still showing up as if it's transparent to me

**Comment by kevingreenman** [comment]
It shows correctly for me now, not sure what was going on before. Thanks for the making the change!
