### ISSUE TITLE
[QUESTION]: wrong directory structure.

### ISSUE THREAD

**Issue by psahithireddy** [chemprop/chemprop#343]
**What are you trying to do?**
I am trying to run the integration test.

**Problem**
In line 27 of test_integration.py, shouldn't it be like TEST_DIR = "/data" instead of "tests/data"

**Comment by kevingreenman** [comment]
No. Running `python -m pytest -v` from the top level `chemprop/` directory results in no errors for `test_integration.py` or any other files on the `master` branch.
