### ISSUE TITLE
[FEATURE]: Batching of dataset creation when using chemprop_predict

### ISSUE THREAD

**Issue by tbrx** [chemprop/chemprop#346]
I was recently attempting to use `chemprop_predict` command line tool to screen against a decent sized library (a few million molecules). 

This caused a problem as the first step in this process was to read in *all* the data, to validate SMILES strings and produce a dataset object. That was problematic, as I ran out of RAM before this was done.

As a workaround I wrote my own screening script that called out to `make_prediction` multiple times. (One of the tutorial scripts gave a good example.)

But, it would be nice to use the command line tools for this! In my simple case (e.g. with no calibration set) it was fine to just read the full list of smiles from the file, and then process them in chunks, interleaved with calls to `make_prediction`.

**Comment by kevingreenman** [comment]
We are closing all enhancement requests for chemprop v1.x, as we will not have time to implement these before the upcoming release of [chemprop v2.0](https://github.com/chemprop/chemprop/issues/517). If there is still interest in this enhancement, please open a new issue after the release of v2.0.
