### ISSUE TITLE
Why use the same number of layers for input and output？

### ISSUE THREAD

**Issue by PussInCode** [chemprop/chemprop#347]
The input and output layers are generally not the same. Is there any point in doing this? Is the current matching already optimal?

https://github.com/chemprop/chemprop/blob/98fc25eec8c57171c56d6ffad03ae1336c016e3b/chemprop/models/model.py#L116

**Comment by kevingreenman** [comment]
This is not necessarily optimal, but it is a common choice for the sake of simplicity. Chemprop includes tools for doing hyperparameter optimization, including the hyperparameters for `ffn_hidden_size` and `ffn_num_layers`. If you want a different `ffn_hidden_size` for each hidden layer of the FFN, you would need to implement this yourself.
