### ISSUE TITLE
[QUESTION]: Is there a square root missing in the formula for the "ENCE" uncertainty evaluator? 

### ISSUE THREAD

**Issue by msk235** [chemprop/chemprop#356]
Hi all, 

I have a question regarding the Expected Normalized Error Evaluator:

In the paper you have referenced in the documentation they state that "mVAR(i) is the **root** of the mean uncertainty over the i-th bin" (Scalia et al. "Journal of chemical information and modeling" (2020)). 

The formula you use is `ence = np.mean(np.abs(mean_vars - rmses) / mean_vars, axis=1)` where `mean_vars` equals an array with the mean uncertainty / variance for each bin, not the root of the mean uncertainty for each bin (file: uncertainty_evaluator.py, line: 359).

Where does the square root from the original paper come into play, or am I missing something?

Thanks for your help!

**Comment by cjmcgill** [comment]
Hello,

It appears that you have indeed found a bug. I'll be following up with a PR that brings the equation in line with the definition used in Scalia et al.
