### ISSUE TITLE
[QUESTION]: evidential regression with partly bounded data

### ISSUE THREAD

**Issue by GLPG-GT** [chemprop/chemprop#359]
Apologies if this question was already asked.  
We have continuous data that are partly bounded (e.g. '>1000', '<0.01').  
When we simply remove the qualifiers '>', '<' and use loss_function = 'evidential', as desired we obtain models that are able to output uncertainty estimates for the predictions.  
If we do not remove the qualifiers and use loss_function = 'bounded_mse', we take into account the 'censored' nature of the data, but we lose the ability to calculate evidential uncertainty estimates.

Would there be a way to combine the two, i.e. not remove the qualifiers and at the same time do evidential modelling?  
Or does the fundamental machinery of evidential modelling require fully numerical data?

**Comment by kevingreenman** [comment]
I think it would be possible to combine these by merging the [`bounded_mse_loss`](https://github.com/chemprop/chemprop/blob/8fcc9032512c94ec4567fd0d79ef3d12710e207c/chemprop/train/loss_functions.py#L60) and [`evidential_loss`](https://github.com/chemprop/chemprop/blob/8fcc9032512c94ec4567fd0d79ef3d12710e207c/chemprop/train/loss_functions.py#LL327C5-L327C20) functions (running the `torch.where` lines of the former before all of the latter). 

I'm not aware of anyone studying the behavior of evidential uncertainty for bounded data, so this might lead to some unexpected behavior, and I'd be hesitant to implement it in the main repo without further study.

**Comment by kevingreenman** [comment]
Closing this issue now, feel free to reopen if you have more questions related to this
