### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by rishijagdev1** [chemprop/chemprop#36]
Hi, I get the following error while running the code in chemprop environment:

> (chemprop) C:\Users\1901566.admin\Downloads\chemprop-master>python web/run.py
> Traceback (most recent call last):
>   File "web/run.py", line 10, in <module>
>     from app import app, db
>   File "C:\Users\1901566.admin\Downloads\chemprop-master\web\app\__init__.py", line 6, in <module>
>     app.config.from_object('config')
>   File "C:\Users\1901566.admin\.conda\envs\chemprop\lib\site-packages\flask\config.py", line 174, in from_object
>     obj = import_string(obj)
>   File "C:\Users\1901566.admin\.conda\envs\chemprop\lib\site-packages\werkzeug\utils.py", line 568, in import_string
>     __import__(import_name)
>   File "C:\Users\1901566.admin\Downloads\chemprop-master\web\config.py", line 9, in <module>
>     import torch
>   File "C:\Users\1901566.admin\.conda\envs\chemprop\lib\site-packages\torch\__init__.py", line 81, in <module>
>     ctypes.CDLL(dll)
>   File "C:\Users\1901566.admin\.conda\envs\chemprop\lib\ctypes\__init__.py", line 348, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: [WinError 126] The specified module could not be found

Could anyone please help me with it? Thank you

**Comment by swansonk14** [comment]
Hi @rishijagdev1, thank you for the question! It looks like there might be an issue with your PyTorch installation since it seems to be crashing when it tries "import torch". Does chemprop work if you run [train.py](https://github.com/chemprop/chemprop/blob/master/train.py) instead of using the web interface? That could be a way to check whether PyTorch is installed correctly.

**Comment by rishijagdev1** [comment]
Hi @swansonk14 , thanks for your reply. No, it doesn't run while I run train.py as well. 
Am I supposedto install PyTrch separately, as I thought that it gets automatically installed with chemprop. Thanks in advance.
