### ISSUE TITLE
[QUESTION]: ChemProp Model Zoo

### ISSUE THREAD

**Issue by miha-skalic** [chemprop/chemprop#362]
Hi Chemprop developers and community. 

Firstly let me congratulate you for putting a great package together. Intuitive and straight forward use!

Coming to my question: Do you plan to incorporate different (GC) models in the future beyond the default MPN? Or are there any previous attempts (forks) doing this? Any hits would be appreciated. I'm thinking something like [dgl-lifesci](https://github.com/awslabs/dgl-lifesci/blob/master/python/dgllife/model/model_zoo) where they have plenty of models available.

**Comment by kevingreenman** [comment]
We don't have any plans to implement other architectures at this time.

There are other places that have done so (such as `dgl-lifesci` as you mention, as well as [DeepChem](https://github.com/deepchem/deepchem) and [PyG](https://github.com/pyg-team/pytorch_geometric)). I think one of Chemprop's strengths is that it's easy to use for molecules out-of-the-box without requiring a lot of PyTorch expertise, while some of these other tools offer more customizability to users with more expertise.

That being said, one of our current development priorities in Chemprop is to make it more modular and extensible, which will make Chemprop easier to integrate with other model types if the user desires. We plan to make many changes in this regard for the release of Chemprop version 2.0.

**Comment by kevingreenman** [comment]
Closing this issue now, feel free to reopen if you have more questions related to this
