### ISSUE TITLE
[QUESTION]: Advantages of MCTS for interpreting

### ISSUE THREAD

**Issue by PigUnderRoof** [chemprop/chemprop#366]
I am using interpreter functionalitiy for QSAR insights. Does MCTS method have some obvious advantages over methods like knock-out or feature masking, for example?

**Comment by davidegraff** [comment]
@cjmcgill @kevingreenman do we know who might be able to answer this?

**Comment by kevingreenman** [comment]
I'm going to close this for now, but @wengong-jin can respond if he sees this.
