### ISSUE TITLE
[BUG]: OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by sajjadGG** [chemprop/chemprop#372]
**Describe the bug**
When importing chemprop.data it can cause overflow error
the error is due to this line
`
csv.field_size_limit(sys.maxsize)
`
**Screenshots**
![image](https://user-images.githubusercontent.com/46228131/223607273-8b3dd1ec-9b1f-4658-a0f9-4d5be9100c1f.png)

**Environment**
- Python 3.8.16
- chemprop                  0.0.0                    pypi_0    pypi
- OS: Windows 11

**Checklist**
- [ ] all dependencies are satisifed: `conda list` shows the packages listed in the `README`
- [ ] the unit tests are working: `pytest -v` reports no errors

**Additional context**
pass more appropriate value to csv.field_size_limit(sys.maxsize)

**Comment by oscarwumit** [comment]
Hi, how big is the csv file that you are trying to parse to Chemprop? Is the csv file for training or for prediction?

**Comment by sajjadGG** [comment]
it doesn't matter when I import the module it causes and error it happens before the that
I had to comment this line in the code to resolve the issue I think the amount of sys.maxsize is too big to be passed to csv.field_size_limit

**Comment by oscarwumit** [comment]
Thanks. I think this is related to https://github.com/chemprop/chemprop/pull/280/commits/a728a23200d61ef62eda21e21123f64881a0d18a
@shihchengli maybe we should implement a number that is large enough to handle large csv files but not too large that will cause overflow.

**Comment by sajjadGG** [comment]
@oscarwumit If you want, I can make a pull request and fix it

**Comment by shihchengli** [comment]
@sajjadGG Thanks for reporting this issue. I am sorry my code implementation led to this unexpected behavior. I will fix this issue soon.
@oscarwumit Sure! I just opened a PR #373.

**Comment by oscarwumit** [comment]
@sajjadGG Thanks for reporting this bug. Would you mind testing if our solution https://github.com/chemprop/chemprop/pull/373 solve your issue successfully?
