### ISSUE TITLE
[FEATURE]: Support for multiple-GPU inference for large scale virtual screening

### ISSUE THREAD

**Issue by ogkdmr** [chemprop/chemprop#376]
**Is your feature request related to a problem? Please describe.**
Currently, Chemprop models can be used for prediction only on a single GPU. However, these models are wonderful candidates for high-throughput virtual screening of large ligand libraries. To increase the throughput of inference via parallelization, I suggest that you add support for data parallelism to the codebase.

**Use-cases/examples of this new feature**
One tangible use case is Chemprop as a docking surrogate where the model is trained to regress on the docking score of a ligand given its SMILES string. With such a surrogate, one can bypass docking and efficiently screen a ligand database like the Enamine (5.5 billion compounds). If the inference code was parallelized this would be much more computationally feasible.

**Desired solution/workflow**
A modification to the chemprop.train.make_predictions.py file could be made to incorporate nn.DataParallel. Also, CommonArgs would need to be modified so that --gpu : int becomes --gpu:List[int]. Also trivial dataloader logic can be added to distribute loaded batches to the GPUs at hand. 

**Discussion**
What are some considerations around this new feature? Are there alternative approaches to consider? What should the scope of the feature be?
Graph Neural Networks are quite data-efficient compared the Transformers trained on SMILES strings. We can see this manifest in the representation capacity of your model with just ~350k parameters. Therefore, it makes sense that data parallelism has not been implemented for training and inference (but supported for hyperparameter tuning via HyperOpt). That said, for any kind of large real-life dataset, lack of multi-gpu support renders the Chemprop codebase hard to deploy. I think data parallelism for inference is a must, and it could be extended to training for those who want to train larger models more efficiently.

**Additional context**

**Comment by davidegraff** [comment]
This is largely a problem in the original version of the code that we're aiming to fix with a ground-up rewrite in v2. If you want, you're more than welcome to manually implement DDP in the current code. With v2, we're wrapping the models in PyTorch Lightning to seamlessly handle the DDP backend. As for inference-time distribution, you can do this pretty easily via Ray (see [here](https://github.com/coleygroup/molpal/blob/main/molpal/models/mpnmodels.py#L33) for an example.) We're not looking to really support inference distribution as a core feature in Chemprop, as it's sort of extraneous to the core goal of providing software for property prediction and can be pretty easily implemented on your own, if necessary. If you think there's more to talk about, feel free to keep the issue open. Otherwise, I'll close it.

**Comment by ogkdmr** [comment]
Thanks for your response, @davidegraff. I'm closing the issue now.

**Comment by Sakura4036** [comment]
> This is largely a problem in the original version of the code that we're aiming to fix with a ground-up rewrite in v2. If you want, you're more than welcome to manually implement DDP in the current code. With v2, we're wrapping the models in PyTorch Lightning to seamlessly handle the DDP backend. As for inference-time distribution, you can do this pretty easily via Ray (see [here](https://github.com/coleygroup/molpal/blob/main/molpal/models/mpnmodels.py#L33) for an example.) We're not looking to really support inference distribution as a core feature in Chemprop, as it's sort of extraneous to the core goal of providing software for property prediction and can be pretty easily implemented on your own, if necessary. If you think there's more to talk about, feel free to keep the issue open. Otherwise, I'll close it.

I really think multi-gpu training and inference is a much needed and important feature.
I'd like to know when you plan to release the V2 version？

**Comment by davidegraff** [comment]
There is a pinned issue (#517) for details on the v2 timeline. As stated above, we don't intend to implement inference distribution as a core feature. There are a variety of ways to achieve this, each with their own pros and cons, and we can't assume what the right model for our end users will be. I provided one example above on using Ray to achieve inference distribution, but you could also use a variety of other frameworks (e.g., wrapping in a microservice) to achieve the same result. For single-machine distribution, we can look at the solution described [here](https://lightning.ai/docs/pytorch/stable/deploy/production_basic.html#enable-distributed-inference) but multi-GPU inference is low on our priority list for the reasons detailed above.
