### ISSUE TITLE
hyperparameteroptimization

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#377]
I am doing hyperparameter optimization with chemprop. After a few hours of running, it fails and the log file does not show any errors. Also, no .json file is generated. If you have any suggestions, please let me know. 

Here is the tail of the log file:

^M 61%|######    | 2394/3932 [13:54<08:20,  3.07it/s]
^[[A^[[A
^M 61%|######    | 2395/3932 [13:54<08:19,  3.07it/s]
^[[A^[[A
^M 61%|######    | 2396/3932 [13:54<08:15,  3.10it/s]
^[[A^[[A
^M 61%|######    | 2397/3932 [13:55<08:08,  3.15it/s]
^[[A^[[A
^M 61%|######    | 2398/3932 [13:55<08:13,  3.11it/s]
^[[A^[[A
^M 61%|######1   | 2399/3932 [13:55<09:03,  2.82it/s]
^[[A^[[A
^M 61%|######1   | 2400/3932 [13:56<09:21,  2.73it/s]
^[[A^[[A
^M 61%|######1   | 2401/3932 [13:56<09:13,  2.77it/s]
^[[A^[[A
^M 61%|######1   | 2402/3932 [13:57<08:57,  2.85it/s]
^[[A^[[A
^M 61%|######1   | 2403/3932 [13:57<08:38,  2.95it/s]
^[[A^[[A
Loss = 1.5168e+00, PNorm = 48.6410, GNorm = 3.8542, lr_0 = 5.1854e-06

^M 61%|######1   | 2404/3932 [13:57<08:32,  2.98it/s]
^[[A^[[A
^M 61%|######1   | 2405/3932 [13:58<08:59,  2.83it/s]
^[[A^[[A

**Comment by shihchengli** [comment]
Hi @SoodabehGhaffari, could you check if the system ran out of memory during the optimization process? If the dataset is too large, it could cause the process to crash without generating any error messages. You can try reducing the dataset size if that resolves the issue.

**Comment by SoodabehGhaffari** [comment]
Hi,
Thank you for the response. I just checked the status of my slurm job. It
did not run out of memory. Please see below; I was also wondering if the
hyperparameter optimization can be accelerated using GPU. The report below
shows it did not use GPU.

Any suggestions would be appreciated.
Best Regards
Soodabeh


***@***.*** chemprop]$ jobstats 46229681


================================================================================

                              Slurm Job Statistics

================================================================================

         Job ID: *46229681*

  NetID/Account: sg6615/molbio

       Job Name: anti-hyper

          State: FAILED

          Nodes: 1

      CPU Cores: 1

     CPU Memory: 50GB

           GPUs: 1

  QOS/Partition: della-cryoem/cryoem

        Cluster: della

     Start Time: Wed Mar 15, 2023 at 1:33 PM

       Run Time: 12:29:29

     Time Limit: 3-00:00:00


                              *Overall Utilization*

================================================================================

  CPU utilization  *[*|||||||||||||||||||||||||||||||||||||||||||||||99%*]*

  CPU memory usage *[*||||||                                         12%*]*

  GPU utilization  *[*                                                *0%*
*]*

  GPU memory usage *[*                                                1%*]*


                              *Detailed Utilization*

================================================================================

  CPU utilization per node (CPU time used/run time)

      della-l09g9: 12:20:28/12:29:29 (efficiency=98.8%)


  CPU memory usage per node - used/allocated

      della-l09g9: 5.9GB/50.0GB (5.9GB/50.0GB per core of 1)


  GPU utilization per node

      della-l09g9 (GPU 1): 0% *<--- GPU was not used.*


  GPU memory usage per node - maximum used/total

      della-l09g9 (GPU 1): 267.2MB/32.0GB (0.8%)

**Comment by SoodabehGhaffari** [comment]
Please note that the exit code is 1. I am also attaching my job script if
that helps.


#!/bin/bash

#SBATCH --job-name=anti-hyper         # create a short name for your job

#SBATCH --nodes=1                # node count

#SBATCH --ntasks=1               # total number of tasks across all nodes

#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded
tasks)

#SBATCH --mem-per-cpu=200G         # memory per cpu-core (4G is default)

#SBATCH --time=72:00:00          # total run time limit (HH:MM:SS)

#SBATCH --mail-type=begin        # send email when job begins

#SBATCH --mail-type=end          # send email when job ends

#SBATCH ***@***.***

#SBATCH -p cryoem

#SBATCH -o ./logs/anti-hyper.out

#SBATCH --gres=gpu:1             # number of gpus per node


module purge

module load anaconda3/2022.5

conda activate /scratch/gpfs/sg6615/CONDA/envs/chemprop

pip install -e .

chemprop_hyperopt --data_path ./data/df_antibiotic_train_val.csv
--dataset_type regression --num_iters 50 --hyperopt_checkpoint_dir
./antibiotics_hyperopt_checkpoint --config_save_path ./antibiotics_config
--search_parameter_keywords basic learning_rate batch_size ffn_num_layers
linked_hidden_size dropout depth --smiles_column SMILES_FROM_INCHI
--target_columns Antibiotic

**Comment by shihchengli** [comment]
It's hard to tell what's going on without any error messages. Could you try optimizing the hyperparameters with a smaller subset of the data to see if it still fails?
Chemprop does support GPU acceleration, could you run `conda list | grep 'torch\|cuda'` in your chemprop environment to see if the GPU-enabled version of PyTorch was installed appropriately?
As for your job script, you don't need to run `pip install -e .` every time you run the code.

**Comment by SoodabehGhaffari** [comment]
Thank you for the suggestions. I will try them and let you know.

Soodabeh

**Comment by SoodabehGhaffari** [comment]
Hello,
I am reaching out to ask about the GPU usage in chemprop. I checked the
GPU-enabled version of Pytorch with the command you provided and here are
the results: However, the jobstats shows that the job does not use GPU. The
hyperparameter optimization has been running for more than 3 days. Please
see below for more details.

Any suggestions for accelerating the hyperparameter optimization is greatly
appreciated.

Best Regards
Soodabeh




(chemprop) ***@***.*** antibiotic-config]$ conda list | grep
'torch\|cuda'

*cuda*-*cuda*rt               11.8.89                       0    nvidia

*cuda*-cupti                11.8.87                       0    nvidia

*cuda*-libraries            11.8.0                        0    nvidia

*cuda*-nvrtc                11.8.89                       0    nvidia

*cuda*-nvtx                 11.8.86                       0    nvidia

*cuda*-runtime              11.8.0                        0    nvidia

ffmpeg                    4.3                  hf484d3e_0    py*torch*

py*torch*                   2.0.0              py3.10_cpu_0    py*torch*

py*torch*-*cuda*              11.8                 h7e8668a_3    py*torch*

py*torch*-mutex             1.0                         cpu    py*torch*

*torch*                     2.0.0                    pypi_0    pypi

*torch*audio                2.0.0                    pypi_0    pypi

*torch*vision               0.15.0                   pypi_0    pypi








        Job ID: *46333978*

  NetID/Account: sg6615/molbio

       Job Name: anti-hyper

          State: RUNNING

          Nodes: 1

      CPU Cores: 4

     CPU Memory: 120GB (30GB per CPU-core)

           GPUs: 1

  QOS/Partition: della-cryoem/cryoem

        Cluster: della

     Start Time: Sun Mar 19, 2023 at 8:21 PM

       Run Time: 3-19:11:09 (in progress)

     Time Limit: 5-00:00:00


                              *Overall Utilization*

================================================================================

  CPU utilization  *[*|||||||||||||||||||||||||||||||||||||||||||||||98%*]*

  CPU memory usage *[*|||                                             6%*]*

  GPU utilization  *[*                                                *0%*
*]*

  GPU memory usage *[*                                                1%*]*

**Comment by shihchengli** [comment]
The PyTorch you installed is a CPU enabled version (`py*torch* 2.0.0 py3.10_cpu_0 py*torch*`). You should run `conda remove pytorch` and `conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia` to get a CUDA enabled PyTorch.

**Comment by SoodabehGhaffari** [comment]
Thank you very much!
