### ISSUE TITLE
Input args

### ISSUE THREAD

**Issue by jamel-mes** [chemprop/chemprop#38]
**--save_smiles_splits** doesn't work if used when specifying smiles and target columns using the new flags **--smiles_column** & **--target_columns** in combination with **--separate_val_path** & **--separate_test_path**. There is a smiles error that gets thrown during training. A minor bug, nothing serious :-)

**Comment by swansonk14** [comment]
Good catch @jamel-mes! I just made a fix: https://github.com/chemprop/chemprop/commit/3778d116b27173014f23b7598e93722f02485291
