### ISSUE TITLE
[QUESTION]: antibiotics prediction and checkpoints

### ISSUE THREAD

**Issue by TAYmit** [chemprop/chemprop#390]
Hello! 

I was reading the deep learning antibiotics paper. Hope you don't mind I ask some questions :)

I found antibiotics checkpoints from the google drive! thank you very much for sharing this. Is this the model that was used for predicting and discovering halicin?

Thank you!

**Comment by kevingreenman** [comment]
Thanks for your interest! The authors of the antibiotics paper are no longer actively involved with maintaining the Chemprop repo, but maybe one of them could answer your question if they see this @yangkevin2 @swansonk14 @wengong-jin

**Comment by TAYmit** [comment]
Thank you!
