### ISSUE TITLE
[QUESTION]: How to predict molecules starting from latent fingerprint, not SMILES?

### ISSUE THREAD

**Issue by MariBerry** [chemprop/chemprop#392]
Hello,
In my current project, I need to be able to predict molecule's activity by a trained Chemprop model.  The input, however, is not SMILES, but fingerprint, calculated, let's say in the mode of "MPN".
I try to do it like this:

```
import chemprop
from rdkit import Chem
from torch import Tensor
import torch
# load model
arguments = [
    '--test_path', '/dev/null',
    '--preds_path', '/dev/null',
    '--checkpoint_dir', '1913_checkpoints'
]

args = chemprop.args.PredictArgs().parse_args(arguments)

model_objects   = chemprop.train.load_model(args=args)

# create mol to predict
smiles =[[ 'Cc1cc(C)c(/C=C2\\C(=O)Nc3ccccc32)[nH]1']]

# calculate fingerprint
arguments = [
      '--test_path', '/dev/null',

    '--preds_path', '1913_preds_fingerprint.csv',
    '--checkpoint_dir', '1913_checkpoints',
    '--fingerprint_type', 'MPN'
]

args = chemprop.args.FingerprintArgs().parse_args(arguments)
preds_1913= chemprop.train.molecule_fingerprint.molecule_fingerprint(args=args, smiles=smiles)
 # np matrix to torch.tensor
preds_1913 = Tensor(preds_1913.squeeze(2)) # to torch.tensor

# pass fingerprint through last FFN of model
ffn = model_objects[2][0].ffn
ffn.eval()
out = ffn.forward(preds_1913) # tensor([[-0.3711]], grad_fn=<AddmmBackward0>) seems strange
```

But the result is different from this:

```
arguments = [
    '--test_path', '/dev/null',
    '--preds_path', '/dev/null',
    '--checkpoint_dir', '1913_checkpoints'
]

args = chemprop.args.PredictArgs().parse_args(arguments)

out = chemprop.train.make_predictions(args=args, smiles=smiles)  # [[6.133100757134966]] (seems  OK)
```

So, my question is: how to achieve the correct prediction, as is given by prediction from SMILES?

Thank you in advance,  [1913_checkpoints.zip](https://github.com/chemprop/chemprop/files/11507662/1913_checkpoints.zip)

**Comment by kevingreenman** [comment]
Thanks for your question. Could it be that in your first example (writing to fingerprint first, then predicting with the FFN), the output still needs to be unscaled? The unscaling isn't part of the forward pass of the FFN, but it would be done automatically by `make_predictions`.

**Comment by kevingreenman** [comment]
It's also worth mentioning that the first script will need to be modified for the release of version 1.6.0 because `self.ffn` is now `self.readout`, and the format of the fingerprints will change to accommodate the new atom/bond feature predictions.

**Comment by MariBerry** [comment]
> Thanks for your question. Could it be that in your first example (writing to fingerprint first, then predicting with the FFN), the output still needs to be unscaled? The unscaling isn't part of the forward pass of the FFN, but it would be done automatically by `make_predictions`.

No , I didnt unscale. Could you help me? how to do it? Or which line is it in make_predictions.py?

**Comment by kevingreenman** [comment]
I'm glad to hear that it worked! 

You typically always need to unscale at the end if you scaled at the beginning, unless you only care about rank ordering of the prediction values. Otherwise, the model predictions are unitless and can be unphysical (e.g. if you're predicting a property that can only be positive, but if your scaled predicted value is less than the mean then it will be negative). You also typically need to unscale before calculating error metrics like RMSE or MAE to have these in the expected units of your property of interest.

I'm closing this issue now, but feel free to reopen it if you have further questions.
