### ISSUE TITLE
[FEATURE]: Add a `CITATION.cff`

### ISSUE THREAD

**Issue by JacksonBurns** [chemprop/chemprop#394]
**Is your feature request related to a problem? Please describe.**
Citing chemprop requires getting to the papers manually and retrieving a citation file.

**Desired solution/workflow**
See the [GitHub docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files), we can add a `CITATION.cff` file that makes a "cite this repo" button appear on GitHub that will autodownload a bibtex or APA.

**Discussion**
Don't know which paper to put in said file, if there are multiple we will instead need to add .bib with multiple entires (like [this](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/main/CITATIONS.bib)).

**Comment by hesther** [comment]
I can add this, but would like to discuss first which references we want to use. I guess the original manuscript [Analyzing Learned Molecular Representations for Property Prediction](https://pubs.acs.org/doi/abs/10.1021/acs.jcim.9b00237) and the new manuscript [Chemprop: Machine Learning Package for Chemical Property Prediction](https://doi.org/10.26434/chemrxiv-2023-3zcfl) are a must-have. However, what about the smaller papers implementing specialty features, e.g. spectra or reactions?

**Comment by kevingreenman** [comment]
That's a good question. Maybe an alternative would be to list the main two papers in the bib file, and add the bibtex for the others to the README somewhere? Or I guess it doesn't hurt to include all of them in the bib file, people can always take just the ones they need from there.

**Comment by JacksonBurns** [comment]
I am opening a PR to address this and will reference this issue.
