### ISSUE TITLE
[QUESTION]: Handling missing values in target variables

### ISSUE THREAD

**Issue by jamshaidsohail5** [chemprop/chemprop#404]
Hi. I hope this message finds you in the best of health. I wanted to use chemprop for multi-task learning. I am thinking of utilizing the below dataset for this purpose. 

https://github.com/lenselinkbart/SAMPL7_paper/blob/main/data/full_dataset.csv

It contains some values in the target variables. How chemprop would be handling that or do I have to do something custom my side ?

Best Wishes
Jamshaid Sohail

**Comment by kevingreenman** [comment]
https://github.com/chemprop/chemprop#missing-target-values

**Comment by kevingreenman** [comment]
Feel free to re-open the issue and ask for clarification if you have more questions that aren't answered in the README section linked above.
