### ISSUE TITLE
[FEATURE]: Extend MoleculeDatapoint to use SMILES and RDKit Molecules

### ISSUE THREAD

**Issue by JenniferHem** [chemprop/chemprop#407]
In our work we often pre-process molecules (e.g. standardisation, filtering etc) and then already have an RDKit molecule. To avoid multiple conversions between SMILES and the RDKit Molecule Format it would be good to have a kind of "Molecule Datapoint" which uses RDKit as an input Format. 

Looking at the code there could either be a parameter "mol_type" in the existing MoleculeDatapoint which then sets either the mol or the smiles depending on the type, or maybe also two classes like a MoleculeDatapoint and a SmilesDatapoint.

Currently I cannot think about other input formats which might be relevant (at least for our work) but might be interesting to brainstorm if any other format would be relevant for other users and could also be interesting for incorporation.

**Comment by kevingreenman** [comment]
Thanks for the suggestion! We can discuss whether this makes sense to include. @davidegraff do you have thoughts on whether this could become part of v2?

**Comment by JenniferHem** [comment]
@kevingreenman @davidegraff any updates or ideas here?

**Comment by davidegraff** [comment]
`MoleculeDatapoint`s were made `Mol`-centric with #441
