### ISSUE TITLE
[BUG]:  missing packages in v2 `setup.cfg`

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#408]
As reported by an MLPDS member, three packages are missing from the [`setup.cfg` in `dev/v2`](https://github.com/chemprop/chemprop/blob/v2/dev/setup.cfg):
- typed-argument-parser
- tensorboardX
- hyperopt

**Comment by davidegraff** [comment]
these are being removed in a forthcoming PR, right?

**Comment by kevingreenman** [comment]
The `setup.cfg` file should be removed by #433. As for the packages, I think `typed-argument-parser` is definitely being removed, `tensorboardX` I'm not sure about, and `hyperopt` will definitely stay (TBD whether we will keep it initially or add it back in once we add HPO functionality). I'll close this issue, and we can continue any additional discussion on this in #433
