### ISSUE TITLE
[QUESTION]: Getting the almost same test MAE for the different tasks on --show_individual_scores in multi-task learning ?

### ISSUE THREAD

**Issue by jamshaidsohail5** [chemprop/chemprop#411]
Hi. I hope this message finds you in the best of health. I have trained a multi-task learning model on 4 properties of QM9 dataset which are highly correlated with each other (correlation above 90%). The one thing I observed is that I am getting the test MAE for the different tasks in the test dataset to be the same. For example, if I share one fold test MAE for the different tasks, I can give you the below scores. The columns (U0, U, G, H) are the different properties which are highly correlated with each other and people have been training a model together as well on these. 

Property | U0  | U | G | H 
--- | --- | --- | --- |--- 
Fold 1 | 1.22  | 1.22  | 1.22  | 1.22  
Fold 2 |  1.55 |  1.55 |  1.56 | 1.55 

What could be the reason behind these, I just want to make sure that I might not be doing something wrong? The thing to be repeated is that these properties are highly correlated with each.

**Comment by kevingreenman** [comment]
If targets are highly correlated and have similar magnitudes, it's not surprising that the MAEs would be similar. If you look at the summary statistics for these 4 properties, they're almost identical (see below).

```
$ wget https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/qm9.csv
```

```
import pandas as pd
df = pd.read_csv("qm9.csv")
df[['u0', 'u298', 'g298', 'h298']].describe()
```

```
                  u0           u298           g298           h298
count  133885.000000  133885.000000  133885.000000  133885.000000
mean     -411.543985    -411.535513    -411.577397    -411.534569
std        40.060230      40.060012      40.060741      40.060012
min      -714.568061    -714.560153    -714.602138    -714.559209
25%      -437.913936    -437.905942    -437.947682    -437.904997
50%      -417.864758    -417.857351    -417.895731    -417.856407
75%      -387.049166    -387.039746    -387.083279    -387.038802
max       -40.478930     -40.476062     -40.498597     -40.475117
```
