### ISSUE TITLE
[QUESTION]: environment installation error with gunicorn

### ISSUE THREAD

**Issue by Costin67** [chemprop/chemprop#412]
I am trying to install the chemprop software, but at the creating environment step is giving an error message: ResolvePackageNotFound: - gunicorn[version='>=20.0.4'] though I installed gunicorn. WHat can I do in this case?

**Comment by shihchengli** [comment]
Could you please try updating your conda by running `conda update conda` and then attempt to install this package again to see if it works? Alternatively, you can install this package using `pip install "gunicorn>=20.0.4"`.

**Comment by cjmcgill** [comment]
I'll add that Gunicorn is only necessary if you want to use the web browser interface for chemprop. If you want to run it from command line or Python, you can remove that line from your environment file.

**Comment by kevingreenman** [comment]
As a side note, we will soon be dropping support of the web interface when we transition to version 2.0 of chemprop.
