### ISSUE TITLE
[BUG]: Dirichlet Uncertainty

### ISSUE THREAD

**Issue by muammar** [chemprop/chemprop#413]
**Describe the bug**
If training with `--uncertainty_method dirichlet`, the MPNN outputs `alphas` of a Dirichlet distribution. At prediction time, `u` should be returned with the class probability scores and computed as `u = K / S` where `K` is the number of classes and `S` is the Dirichlet strength. Currently, I use the `--uncertainty_method classification`,  but this returns a prediction with `_classification_uncal_confidence` appended, and that value is virtually the same as the probability score:

```
SMILES,measured log(solubility:mol/L),measured log(solubility:mol/L)_classification_uncal_confidence
CC(=C)C=C,0.9371881484985352,0.9371881484985352
CC(C)=CCCC(O)(C)C=C,0.884028971195221,0.884028971
```

I train with this command: 

```
chemprop_train --data_path ../01_all_dp_80_percent_train.csv 
    --dataset_type classification --save_dir 00_all_datapoints_dedup_random_split.train.prc-auc 
    --metric prc-auc --split_type random --split_sizes 0.8 0.1 0.1 --gpu 0 --dropout 0 
    --ensemble_size 1 --num_folds 1 --hidden_size 300 --ffn_hidden_size 300  
    --smiles_column SMILES --loss_function dirichlet --evidential_regularization 1
```

And predict with this: 

```
chemprop_predict --test_path ../01_all_dp_20_percent_test.csv 
    --checkpoint_dir 00_all_datapoints_dedup_random_split.train.auc 
    --preds_path 00_all_datapoints_dedup_random_split.test.auc.csv --gpu 0  
    --smiles_column SMILES --uncertainty_method classification --smiles_column SMILES
```

Am I missing something?

**Expected behavior**
Return `u = K / S` instead of `_classification_uncal_confidence`. 

See: http://arxiv.org/abs/1806.01768

**Comment by cjmcgill** [comment]
Hi @muammar, this sounds like we may have implemented Dirichlet incompletely. I'll take a look at it. Also, thank you for the reference link.

**Comment by muammar** [comment]
> Hi @muammar, this sounds like we may have implemented Dirichlet incompletely. I'll take a look at it. Also, thank you for the reference link.

Thank you very much for your fast reply, @cjmcgill! In the interim, we are trying to hack this from our side. I'll let you know how that goes, and if the fix looks good, we will submit a PR. 

I look forward to hearing from you—no worries about the reference link. 

Best,

**Comment by muammar** [comment]
We have some work ready about this, but I suspect it must be incomplete. Do you think we should submit a PR and work it from there?

**Comment by cjmcgill** [comment]
I think that would be great, even if incomplete. We can keep working on it together from there. Thanks!

**Comment by muammar** [comment]
> I think that would be great, even if incomplete. We can keep working on it together from there. Thanks!

 I just pushed the implementation that I have been using for classification in single-task mode.

**Comment by cjmcgill** [comment]
Hi @muammar thanks for posting that PR. I think I understand your goal better now. I'm going to keep discussion of the theory and strategy here and comments on the code over in the PR.

As you say, the output of the model is the alphas for each option. In classification, just for the [0,1] options but for multiclass, it's for any of the n options. The overall prediction from Chemprop is the expected value for class 1, from equation 2 in your referenced paper
$$p_1  = \alpha_1/S$$

I don't think I understood before what you wanted to get out of the prediction function. I had thought you were asking for convert the alphas back to class beliefs, yielding: $b_0$, $b_1$, and $u$ as three outputs for binary classification. Which would have been a challenge as set up now. But thankfully I think I was wrong there and it's going to be an easier implementation.

If I'm understanding correctly now, you are good to keep $p_1$ as the uncalibrated prediction of the model but you want the $u$ value as the uncertainty column when `--uncertainty_type dirichlet` is specified.

**Comment by cjmcgill** [comment]
@muammar do you have any insight as to whether special procedures need to be taken in terms of ensembling?

I can average together the $p_k$ from each submodel to get an ensemble $p_k$. And I can average $u$ from each submodel to get an ensemble $u$. But I think that will be mathematically distinct from if I averaged together the $\alpha_k$ from each submodel and then used those $\alpha_k$ to calculate and ensemble $p_k$ and $u$.

Either approach seems potentially justifiable. The former would be much simpler to execute and would avoid needing to build in custom ensembling methods into training functions as well, so I would lean that way. But if you know a literature justification for the latter or another method altogether I'd be interested to take a look.

**Comment by cjmcgill** [comment]
Hi @muammar I've posted a PR #423 that builds on what you did in #421 and adds support for multitask and atom/bond targets along with some other minor additions.
