### ISSUE TITLE
Is hyperparameter optimization useful if we would like to use pretraining model to train a new model 

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#414]
Hello,
I was wondering if hyperparameter optimization useful if we would like to use pretraining model to train a new model.

Thank you

**Comment by kevingreenman** [comment]
It's hard to predict _a priori_ whether HPO will help a little or a lot in a given scenario. It's even less clear what the effect will be if pretraining / transfer learning is involved. The best thing to do is just to test it empirically.
