### ISSUE TITLE
[BUG]: AttributeError: module 'scipy.stats' has no attribute 'gibrat'

### ISSUE THREAD

**Issue by shihchengli** [chemprop/chemprop#428]
**Describe the bug**
As of version 1.9.0, [gilbrat](https://docs.scipy.org/doc/scipy-1.10.0/reference/generated/scipy.stats.gilbrat.html#scipy.stats.gilbrat)  has been deprecated, and it is recommended to use [gibrat](https://docs.scipy.org/doc/scipy-1.10.0/reference/generated/scipy.stats.gibrat.html#scipy.stats.gibrat) instead. `gilbrat` is actually a misspelling of the correct name for the `gibrat`, and it will be completely removed in [SciPy 1.11](https://docs.scipy.org/doc/scipy/release/1.11.0-notes.html#expired-deprecations). 

The package `descriptastorus` recently addressed this issue with the attribute naming convention `gibrat`. However, it's worth noting that an older version of scipy (scipy>=1.4.1) can still be installed in Chemprop, while `descriptastorus` requires scipy>=1.9.0.

**Comment by kevingreenman** [comment]
I suggest we update our `scipy` dependency before we release chemprop v1.7.0, as long as the dependency update doesn't break anything.

**Comment by avas27JTG** [comment]
I am currently encountering the same issue regarding the initiation of the Gunicorn server within the Docker container. As a provisional solution, I have made an adjustment in the `environment.yml` file, specifically modifying `scipy>=1.4.1` to `scipy>=1.5.2`, which has proven to be effective in resolving the problem.

**Comment by kevingreenman** [comment]
Fixed by #431

**Comment by avas27JTG** [comment]
> @avas27JTG does #431 solve your issue as well? If not, you can open a separate issue (or preferably a PR with a fix similar to #431). As a side note, we will soon be dropping support of the web interface when we transition to version 2.0 of chemprop.

Thanks for the update I'll try with #431 fixes and update if it works for me, otherwise I'll create a separate issue and a PR with the fixes.

**Comment by avas27JTG** [comment]
> > @avas27JTG does #431 solve your issue as well? If not, you can open a separate issue (or preferably a PR with a fix similar to #431). As a side note, we will soon be dropping support of the web interface when we transition to version 2.0 of chemprop.
> 
> Thanks for the update I'll try with #431 fixes and update if it works for me, otherwise I'll create a separate issue and a PR with the fixes.

@kevingreenman #431 didn't work for me so created a new issue https://github.com/chemprop/chemprop/issues/435 and also submitted a PR for this #436.
