### ISSUE TITLE
[QUESTION]: How to preload a model for prediction with dropout uncertainty

### ISSUE THREAD

**Issue by elisammz** [chemprop/chemprop#430]
**What are you trying to do?**
I want to preload a model which args contain the flags for Uncertainty Estimation by the dropout method.

**Previous attempts**

```
arguments = [
        '--test_path', '/dev/null',
        '--preds_path', '/dev/null',
        '--checkpoint_dir', 'some_model_dir',
        '--uncertainty_method', 'dropout',
        '--uncertainty_dropout_p', '0.5',
        '--dropout_sampling_size', '5'     
    ]

args = chemprop.args.PredictArgs().parse_args(arguments)
model_objects = chemprop.train.load_model(args=args)

list_of_smiles = [["O=C1CCSCC1"], ["S=C=S"]]
preds = chemprop.train.make_predictions(args=args, smiles=list_of_smiles, return_uncertainty=True, model_objects=model_objects)
```

**Output**

The error:

```
[/usr/local/lib/python3.10/dist-packages/chemprop/uncertainty/uncertainty_predictor.py](https://localhost:8080/#) in calculate_predictions(self)
   1054 
   1055     def calculate_predictions(self):
-> 1056         model = next(self.models)
   1057         (
   1058             scaler,

TypeError: 'list' object is not an iterator
```

**Other attempts**
This runs fine (without `model_objects`):
`preds = chemprop.train.make_predictions(args=args, smiles=list_of_smiles, return_uncertainty=True)`

Output example:
```
Elapsed time = 0:00:02
([[2.3786209190694754], [6.0510969486492625]],
 [[56.40295818320961], [15.312992857668526]])
```

**Comment by kevingreenman** [comment]
@elisammz can you try replacing
```
model_objects = chemprop.train.load_model(args=args)
```
with
```
model_objects = chemprop.train.load_model(args=args, generator=True)
```
in your code?

I believe that is the source of your error. `make_predictions` expects a generator, but `load_model` returns a list by default. 

In the `make_predictions` code [here](https://github.com/chemprop/chemprop/blob/1f367d55d1bac14dd6b9e0cd5746574fcfab9a59/chemprop/train/make_predictions.py#L375-L392), you can see that if you don't provide `model_objects` as an argument, it will load the models (with `generator=True`) for you, but since you are supplying `model_objects`, it assumes you're giving it a generator.

**Comment by elisammz** [comment]
Hi @kevingreenman 

Thank you very much for your suggestion! I appreciated it. I have tested the suggested line and I got the following error:

```
arguments = [
        '--test_path', '/dev/null',
        '--preds_path', '/dev/null',
        '--checkpoint_dir', 'models/2301_Nu-smiles-test-chk',
        '--uncertainty_method', 'dropout',
        '--uncertainty_dropout_p', '0.5',
        '--dropout_sampling_size', '5'     
    ]

args = chemprop.args.PredictArgs().parse_args(arguments)
model_objects = chemprop.train.load_model(args=args, generator=True)

list_of_smiles = [["O=C1CCSCC1"], ["S=C=S"]]
preds = chemprop.train.make_predictions(args=args, smiles=list_of_smiles, return_uncertainty=True, model_objects=model_objects)
```

The error;
```
RuntimeError                              Traceback (most recent call last)
[<ipython-input-15-ddda8d6889ed>](https://localhost:8080/#) in <cell line: 11>()
      9 
     10 args = chemprop.args.PredictArgs().parse_args(arguments)
---> 11 model_objects = chemprop.train.load_model(args=args, generator=True)

[/usr/local/lib/python3.10/dist-packages/torch/serialization.py](https://localhost:8080/#) in __init__(self, name_or_buffer)
    281 class _open_zipfile_reader(_opener):
    282     def __init__(self, name_or_buffer) -> None:
--> 283         super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
    284 
    285 

RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

Any other suggestion?

**Comment by elisammz** [comment]
Hi @kevingreenman

Thank you very much for your suggestion. It works perfectly! 
Now, I can get the prediction's uncertainty with a preloaded model.

Cheers!

**Comment by elisammz** [comment]
I will close this question.

**Comment by elisammz** [comment]
Sorry, reopening this issue.

**What are you trying to do?**
Load a model once and predict for several lists of smiles returning **Uncertainty Estimation**

**Previous attempts**
```
arguments = [
        '--test_path', '/dev/null',
        '--preds_path', '/dev/null',
        '--checkpoint_dir', 'some_model_dir',
        '--uncertainty_method', 'dropout'
    ]
    
args = chemprop.args.PredictArgs().parse_args(arguments)

model_objects = chemprop.train.load_model(args=args, generator=True)

list_of_smiles = [['CCCC'], ['CCCCC'], ['COCC']]
preds = chemprop.train.make_predictions(args=nu_args, smiles=list_of_smiles, model_objects=nu_model_objects, return_uncertainty=True)

list_of_smiles_2 = [['O=C1CCSCC1'], ['S=C=S']]
preds_2 = chemprop.train.make_predictions(args=nu_args, smiles=list_of_smiles_2, model_objects=nu_model_objects, return_uncertainty=True)
```
The output and the error:
```
Loading training args
Setting molecule featurization parameters to default.
Loading data
Validating SMILES
Test size = 3
Loading pretrained parameter "encoder.encoder.0.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.0.W_i.weight".
Loading pretrained parameter "encoder.encoder.0.W_h.weight".
Loading pretrained parameter "encoder.encoder.0.W_o.weight".
Loading pretrained parameter "encoder.encoder.0.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
Loading pretrained parameter "ffn.7.weight".
Loading pretrained parameter "ffn.7.bias".
Loading pretrained parameter "ffn.10.weight".
Loading pretrained parameter "ffn.10.bias".
                                             
Saving predictions to [/dev/null](https://file+.vscode-resource.vscode-cdn.net/dev/null)
Elapsed time = 0:08:36
Setting molecule featurization parameters to default.
Loading data
Validating SMILES
Test size = 2
```
```
File [~/opt/anaconda3/envs/chemprop/lib/python3.11/site-packages/chemprop/train/make_predictions.py:453](https://file+.vscode-resource.vscode-cdn.net/Users/elisa_mi-6/ws/IMS-chemprop/app-backend/api/~/opt/anaconda3/envs/chemprop/lib/python3.11/site-packages/chemprop/train/make_predictions.py:453), in make_predictions(args, smiles, model_objects, calibrator, return_invalid_smiles, return_index_dict, return_uncertainty)
    451     unc = [None] * len(full_data)
    452 else:
--> 453     preds, unc = predict_and_save(
    454         args=args,
    455         train_args=train_args,
    456         test_data=test_data,
    457         task_names=task_names,
    458         num_tasks=num_tasks,
    459         test_data_loader=test_data_loader,
...
    681         or atom_descriptor_scaler is not None
    682         or bond_feature_scaler is not None
    683     ):
```

The prediction and the uncertainty estimation is successful for the first list_of_smiles, but it fails for the list_of_smiles_2. What could be the reason of this?
Thank you for the support ^^

**Comment by kevingreenman** [comment]
Is that the full error traceback? It seems weird that it would end with the `predict_and_save` call. I think the `StopIteration` error suggests that the error is related to the `model = next(self.models)` line [here](https://github.com/chemprop/chemprop/blob/f3d1bff19a6e1b03d28e9cfabdf4c80dd8c67382/chemprop/uncertainty/uncertainty_predictor.py#L1056). 

Can you confirm that the error goes away if you run 
```
model_objects = chemprop.train.load_model(args=args, generator=True)
```
again before the 2nd call of `chemprop.train.make_predictions`?

I did some digging and haven't found a good way to reset a generator in Python without just creating it again, so I think you may have to run `load_model` every time you want to make a prediction. Note that this is only true for models with dropout uncertainty (not models with no uncertainty or other types of uncertainty), because only the Dropout method uses `next()` on a generator of model checkpoints.

I recognize this might pose a problem if you're trying to make a lot of sets of predictions and don't want to have to keep loading the model every time. This was the reason we implemented model preloading in #200 (this is also the PR that introduced the generator functionality into `load_model`), but dropout uncertainty wasn't part of the codebase at the time, so we didn't foresee this issue. 

How set are you on using dropout as opposed to other uncertainty methods? In your workflow, would you be loading the model so many times that the loading time would add up and be a significant overhead? We could consider changing the code to avoid this problem.

**Comment by elisammz** [comment]
@kevingreenman  Thank you for that quick reply and the clear explanation!

> Is that the full error traceback? It seems weird that it would end with the predict_and_save call. I think the StopIteration error suggests that the error is related to the model = next(self.models) line [here](https://github.com/chemprop/chemprop/blob/f3d1bff19a6e1b03d28e9cfabdf4c80dd8c67382/chemprop/uncertainty/uncertainty_predictor.py#L1056).

Yes, indeed. Here is the proof.
```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
Cell In[14], line 16
     13 preds = chemprop.train.make_predictions(args=nu_args, smiles=list_of_smiles, model_objects=nu_model_objects, return_uncertainty=True)
     15 list_of_smiles_2 = [['O=C1CCSCC1'], ['S=C=S']]
---> 16 preds_2 = chemprop.train.make_predictions(args=nu_args, smiles=list_of_smiles_2, model_objects=nu_model_objects)
....
File [~/opt/anaconda3/envs/chemprop/lib/python3.11/site-packages/chemprop/uncertainty/uncertainty_predictor.py:50](https://file+.vscode-resource.vscode-cdn.net/Users/elisa_mi-6/ws/IMS-chemprop/app-backend/api/~/opt/anaconda3/envs/chemprop/lib/python3.11/site-packages/chemprop/uncertainty/uncertainty_predictor.py:50), in UncertaintyPredictor.__init__(self, test_data, test_data_loader, models, scalers, num_models, dataset_type, loss_function, uncertainty_dropout_p, dropout_sampling_size, individual_ensemble_predictions, spectra_phase_mask)
     48 self.raise_argument_errors()
     49 self.test_data_loader = test_data_loader
---> 50 self.calculate_predictions()

File [~/opt/anaconda3/envs/chemprop/lib/python3.11/site-packages/chemprop/uncertainty/uncertainty_predictor.py:672](https://file+.vscode-resource.vscode-cdn.net/Users/elisa_mi-6/ws/IMS-chemprop/app-backend/api/~/opt/anaconda3/envs/chemprop/lib/python3.11/site-packages/chemprop/uncertainty/uncertainty_predictor.py:672), in DropoutPredictor.calculate_predictions(self)
    671 def calculate_predictions(self):
--> 672     model = next(self.models)
    673     (
    674         scaler,
    675         features_scaler,
    676         atom_descriptor_scaler,
    677         bond_feature_scaler,
    678     ) = next(self.scalers)
    679     if (
    680         features_scaler is not None
    681         or atom_descriptor_scaler is not None
    682         or bond_feature_scaler is not None
    683     ):

StopIteration:
```

> Can you confirm that the error goes away if you run `model_objects = chemprop.train.load_model(args=args, generator=True)` again before the 2nd call of chemprop.train.make_predictions?

Yes, this works:
```
arguments = [
        '--test_path', '/dev/null',
        '--preds_path', '/dev/null',
        '--checkpoint_dir', 'some_model_dir',
        '--uncertainty_method', 'dropout',
    ]
    
args = chemprop.args.PredictArgs().parse_args(arguments)

model_objects = chemprop.train.load_model(args=args, generator=True)

list_of_smiles = [['CCCC'], ['CCCCC'], ['COCC']]
preds = chemprop.train.make_predictions(args=args, smiles=list_of_smiles, model_objects=model_objects, return_uncertainty=True)

list_of_smiles_2 = [['O=C1CCSCC1'], ['S=C=S']]
model_objects = chemprop.train.load_model(args=args, generator=True)
preds_2 = chemprop.train.make_predictions(args=args, smiles=list_of_smiles_2, model_objects=model_objects, return_uncertainty=True)
```

> How set are you on using dropout as opposed to other uncertainty methods?

Unfortunately, only the dropout method is applicable to my single model. On the bright side, loading the model many times is not costing much compared to the prediction itself (at least in my case). Thus, I will load the model prior to each prediction. I guess it could be nice for those who really need to preload the model and declare the uncertainty estimation by dropout.

**Comment by kevingreenman** [comment]
We are closing all enhancement requests for chemprop v1.x, as we will not have time to implement these before the upcoming release of [chemprop v2.0](https://github.com/chemprop/chemprop/issues/517). If there is still interest in this enhancement, please open a new issue after the release of v2.0.
