### ISSUE TITLE
[QUESTION]: 3D structural Feature

### ISSUE THREAD

**Issue by suleechem** [chemprop/chemprop#434]
Thanks to the powerful tools of ChemProp, I could solve my problems predicting S1-T1 energy gap. 
But, I want to more improve accuracy. 
Now I guess the I should include 3D structural information (especially angles and dihedral angles of molecules) as molecular feature. 

So I would like to know if there is any way to include 3D structural information.

Thank you very much.

**Comment by kevingreenman** [comment]
Unfortunately there is no way to provide 3D structural information to Chemprop. There are many other packages available for this (e.g. [NeuralForceField](https://github.com/learningmatter-mit/NeuralForceField), [SchNet](https://github.com/atomistic-machine-learning/schnetpack), [DimeNet](https://github.com/gasteigerjo/dimenet), etc.), but that is not the focus of Chemprop. Note that 3D structural information doesn't always improve property predictions, but it's worth trying if you have reason to believe that the property you're predicting depends on the geometry of a conformer or an ensemble of conformers (see this [paper](https://arxiv.org/abs/2012.08452)).

I'm closing the issue for now, but feel free to re-open it if you'd like to continue the discussion.
