### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by SOH9797** [chemprop/chemprop#44]
Unable to install on Windows, as far as I can see, this is due to the web interface packages not being available for Windows. Is it possible to make the web interface an optional 'add-on' package, the core of ChemProp would then be installable on windows machines?

**Comment by daverdude** [comment]
I have been running it on macOS, but can confirm that I have been unable to get it up and running on Windows and on Fedora.

**Comment by swansonk14** [comment]
Thank you for bringing this to our attention @SOH9797 and @daverdude! It looks like it's specifically a problem with `gunicorn`, which is only available on UNIX systems. I've removed `gunicorn` from the requirements and added instructions for manually installing gunicorn on the README for those who do want to use it. You can see the changes here: https://github.com/chemprop/chemprop/commit/7f7b6d82ef51696b72be40ef35adecd5bcff3770
