### ISSUE TITLE
[FEATURE]: Option to turn off feature source validation during prediction

### ISSUE THREAD

**Issue by swansonk14** [chemprop/chemprop#450]
I frequently train models using `features_path` and then want to make predictions on a set of molecules using `features_generators`.  However, this is not possible due to the following lines:

https://github.com/chemprop/chemprop/blob/f3d1bff19a6e1b03d28e9cfabdf4c80dd8c67382/chemprop/utils.py#L829-L838

It looks like this error can be controlled by the `validate_feature_sources` parameter to the `update_prediction_args` function, but this parameter is not exposed to the user via the `chemprop_predict` command line.

It would be great if this parameter could be exposed so that users can turn off this error if they want to use `features_generators` with a model trained using `features_path` (or vice versa).

**Comment by kevingreenman** [comment]
We are closing all enhancement requests for chemprop v1.x, as we will not have time to implement these before the upcoming release of [chemprop v2.0](https://github.com/chemprop/chemprop/issues/517). If there is still interest in this enhancement, please open a new issue after the release of v2.0.
