### ISSUE TITLE
[QUESTION]: optimizing GPU usage

### ISSUE THREAD

**Issue by tmcf22** [chemprop/chemprop#457]
First of all, this is a fantastic program! I am a chemist, and I never thought I would be able to get into machine learning, but you guys made that possible. Thank you!

**What are you trying to do?**
I am trying to optimize the use of my GPU for running hyperparameter optimizations, training, and predicting. I have successfully installed chemprop with cuda, cudnn, pytorch, etc. and the GPU is used, but maxes out at about a 20% work load. Is there a way to further speed up the calculations with GPU optimization? For example, can I load the sample data onto the GPU directly? Are there any example scripts for that?

**Previous attempts**
I have been reading a book about PyTorch, but I'm totally new at it and don't know what I'm doing. I haven't tried anything worth reporting

I would appreciate any help, even if it is just, "Your GPU is working just fine, sir. No other optimizations are possible." Lastly, are you guys able to implement the code/instructions for running Chemprop with PyTorch Geometric? The acceleration reported there is exactly what I am interested in implementing. Many thanks!

**Comment by JacksonBurns** [comment]
Hi @tmcf22 glad to hear `chemprop` has helped you out!

You might want to try adding `--cache_cutoff inf` to your command line arguments - by default, `chemprop` will save 10,000 molecules in memory at any time, but this will allow it to keep all molecules in memory. This will increase the memory utilization on your GPU (the data is already there). That's about it for improvements, though - once the entire dataset is on the GPU and the entire network is there as well, we are maximizing our use of it. Let me know if this helps!

For the PyTorch geometric accelerations you mention - could you link to the features/documentation you are looking to use?

**Comment by JacksonBurns** [comment]
Also, here is a link to the `chemprop` [caching documentation](https://chemprop.readthedocs.io/en/latest/tutorial.html?highlight=cache#caching). It also suggests turning off caching and generating molecular graphs in parallel, but you might want to try both! Speed vs. utilization don't always go hand-in-hand.

**Comment by tmcf22** [comment]
Thank you for your reply Jackson! I was already using cache_cutoff inf, but
it is good to know that it indeed helps with the speed. Some of the
hyperparameter optimizations I am running take 2 days...This is not the end
of the world and I am fine with that knowing that I am indeed maximizing
the GPU potential. Thanks for your reply Jackson, and well done on such a
fantastic program!

My best,

Thomas

**Comment by tmcf22** [comment]
I almost forgot, here is the link to the PyTorch Geometric/chemprop site:

https://github.com/itakigawa/pyg_chemprop

**Comment by JacksonBurns** [comment]
Thanks for sharing @tmcf22. We actually had not seen this before and are excited to roll in some of these speedups into `chemprop`. We are currently developing `chemprop` v2.0 and are now discussing how best to include these improvements. Thanks for sharing this!

I will go ahead and close this issue since the original question has been answered, and the timescale for the new release of `chemprop` is forthcoming. If anything else comes up, please feel to re-open this issue, or open a new one as you use `chemprop`!

**Comment by tmcf22** [comment]
Thank you very much! Good luck with all your future  endeavors and I will
be watching eagerly for any speedups that you guys are able to implement.

My best,

Thomas

**Comment by tmcf22** [comment]
This YouTube link by the same author as the github link I sent might help
too.

https://www.youtube.com/watch?v=nez755i1oFE

How long until you think chemprop version 2 comes out? Just curious! Thanks!

**Comment by tmcf22** [comment]
Hey Jackson,

Thank you for your help before. I have one quick (silly) question that I am
not sure is worth posting publicly.

Will the resulting ML model be different if the SMILES input is canonical
for aromatics? Not in lowercase... I appreciate it!

Thomas

**Comment by JacksonBurns** [comment]
Hi again,

Not a silly question at all. ChemProp uses RDKit to load its molecule from SMILES (see https://github.com/chemprop/chemprop/blob/master/chemprop/rdkit.py), so any valid form of a SMILES string for a molecule should turn out the same way.

As far as a release timeline, the initial release of v2.0 is in before the end of the year, and the release which would contain the pytorch geometric speedups will follow after that.
