### ISSUE TITLE
[FEATURE]: batch selection for active learning

### ISSUE THREAD

**Issue by GLPG-GT** [chemprop/chemprop#466]
This paper:

https://www.biorxiv.org/content/10.1101/2023.07.26.550653v2

presents a (new?) method to select batches of samples for active learning, supposedly more efficiently than by random selection or by picking samples with high epistemic uncertainty.

Several approximations are introduced to estimate the required information, and yet more approximations are introduced at the optimization stage.  
Given that chemprop, in 'evidential' mode, learns higher-order distributions of the model's parameters, is it possible that it already has the information needed to estimate the covariance the paper is talking about?  
And more in general, do you know of any existing work regarding using chemprop in an active-learning context?

**Comment by kevingreenman** [comment]
I'm not sure about using the output of evidential uncertainty, but the paper mentions using Monte Carlo dropout to estimate the epistemic covariance, and dropout is implemented in chemprop. 

Yes, chemprop has certainty been used in active learning contexts, e.g. [Accelerating high-throughput virtual screening through molecular pool-based active learning (2021)](https://pubs.rsc.org/en/content/articlehtml/2021/sc/d0sc06805e)
