### ISSUE TITLE
[Feature Request] Add --ignore_columns

### ISSUE THREAD

**Issue by Miserlou** [chemprop/chemprop#47]
I have some chemical names in my datasets. It'd be far more convenient for me if I could simply ignore that columns rather than needing to explicitly list all of the columns that I want to include.

I imagine the implementation is extremely simple, if `--ignore_columns name` is supplied, then the targets are all columns, or `--target_columns`, if supplied, minus `name`.

If you agree to this feature, I can send a PR.

**Comment by swansonk14** [comment]
Hi @Miserlou, that's a great suggestion! I actually found myself needing this so I went ahead and implemented it: https://github.com/chemprop/chemprop/commit/8c617872668a7626294eb516992d0e1b2c4e2284. I hope this works as you want.
