### ISSUE TITLE
[FEATURE]: v2 polymer functionality

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#476]
Integrate polymer functionality from [Coley group's work](https://github.com/coleygroup/polymer-chemprop)

**Comment by davidegraff** [comment]
some brief notes (excuse the mixing of atom/node and bond/edge):
- the primary difference of polymeric message passing is the introduction of atom and bond weights into the `BatchMolGraph` ([here](https://github.com/coleygroup/polymer-chemprop/blob/ae1ae1a86776cbf0860fde5d4823938acd0a794d/chemprop/models/mpn.py#L81C33-L81C33))
- during edge-based message passing, a message is calculated as normal and then multiplied by its weight (`w_bonds`). That is, message aggregation becomes a fixed, weighted sum over messages (i.e., "static attention")
- during graph aggregation, two things happen:
  1. a similar concept is applied to each node (`w_atoms`) in the graph (i.e., a fixed, weighted {sum, mean})
  2. the graph-level representation is multiplied by its "degree_of_polymerization" (`degree_of_polym`)
- we obtain these attributes via a new featurization scheme (main code block is [here](https://github.com/coleygroup/polymer-chemprop/blob/ae1ae1a86776cbf0860fde5d4823938acd0a794d/chemprop/features/featurization.py#L489-L637)). There's a lot going on here, and I don't really understand it myself.
- the new featurization scheme also relies on the "polymer rules" (`list[str]`) information being attached to a given polymer. These rules are parsed to obtain (i) the edge weights between repeating monomer units and (ii) the degree of polymerization

**Comment by KnathanM** [comment]
At the MLPDS meeting today, we mentioned that we don't have current plans to work on polymer functionality in v2 and no one spoke up in favor polymer functionality. I'd be in favor of closing this issue as we don't have anyone to work on it for now.

**Comment by JacksonBurns** [comment]
Seconded
