### ISSUE TITLE
Hang when prediction data > available RAM

### ISSUE THREAD

**Issue by Miserlou** [chemprop/chemprop#48]
I've noticed that chemprop will hang once all available RAM is depleted, which happens if the prediction dataset is larger than the available RAM on the system.

For prediction purposes, is it necessary to load all of the test data into RAM at once? Can it be read as needed instead?

**Comment by Miserlou** [comment]
From experimentation, I've found that this is actually true even for sizes far less than the available RAM. Starting with a 60GB file of the whole ZINC15 (on a machine with 32GB RAM), I keep splitting the file until chemprop can handle it without freezing/crashing) - the first first file to give a successful result is 30_MB_.

When you did the Zinc search for your paper, did you do so iteratively or a single input? Is there anything I can do to avoid having to parcel this out, or do individual predictions somehow depend on others?

Cheers!
Rich

**Comment by Miserlou** [comment]
Hi again, sorry to pester, was just hoping you could take a quick glance at this question and comment on your preferred implementation details before I begin a pull request.

**Comment by davidegraff** [comment]
the internals of Chemprop require holding, at the very least, all SMILES strings in memory for training/prediction and generates MolGraphs (the actual input representation to the MPN) as necessary (or reads them from a cache if specified.) You can circumvent this by writing your own wrapper for predict.py that stores SMILES strings on disk.
Concretely, here's are the steps you need to address:
1. store all of your strings on disk
2. read a chunk of strings into memory
3. pass that chunk to predict.py and generate prediction values
4. append that chunk to a list of prediction values
5. repeat 2-4 until you've read your entire file

**Comment by swansonk14** [comment]
Hi @Miserlou, we have made some improvements to the memory usage of Chemprop but for really large datasets like zinc, the best thing to do (and what we did) is to process the dataset piece by piece. We essentially did the same procedure as @davidegraff and used a bash script to run Chemprop on small chunks of zinc at a time and then at the end concatenated all the predictions.

I just checked and I don't see a PR from you but please let me know if I'm missing something! I'd love to see any code you might have to address this.
