### ISSUE TITLE
[BUG]: readout input size is wrong in `train.py` for additional molecular features

### ISSUE THREAD

**Issue by davidegraff** [chemprop/chemprop#481]
**Describe the bug**
Per Angiras and Xiarui:
> Xiaorui and I are having a look at additional features and are encountering a dimension error when it comes to readout when using the Morgan fingerprints. The output dimension of the message passing block becomes 2348 (default 300 + 2048 from Morgan fingerprint) but the readout input dimension is still 300. In train.py it seems that the readout input dimension is set to be mp.block.output_dim which seems to correspond to the size before any additional features are concatenated. As a result, it seems that the readout input dimension is unaware of the additional features vector x_f at the moment. In v1, there was another arg use_input_features that would then be added to the first linear dimension during readout and was set when additional features through features_generators or features_path were passed. Do we want to adopt the same approach for v2, or was there another approach you wanted to take?

**Comment by kevingreenman** [comment]
Fixed by #482
