### ISSUE TITLE
Remove all unused imports in v2 files

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#484]

**Comment by JacksonBurns** [comment]
We should also `isort` the imports. And the removal can be done automatically by something like `autoflake8`

**Comment by davidegraff** [comment]
thoughts on using `ruff` -> `black` as a pre-commit hooks?

**Comment by KnathanM** [comment]
#714 now enforces no unused imports. @JacksonBurns what is our status with sorted imports? Is that enforced with flake8?

**Comment by JacksonBurns** [comment]
By default `flake8` does not enforce a sort order on imports, although we could add it with the `flake8-import-order` plugin (see the [docs](https://flake8.pycqa.org/en/stable/internal/writing-code.html#imports), or `isort` as mentioned above.

**Comment by JacksonBurns** [comment]
Actually it occurs to me that this issue can be closed since the original topic has been resolved. Let's chat offline about if we want to enforce sorting/how and then open a separate issue.
