### ISSUE TITLE
Add Support for Python 3.12

### ISSUE THREAD

**Issue by JacksonBurns** [chemprop/chemprop#491]
We can support Python 3.12 once PyTorch releases binaries that compatible with it, which should happen when this tracked issue is closed:
 - [ ] https://github.com/pytorch/pytorch/issues/110436

**Comment by davidegraff** [comment]
also:
[ ] https://github.com/rdkit/rdkit/issues/6499

not sure of other packages we need to be aware of

**Comment by JacksonBurns** [comment]
The latest builds of RDKit are compatible with 3.12, and according to [this comment](https://github.com/pytorch/pytorch/issues/110436#issuecomment-1918088057) on the linked PyTorch issue, the latest builds of that work on windows. So I'll go ahead and close this - seems like the problem is resolved? Out of our hands, regardless (as it always was).
