### ISSUE TITLE
[TODO]: update `environment.yml` file for v2

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#499]
Originally posted by @davidegraff in https://github.com/chemprop/chemprop/pull/433#discussion_r1349307128

**Comment by kevingreenman** [comment]
This was removed in #695 since the file was out of date, but we should consider re-adding an updated version if we can get it to work. This was requested by some of the MLPDS companies.

**Comment by davidegraff** [comment]
based on the [most recent version](https://github.com/KnathanM/chemprop/blob/v2/dev/environment.yml), I would suggest we structure it something like:
```
- python==3.11.X
- lightning ~= 2.0
- numpy < 2.0
- pandas >= 2.0
- rdkit
- scikit-learn > 1.0
- scipy > 1.1
- pytorch == 2.X
- astartes
```
IMO we should keep it simple: (1) we should agree on a set of minimal requiresments (2) someone should build an env according to those requirements, and (3) `conda env export > environment.yml`. IMO, the environment should rely on `pip` as much as possible, i.e., use a `pip` sub-dependency in the YAML file, but this is a soft opinion. We should strive to make the `chemprop` environment `pip`-installable, but for the purposes of replication, it's fine to rely on `conda`.
