### ISSUE TITLE
[BUG]: data splitting tests fail

### ISSUE THREAD

**Issue by davidegraff** [chemprop/chemprop#513]
**Describe the bug**
```
$ pytest chemprop/v2/tests/ -k 'test_data_utils'
FAILED chemprop/v2/tests/unit/data/test_data_utils.py::TestSplitData::test_splits_sum1 - astartes.utils.exceptions.InvalidConfigurationError: Provided data and requested split resulted in an empty set. Dataset may be too small or requested splits may be too large. ( testing set empty )
FAILED chemprop/v2/tests/unit/data/test_data_utils.py::TestSplitData::test_three_splits_provided - IndexError: tuple index out of range
```

The first test fails because it expects to catch a `ValueError` but `astartes` throws an `InvalidConfigurationError` (subclass of `RuntimeError`)

The second one fails because it again expects to catch a `ValueError` but an `IndexError` is raised.

**Comment by JacksonBurns** [comment]
This is resolved in #510 - I have just pushed some updates, now waiting on @oscarwumit for some additional edits and then we can re-review.
