### ISSUE TITLE
[TODO]: Add support for NumPy 2.0 (coming Early 2024)

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#516]
See issue from NumPy: 

- [x] https://github.com/numpy/numpy/issues/24300

**Comment by JacksonBurns** [comment]
Note that the first release candidate of Numpy 2 was pushed back to Feb. 1 2024, but may possibly be pushed back again.

See the Numpy docs for more information on their suggested 2.0 support strategy: https://numpy.org/devdocs/dev/depending_on_numpy.html#testing-against-the-numpy-main-branch-or-pre-releases

**Comment by KnathanM** [comment]
Kicking the can down the road, see #733
