### ISSUE TITLE
Chemprop v2.0 Development Status and Notes

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#517]
* Stable v2.0 release planned for early 2024
  * Primary objectives - making Chemprop: more usable from within Python scripts, more modular, easier to maintain and develop, more compute/memory efficient, usable with PyTorch Lightning
  * Will include a user guide for transitioning from v1, expanded documentation, and tutorial notebooks
  * Some features will not be migrated from v1 to v2 (e.g. web, sklearn)
  * Some v1 features will be added in later versions of v2 (v2.1+) (e.g. uncertainty, atom- and bond-targets)
    * See milestones: https://github.com/chemprop/chemprop/milestones
* beta version now available on `v2/dev` branch: https://github.com/chemprop/chemprop/tree/v2/dev
  * Under active development - not guaranteed to be stable!
  * beta testers welcome - please let us know of any bugs you find by opening an issue
  * Command line interface (CLI) does not yet have feature parity with v1

**Comment by JenniferHem** [comment]
Hey @kevingreenman @davidegraff we are currently testing the v2/dev branch. I know its is not guaranteed to be stable but we would like to incorporate it already into our pipelines as it already makes your life much easier! However as the v2 folder does not (yet?) contain an __init__.py any installation, apart from manually installing misses the v2 folder. Could this maybe be changed already? Or would that result in too many headaches for you? 
I have seen you plan to move the things our from v2 in #486 but until then I would love to just install the branch via pip in the requirements!

**Comment by davidegraff** [comment]
When you install from source you can use it via:
```python 
from chemprop.v2 import …
```
we don’t have a top-level `__init__.py` yet, but we can add that easily. The main reason we haven’t moved it over yet though is for feature tracking, but at this point I think we’re far enough along that we can consider deleting the v1 code in that branch.

**Comment by arijit-s** [comment]
Hi devs, not sure if this is the correct forum to ask, but I noticed in the v2/dev branch, caching(MolGraoh and Mol) codes are commented out. Is caching not going to be implemented in v2? 
I am more interested in caching during prediction. I have multiple models, where I want to cache the molgraph generation. Hope this feature will be available.
Thanks for the wonderful job doing here.

**Comment by KnathanM** [comment]
Hi Arijit, 

A couple months ago we decided that caching was [unnecessary](https://github.com/chemprop/chemprop/pull/455#discussion_r1325126598) in the new version. It sounds like you might have a use case for caching. Can you open an issue about about your use case for caching the molgraphs as a feature request?

**Comment by davidegraff** [comment]
@arijit-s 

This is something we can consider adding back, especially now that `MolGraph` objects are much smaller. That said, v2 without caching is now faster than v1 even with caching. Using 8 workers, you can now process $\sim 10$ k $\text{mol}\cdot s^{-1}$. With the original code, you would get only half as many even when they were cached.

**Comment by kevingreenman** [comment]
We have released our release candidate v2.0.0-rc.1, please see here for details: https://github.com/chemprop/chemprop/releases/tag/v2.0.0-rc.1

**Comment by kevingreenman** [comment]
We have released the stable v2.0.0, please see here for details: https://github.com/chemprop/chemprop/releases/tag/v2.0.0
