### ISSUE TITLE
[TODO]: Link old website to new documentation

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#519]
After the old website is taken down, we should have the http://chemprop.csail.mit.edu/ URL redirect to our new documentation. We can follow the instructions [here](https://kb.mit.edu/confluence/display/istcontrib/Web+Publishing+-+Domain+Names) (email the MIT Service Desk with a request, specifying that Bill will be the faculty "sponsor" for it).

We might also want to reserve http://chemprop.mit.edu and have that redirect to our documentation as well.

**Comment by JacksonBurns** [comment]
I have started this process in an internal email chain.

**Comment by JacksonBurns** [comment]
This has been completed.
