### ISSUE TITLE
BinaryMCCMetric defined twice

### ISSUE THREAD

**Issue by c-w-feldmann** [chemprop/chemprop#525]
In v2/dev - models/metrics.py:  
https://github.com/chemprop/chemprop/blob/db9bc6dfb54248f4786784f8eec40c36a379e94b/chemprop/v2/models/metrics.py#L135  
redefines `BinaryMCCMetric` defined in already defined in L131:  
https://github.com/chemprop/chemprop/blob/db9bc6dfb54248f4786784f8eec40c36a379e94b/chemprop/v2/models/metrics.py#L131  
I propose to rename the first one to `MultiClassMCCMetric`.

**Comment by davidegraff** [comment]
this should be fixed in #470
