### ISSUE TITLE
v2 CI is failing

### ISSUE THREAD

**Issue by davidegraff** [chemprop/chemprop#526]
our automated CI is failing in two spots:
1. our tests that rely on a file `regression.csv`. I'm not sure where this file is but we should fix those tests or create the relevant file
2. `flake8`: a lot of our CLI code raises errors here. We should fix this.
  _NOTE:_ we should break this up into steps: `build` which does some quick semantic checking for failing fast and `lint` which runs `black`, `flake8`, etc. and checks that our code is formatted properly

**Comment by kevingreenman** [comment]
Partially fixed by #549  and #551

**Comment by davidegraff** [comment]
yep seems like it's passing now
