### ISSUE TITLE
[QUESTION]: Argument data_path question

### ISSUE THREAD

**Issue by IannLiu** [chemprop/chemprop#528]
Hi, it's possible to parse a list of `data_path` (and/or `separate_val_path`, `separate_test_path`) ?  It would be convenient to use user-defined data folds for cross-validation and hyperparameter optimization.

**Comment by kevingreenman** [comment]
We don't have this feature very well documented, but the way to accomplish what you're asking is using the `--index_predetermined` and `--crossval_index_file` arguments. You can look in the [args.py](https://github.com/chemprop/chemprop/blob/master/chemprop/args.py) file to see how these arguments work.
