### ISSUE TITLE
[QUESTION]: Training and then fine tuning your own model

### ISSUE THREAD

**Issue by Rhys-McAlister** [chemprop/chemprop#530]
Using chemprop 2.0/v2 is it possible to train your own model on a particular dataset and then fine tune it on another dataset?

**Comment by davidegraff** [comment]
I don't see why not. You would just need need to load the model from the prior training run and then proceed with training like normal.

**Comment by kevingreenman** [comment]
I'm not sure if we've added the ability to freeze weights yet, but as David said, starting training from an existing model should be doable. Please let us know if you try it and it doesn't work for you for some reason.

**Comment by Rhys-McAlister** [comment]
Yeah re-training through loading the model does appear to work Is freezing weights high on the priority list for features to be added? Because that would be fantastic to have with the new system.

**Comment by kevingreenman** [comment]
Yes, essentially everything from v1 training and prediction will also be implemented in v2. The main things that we do not plan to implement in v2 are interpretation, sklearn utility functions, and the web interface. We expect that the stable v2 should be ready in early 2024.
