### ISSUE TITLE
[QUESTION]: UV/VIS absorption dataset availability

### ISSUE THREAD

**Issue by emielvb** [chemprop/chemprop#535]
**What are you trying to do?**
I would like to train a model for UV-VIS absorption peak prediction. Table I in your [paper](https://chemrxiv.org/engage/chemrxiv/article-details/64d1f13d4a3f7d0c0dcd836b) on chemrxiv mentions the existence of a UV/VIS absorption peak dataset. I am unable to locate this dataset, is it possible the `.csv` file is not contained within `data.tar.gz`?

**Screenshots**
![image](https://github.com/chemprop/chemprop/assets/93741947/91ab4976-867f-4585-bc5f-075f7c8ccc85)

![image](https://github.com/chemprop/chemprop/assets/93741947/2c325bd2-d479-45c6-894a-41d3daae5e76)

**Comment by kevingreenman** [comment]
Hi @emielvb, thanks for your question. For the 2023 paper, you should look at our [benchmark repository](https://github.com/chemprop/chemprop_benchmark). The `data.tar.gz

**Comment by kevingreenman** [comment]
It may also be of interest that the UV/Vis data used in our benchmark is from [here](https://github.com/learningmatter-mit/uvvisml/tree/main/uvvisml/data), which is a collection of data from several other papers.

**Comment by emielvb** [comment]
Thanks for the response @kevingreenman!
