### ISSUE TITLE
Add parameter deep=True to get_params from ReprMixin in v2/dev

### ISSUE THREAD

**Issue by c-w-feldmann** [chemprop/chemprop#539]
Hey,
here you implement the function `get_params`, which I thinks should be parallel to the `get_params` from sklearn.
https://github.com/chemprop/chemprop/blob/523fa860296ef4142456067df36d675bf0a0e719/chemprop/v2/utils/mixins.py#L19
Can you add the parameter `deep:bool=True` so it can be called similarly?

@JenniferHem: FIY

**Comment by c-w-feldmann** [comment]
It would also be nice if the function could return a dict, rather than a collection of tuples.

**Comment by davidegraff** [comment]
You're welcome to tackle this, but the mixin class is only used in two spots of the code. It's also not a formal subclass of the sklearn `BaseEstimator`, so I don't think we really owe it to implement those features
