### ISSUE TITLE
transfer learning needed

### ISSUE THREAD

**Issue by icewave123** [chemprop/chemprop#54]
Can we added transfer learning,  which allow to load pre-trained model and train on new dataset.

**Comment by swansonk14** [comment]
Hi @icewave123, thank you for the question! This is actually already possible within Chemprop. Simply train a model on one dataset using `--save_dir <dir>` to train and then save the model, and then run training on a second dataset using `--checkpoint_dir <dir>` to load the first model and continue training on the new dataset.

For example:

```
python train.py --data_path data/freesolv.csv --dataset_type regression --save_dir freesolv_ckpt
```

```
python train.py --data_path data/delaney.csv --dataset_type regression --checkpoint_dir freesolv_ckpt --save_dir delaney_ckpt
```

However, it is worth noting that the number of tasks and the dataset type must match between the two datasets. If they don't, you may need to do a bit of manual work to change the final output layer when doing the transfer.

**Comment by kandoigaurav** [comment]
Since you mention that the number of tasks in the second training step should be the same as initial pre-training, would you recommend adding simple auxiliary tasks to our task of interest to make up those extra number of tasks? Or would changing the final output layer be better?
