### ISSUE TITLE
limitation of the number of data points for using Chemprop

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#541]
Hello,
I have a dataset containing around 600 compounds (for training, validation, and test) and I would like to use Chemprop to predict the accumulation of the compounds in a type of Bacteria. I was wondering if I could use Chemprop for these limited data points.

Thank you

**Comment by kevingreenman** [comment]
The only way to know is to try it :)

Typically, we've observed that chemprop starts to outperform traditional baselines (e.g. Morgan fingerprints with a random forest model) when you have on the order of thousands of data points, but this will depend on your dataset and the property you're trying to predict. 

It's worth noting that with a small dataset, the choice of how you split the dataset into train/validation/test sets to avoid information leakage becomes more important, and it may be wise to use cross-validation to better assess model performance.
