### ISSUE TITLE
[TODO]: Add example notebooks to the docs

### ISSUE THREAD

**Issue by davidegraff** [chemprop/chemprop#556]
Sphinx supports embedding [jupyter notebooks](https://docs.readthedocs.io/en/stable/guides/jupyter.html) into docs. We should add the notebooks we've written [here](https://github.com/chemprop/chemprop/tree/v2/dev/examples) instead of manually writing out additional python examples in ReST.

*Note:* we should add commentary and formatting to the notebook before adding them in so that users can follow along better

**Comment by davidegraff** [comment]
should be fixed by #467 or added later. Also linked to #448

**Comment by kevingreenman** [comment]
also linked to #616

**Comment by davidegraff** [comment]
a suggestion: we this section in the docs should be called "cookbook"

**Comment by oscarwumit** [comment]
Related https://github.com/chemprop/chemprop/pull/923
