### ISSUE TITLE
[TODO]: fix example script and notebooks

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#559]
**Notes**
Recent changes have broken `example.py` and the notebooks in `examples/` (these are not included in our testing for PRs). 

Is there a way to test these all automatically as part of our testing for each new PR (e.g. just make sure they run to completion without errors)?

**Comment by hwpang** [comment]
Looks like we can test notebooks using https://github.com/marketplace/actions/run-notebook
