### ISSUE TITLE
[Bug] Issue with hyperparameter_optimization.py script due to typed-argument-parser version

### ISSUE THREAD

**Issue by cswingle98** [chemprop/chemprop#56]
It seems that in a more recent update to the repo something has gone wrong with attempting to do hyper_opt. We've tried two methods of running the scripts by either calculating features first with scripts/save_features.py and by not doing this. The two command-line arguments provided are as follows:

1. `python scripts/save_features.py --data_path data/data/caco2_regression.csv --features_generator rdkit_2d_normalized --save_path features/caco2.npz --sequential`
2. `python hyperparameter_optimization.py --data_path data/caco2_regression.csv --config_save_path configs/caco2.json --quiet --split_type scaffold_balanced --features_path features/caco2.npz --no_features_scaling --num_iters 20 --num_folds 3 --dataset_type regression`

In either case, hyperparameter_optimization.py gives the following error:

> line 62, in create_ffn
>   first_linear_dim += args.features_size
> TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

**Comment by cswingle98** [comment]
Downgrading to typed-argument-parser version 1.4.3 fixed the issue. It seems to be a problem with the newer version.

**Comment by swansonk14** [comment]
Hi @cswingle98, thank you for describing the issue! This was in fact a bug in typed-argument-parser which I fixed in this release: https://github.com/swansonk14/typed-argument-parser/releases/tag/v_1.5.2. If you upgrade to typed-argument-parser version 1.5.2 it should now work.
