### ISSUE TITLE
[TODO]: fix CLI and add CLI integration tests

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#561]
**Notes**
Recent changes have broken the CLI (training and prediction for sure, and maybe others).

In addition to fixing the CLI, we should add integration tests that run the CLI from Python to catch when it breaks in the future.

**Comment by kevingreenman** [comment]
suggestion for how to do this from @davidegraff: https://github.com/chemprop/chemprop/pull/578#issuecomment-1885833320

**Comment by kevingreenman** [comment]
- [ ] train (basic)
- [ ] predict (basic)
- [ ] multi-component

**Comment by KnathanM** [comment]
There are now many tests for the CLI integration.
