### ISSUE TITLE
[TODO]: example notebook dependencies

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#563]
**Notes**
From #562, we should consider including ipykernel as part of a new set of optional dependencies (maybe called `notebooks`) in pyproject.toml so that one can run the example notebooks in VS Code after installing the chemprop environment, without having to take an additional step

**Comment by davidegraff** [comment]
being able to run a notebook is not a core dependency of the package, and it's pretty easy for users to figure out they need the package to run notebooks. I don't think this is necessary.

**Comment by KnathanM** [comment]
My opinion is that manually adding `ipykernel` to a Chemprop environment after realizing you need it isn't too difficult, especially if we include in the documentation a note about that. We can discuss it more in our next developer meeting.

**Comment by kevingreenman** [comment]
I agree that it isn't hard for a user to figure this out on their own, but I don't think it hurts us to add one line to the `pyproject.toml` to make this clear, especially since we can specify that it's optional and only related to the notebooks.

I can also foresee additional packages being added to this `notebooks` optional dependencies list, if we wanted to include some example notebooks that required other packages that aren't part of chemprop's core functionality. For example, if we provide an example notebook of doing active learning or attribution using another package interfaced with chemprop, those dependencies could also be added here.
