### ISSUE TITLE
[TODO]: remove example.py or add it to testing

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#564]
**Notes**
From #562 and #559, we should either remove the `example.py` file since very similar contents are contained in the `examples/` notebooks, or we should add this script to our automated testing as we did with the notebooks in #562 to make sure it still works when we make new changes

**Comment by davidegraff** [comment]
agreed. The script was only meant to serve as a playground for testing/porting features over and for devs to understand the new object model. It should no longer be necessary between the example scripts and integration testse.
