### ISSUE TITLE
[Question] Uncertainty in predicted values

### ISSUE THREAD

**Issue by nathanmlim** [chemprop/chemprop#57]
Hello, just a quick question. Is it possible to get the uncertainty in the models predicted values?

**Comment by swansonk14** [comment]
Hi @nathanmlim, good question! We're actually currently working on developing uncertainty prediction for Chemprop models and we have a paper in the works that we hope to publish soon. The overall takeaway is that current uncertainty quantification methods aren't great, but they may give you at least some indication of the uncertainty of the predictions. Our uncertainty code is currently in this fork of Chemprop if you want to take a look: https://github.com/lhirschfeld/ChempropUncertaintyQuantification.
