### ISSUE TITLE
using chemprop classification for extremely imbalanced data

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#573]
Hello,
I have a dataset in which the positive class is around 1%. I split the dataset into training, validation and test such that the percentage of the positive class in each split is the same. After training with chemprop classification with an ensemble of 20 models and using RDKit features, I found a model with AUC 69%. However, I noticed the prediction probabilities for the test data is so small. I am attaching the test data here, you can see the ground truth and their corresponding predicted probability.

I was wondering if I need to change any parameters/coefficients for imbalanced data in chemprop or if you have any suggestions.

I really appreciate your help.

Best Regards
Soo
[chemprop_classification.csv](https://github.com/chemprop/chemprop/files/13831973/chemprop_classification.csv)

**Comment by kevingreenman** [comment]
See #572
