### ISSUE TITLE
[QUESTION]: How can I use multi-GPU training to speed up my calculations

### ISSUE THREAD

**Issue by zifengdexiatian** [chemprop/chemprop#584]
**What are you trying to do?**
I was training a model with 300,000 samples and found that the program only used one GPU and only used 2% of the memory. My GPU is 1080ti. What should I do to take advantage of all 4 Gpus on my linux server?

**Previous attempts**
I tried to find a parameter in the training parameter to adjust the number of GPUs, but I couldn't find one, only a parameter '--GPU' that specified the number of the GPU.

**Screenshots**
![image](https://github.com/chemprop/chemprop/assets/83349433/d2fe8fb6-2349-4c66-89b4-6ec44abe7f7c)

**Comment by kevingreenman** [comment]
Chemprop v1 does not support training on multiple GPUs. [Chemprop v2](https://github.com/chemprop/chemprop/issues/517) (stable version to be released soon) does. In v1, you could increase your batch size if you're not utilizing much of the available memory.

**Comment by JacksonBurns** [comment]
@zifengdexiatian (and others), we are currently working on #529 which will add support for DDP multi-GPU parallelization in chemprop v1. As stated above, chemprop v2 will also support DDP, though through a different mechanism.
