### ISSUE TITLE
[TODO]: V2 Add a `load_model` function for inference instead of using `load_from_checkpoint`

### ISSUE THREAD

**Issue by hwpang** [chemprop/chemprop#589]
**Notes**
See this comment: https://github.com/chemprop/chemprop/pull/585#discussion_r1459315346 for details. `load_from_checkpoint` contains much information only needed to continue training but are not needed for inference. We should think about defining another function `load_model` to load only model state and the model architecture.

**Comment by davidegraff** [comment]
I think this should be addressed via an `MPNN.load_model` class method. It can probably be very similar to `MPNN.load_from_checkpoint`, particularly these lines:

```python
@classmethod
def load_from_checkpoint(
    cls, checkpoint_path, map_location=None, hparams_file=None, strict=True, **kwargs
) -> MPNN:
    hparams = torch.load(checkpoint_path)["hyper_parameters"]

    kwargs |= {
        key: hparams[key].pop("cls")(**hparams[key])
        for key in ("message_passing", "agg", "predictor") if key not in kwargs
    }
```

can be adapted like so:

```python
@classmethod
def load_from_file(cls, model_path, map_location=None, strict=True) -> MPNN:
    d = torch.load(model_path, map_location=map_location)

    try:
        hparams = d["hyper_parameters"]
        state_dict = d["state_dict"]
    except KeyError:
        raise KeyError(...) # some descriptive error here

    for key in ["message_passing", "agg", "predictor"]:
        hparam_kwargs = hparams[key]
        hparam_cls = hparam_kwargs.pop("cls")
        hparams[key] = hparam_cls(**hparam_kwargs)

    model = cls(**hparams)
    model.load_state_dict(state_dict, strict=strict)

    return model
```

Maybe someone wants to try this out, but I just don't have the bandwidth to test that this actually works.

**Comment by hwpang** [comment]
Thanks for the suggestion, @davidegraff! I can try this out.

**Comment by davidegraff** [comment]
@hwpang in the spirit of test-driven development, the unit tests for this function should be:
1. `test_roundtrip`: saving a model to a file and then loading the resulting file into a new model should produce the same predictions as the original model
2. `test_checkpoint_is_valid`: that any valid `model.ckpt` can be supplied to this function
3. `test_checkpoint_roundtrip`: that two models, one loaded via `MPNN.load_from_checkpoint` and the other loaded via `MPNN.load_from_file`, generate the same predictions

**Comment by hwpang** [comment]
Resolved by https://github.com/chemprop/chemprop/pull/606.
