### ISSUE TITLE
[TODO]: V2 Add pytest to test CLI functionality 

### ISSUE THREAD

**Issue by hwpang** [chemprop/chemprop#590]
**Notes**
See https://github.com/chemprop/chemprop/pull/585#discussion_r1459335866 for details.

**Comment by davidegraff** [comment]
we should probably use [marks](https://docs.pytest.org/en/7.1.x/example/markers.html#marking-whole-classes-or-modules) to mark all of these tests as CLI (and a similar thing for the integration tests). This will speed up testing during development and help us delineate the type of tests we're running in the CI, e.g.:
1. run unit tests: `pytest -v -k 'not (CLI or integration)'` 
2. run integration tests: `pytest -v -k 'integration'`
3. run CLI tests: `pytest -v -k 'CLI'`

**Comment by hwpang** [comment]
Resolved by https://github.com/chemprop/chemprop/pull/602.
