### ISSUE TITLE
[QUESTION]: the square root of the evidential total or epistemic variance seems to show an exponential pattern - is this expected?

### ISSUE THREAD

**Issue by GLPG-GT** [chemprop/chemprop#593]
**What are you trying to do?**

We have built and deployed a multi-task model, using evidential loss.  
We are trying to *qualify the predictions from the model using an estimate of uncertainty*: we output **evidential total uncalibrated variance** together with the predictions.

In training, we use evidential_regularization = 0.2.

However, we recently got remarks that our predictions were not used 'because the uncertainty is so large they are completely useless'.

This was quite unfortunate, as chemprop has very satisfactory validation and test performance metrics for our tasks.

So we looked into it (using a method ~similar to ENCE, details below), and found that, for both 'unseen' compounds and in-training compounds, **chemprop's evidential total uncalibrated variance (henceforth referred to as 'ev_var', and its sqrt 'ev_std') was far overestimating the actual error on the predictions**.  
For some tasks, and for low ev_std bins, the alignment was ~acceptable, but for other tasks, and especially at high ev_std bins, ev_std was overestimating by several order of magnitude the actual rmse.

**Previous attempts**

Our assumption (please correct us if we are wrong) was that a sufficiently large set of compounds whose predictions have, say, ev_std = 0.5, should have residuals (experimental - predicted) whose standard deviation (i.e. essentially their rmse, calculated after grouping by ev_std) is close to 0.5.  
Obviously each compound may have a different ev_std, so we cannot use individual values for binning: for each task, we binned (using `pd.cut`) ev_std into 10 bins, which results in reasonable ranges. We took each bin midpoint as representative ev_std.  
We calculated the residual standard deviations (residual_std) grouped by [task, ev_std_bin], and **plotted residual_std vs ev_std_bin_midpoint**.

This immediately showed that not only ev_std_bin_midpoint was almost consistently overestimating the residual_std, but that the overestimation **was not by a constant factor**, but displayed a relationship like: **residual_std = A + B * log10(ev_std_bin_midpoint)**, as if ev_std_bin_midpoint were an exponential function of what it is supposed to quantify.

This last point is particularly important, because the obvious response to our question would be: calibrate the uncertainty.  
We cannot do that for reasons that are long to explain; but in any case, the calibration methods that we can find in the documentation all seem to use a 'multiplying factor' for ev_std, which wouldn't address the issue of the apparent exponential escape we are documenting.

**Screenshots**
Model trained with https://github.com/chemprop/chemprop/blob/master/tests/data/regression.csv

```
train_cmd = f'\
chemprop_train \
--data_path "{train_file_path}" \
--dataset_type regression \
--save_dir "{save_dir}" \
--split_sizes 0.9 0.1 0 \
--seed 20240120 \
--loss_function evidential \
--evidential_regularization 0.2 \
'
```

Predictions and uncertainties output by:

```
for unc in ['evidential_total', 'evidential_epistemic', 'evidential_aleatoric'] :
    predict_cmd = f'\
    chemprop_predict \
    --test_path "{train_file_path}" \
    --checkpoint_dir "{save_dir}" \
    --preds_path "{save_dir}\\predictions_{unc}.csv" \
    --uncertainty_method {unc} \
    '
    os.system(predict_cmd)

```
Plots of the residuals vs ev_std, in this case including aleatoric and epistemic as well as total:

![image](https://github.com/chemprop/chemprop/assets/96192927/80018028-801e-485f-a7f9-a99533743226)

![image](https://github.com/chemprop/chemprop/assets/96192927/4a7498c7-a71e-4f94-9fb1-a65c054d758f)

![image](https://github.com/chemprop/chemprop/assets/96192927/5513298d-8e7a-4c7f-ad02-fef84f64087c)

Plots of the binned residual_std vs ev_std bin midpoint:

![image](https://github.com/chemprop/chemprop/assets/96192927/3d2115e9-f0c8-4a92-b7fc-782551a77d97)

![image](https://github.com/chemprop/chemprop/assets/96192927/894988c2-7831-4dcb-ba76-d407bb3dd427)

![image](https://github.com/chemprop/chemprop/assets/96192927/04d06376-b788-4a77-978b-c1a7df5b56ea)

Same, with the x axis in log scale:

![image](https://github.com/chemprop/chemprop/assets/96192927/5c7a9190-130c-42d2-a92a-def08cc4cf58)

![image](https://github.com/chemprop/chemprop/assets/96192927/b6b2be30-c7fa-4b5b-86e3-84539898e16b)

![image](https://github.com/chemprop/chemprop/assets/96192927/ec113b7e-073d-4f0d-ba64-1c5cd19f7864)

Same, with pre-transformed x axis (log10) and weighted regression line:

```
total_residual_std = 0.6498765931183114 + 1.0226299888078183 * log10_total_ev_std_bin_midpoint
r2 = 0.8864295716037394
```
![image](https://github.com/chemprop/chemprop/assets/96192927/3176b897-5248-4fdb-aad3-396e898ada72)

```
epi_residual_std = 0.6674933830636588 + 0.9401052168603675 * log10_epi_ev_std_bin_midpoint
r2 = 0.9044144749516978
```

![image](https://github.com/chemprop/chemprop/assets/96192927/81b99f99-08ee-4af9-a5e5-4857ba9fa32a)

For this specific example, one may argue that the last 3 points (high ev_std bins) are not representative, and the relationship can indeed be accounted for by calibration, like: **residual_std = C * log10(ev_std_bin_midpoint)**, with C being the calibration factor.

We may agree, if it weren't for our own in-house cases, where the exponential escape is far more evident, and we have high bins of ev_std with sufficient residuals data points to make them quite reliable.  

In addition, we tried different values of the evidential_regularization parameter [0, 0.1, 0.2, 0.5, 1], and found that, while the relationship between residual_std and ev_std_bin_midpoint remains the same (logarithmic, not linear), the effect is stronger for higher evidential_regularization, values 0.5 and 1 resulting in extremely large uncertainties, several orders of magnitude larger than the TSS.  

Here is a plot of the total ev_std (each set of boxplots is for a different task; sorry we cannot disclose the task names, but they are ADME endpoints, not activity):

![image](https://github.com/chemprop/chemprop/assets/96192927/73f5b56c-40a8-4f01-99a5-6b1e5ba1cd46)

For comparison, here are the predictions, made with the same models of course, tasks in the same order:

![image](https://github.com/chemprop/chemprop/assets/96192927/677d50c7-7e14-4420-bf2c-68a03d4567be)

The strict performance (r2 and rmse) of the models was very similar, with a slight preference for the one with evidential_regularization = 0 :

![image](https://github.com/chemprop/chemprop/assets/96192927/2c8fee1d-3767-44ff-8fb6-466b3a3e361d)

How can a model issue a fairly accurate prediction, for values in a range like [-5, 5], and then say its uncertainty is 1000 or 1000?  
We don't think this can be accounted for by a simple multiplying factor, and again, the most striking feature emerging from our analysis is the extremely consistent **logarithmic** nature of the relationship, at least for evidential_regularization up to 0.2-0.5. An example of weighted regression from the output of our in-house model (again, task names obfuscated):

![image](https://github.com/chemprop/chemprop/assets/96192927/1664d3de-01e3-41a8-b890-950737bc20b7)

Further analysis seems to indicate that, in the above relationship:  
residual stdev = A + B * log(pred stdev)  
A is more strongly dependent on the evidential_regularization than on the task, whereas B may depend on both, but probably more on the task.

**Conclusion and final question**

As per post title: does it make sense, or is it expected, that the total evidential uncalibrated variance bear this type of logarithmic relationship with the measured binned residual rmse's, especially when larger evidential_regularization parameters are used?  
The calibration methods proposed in the documentation seem to suggest a linear relationship between the two. How would that correct the overestimation on the high variance side, without improperly introducing underestimation on the low variance side?

Sorry for the very long post; we did study this issue in detail, and we feel such a complex topic requires extensive documentation.

**Comment by JacksonBurns** [comment]
Hi @GLPG-GT I apologize for this enormously unsatisfactory answer, but this question is well beyond our capacity to offer help. This is diving deep into the theory of evidential uncertainty, which none of the current developers know much about.

The best advice we can give is to reach out to the authors of the reference paper Deep Evidential Uncertainty (see the paper here: https://arxiv.org/abs/1910.02600) .

If you want to take a totally different approach, consider running replicates of your model rather than using cross validation. By then averaging (including the stdev) performance across test sets, you can get a coarser idea of your model's reliability. While not directly supported by chemprop, you can then ensemble these models to deploy them, considering a prediction 'uncertain' when the group disagrees on a given prediction.
