### ISSUE TITLE
[TODO]: change issue templates for v1/v2

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#605]
**Notes**
Change issue templates so we have:
* v1 bug report (make clear that these will most likely not be fixed and are for community benefit)
* v2 bug report
* v2 feature request
* v2 question

**Comment by davidegraff** [comment]
I've been titling my issues with [v2]. Should we stop doing that and just add a `v1` tag to demarcate issues as v1 issues now?

**Comment by kevingreenman** [comment]
I've mostly been keeping track of which issues/PRs correspond to which versions by adding them each to a milestone. Having the [v2] in the title makes this easier, so you can keep doing that. I don't think a new tag is necessary since we already have the milestones and the "v1-wontfix" tag. We can set up the v1 bug report template so that it automatically labels those with the "v1-wontfix" tag in addition to the "bug" tag it currently adds.

My thinking is that this would be more for the benefit of the users, so they have a better idea of what to expect when they're opening an issue (i.e. they know we're not going to help them fix v1 bugs anymore, and they should only ask questions / request features for v2).
