### ISSUE TITLE
[BUG] [V2]: `split_data` function does cross-validation incorrectly

### ISSUE THREAD

**Issue by hwpang** [chemprop/chemprop#609]
**Describe the bug**
See https://github.com/chemprop/chemprop/issues/581#issuecomment-1911000562 for relevant discussion. In a nutshell, the `split_data` function does not really partition the data into subsets. Instead, it resamples the data for `k` times for "`k`-fold cross validation", which is incorrect.

**Comment by JacksonBurns** [comment]
Resolved by #610
