### ISSUE TITLE
[BUG]: Scale transform X_f

### ISSUE THREAD

**Issue by KnathanM** [chemprop/chemprop#613]
`normalize_inputs() of _MolGraphDatasetMixin only fits a scaler and doesn't transform (https://github.com/chemprop/chemprop/blob/v2/dev/chemprop/data/datasets.py#L126) 

This probably should be addressed when we add saving and loading all the scalers that v1 had.

**Comment by hwpang** [comment]
Closed by https://github.com/chemprop/chemprop/pull/635.
