### ISSUE TITLE
[v2]: If `--crossval_index_file` is added, document what it should look like

### ISSUE THREAD

**Issue by JacksonBurns** [chemprop/chemprop#630]
Basically the title - as you can see in https://github.com/chemprop/chemprop/issues/265 we somehow last track a few years ago of what the `--crossval_index_file` is actually supposed to look like (it's used to manually specify data splits). **If** this feature is added to v2, we need to unambiguously document what the file should look like, add unit tests for it, and include example files that are in that format for users to build on.

**Comment by davidegraff** [comment]
I feel like JSON `list[tuple[list[int], list[int]]` is the way to go:
```python
train_val_idxss = json.loads(Path(CROSS_VAL_INDEX_FILE).read_text())
```
with the following requirements:
```python
# that each inner list must be of length 2, i.e., 'train' and 'val'
assert all(len(xs) == 2 for xs in train_val_idxss)
# that the sum of lengths of all the inner lists must be the same
lengths = [sum(len(x) for x in xs) for xs in train_val_idxss]
assert all(length = lengths[0] for length in lengths)
# that the train and val lengths must all the be same
train_idxss, val_idxss = zip(*train_val_idxss)
assert all(len(idxs) == len(train_idxss[0]) for idxs in train_idxss)
assert all(len(idxs) == len(val_idxss[0]) for idxs in val_idxss)
# (DEBATABLE) that the validation sets are disjoint, i.e., that it is a true cross validation set
train_idxss, val_idxss = zip(*train_val_idxss)
n_val_idxs_total = sum(len(idxs) for idxs in val_idxss)
n_val_idxs_uniq = len(set().union(*val_idxss))
assert n_val_idxs_total == n_val_idxs_uniq
```

**Comment by JacksonBurns** [comment]
I agree on a plaintext format, rather than a binary one. No thoughts on the specifics ATM

**Comment by kevingreenman** [comment]
related to #645

**Comment by kevingreenman** [comment]
I just realized that there are some old scripts in the `scripts/` directory of the repo that I think answer our longstanding question of the proper format for `--crossval_index_file`:
* https://github.com/chemprop/chemprop/blob/master/scripts/create_crossval_splits.py
* https://github.com/chemprop/chemprop/blob/master/scripts/create_crossval_index_files.py

I'm also realizing that I [used this argument](https://github.com/chemprop/chemprop/issues/310#issuecomment-1197543196) while debugging a previous issue (#310). Using `--save_smiles_splits` while `--num_folds` is greater than 1 should result in the `split_indices.pckl` file being written.

I'll post this on the previous relevant issues so people can find it when searching for it in the future.
