### ISSUE TITLE
[QUESTION]: Setting seeds for model creation

### ISSUE THREAD

**Issue by Rhys-McAlister** [chemprop/chemprop#644]
In a notebook I'm trying to create a series of models for an ensemble and I'm trying to understand how I can set discrete seeds for each of these models when creating them. I'm aware of lightning.seed_everything() but I was wondering if there was a way to set them per model as you do when splitting the data?

**Comment by KnathanM** [comment]
Hi @Rhys-McAlister, I think this would work for what you are describing:
```
torch.manual_seed(<seed1>)
model1 = MyChempropModel()
torch.manual_seed(<seed2>)
model2 = MyChempropModel()
etc.
```
But also assuming that you create all the models immediately one after another, you only need to set the seed once as the torch randomness backend updates in a deterministic way each time you use it to initialize weights in a model. That is a notebook cell with
```
torch.manual_seed(0)
model1 = MyChempropModel()
model2 = MyChempropModel()
```
will give two models with different but deterministic initializations
