### ISSUE TITLE
[TODO]: Add max data size

### ISSUE THREAD

**Issue by KnathanM** [chemprop/chemprop#650]
**Notes**
In v1 `--max_data_size`, would specify how many rows of the input data csv to read in. If `None`, reads all of the rows of data.

**Comment by davidegraff** [comment]
Why can't they just appropriately provide the correct input data, i.e., truncate the input CSV? This seems like we're reinventing the wheel of data ingestion here.

**Comment by KnathanM** [comment]
I've seen someone use this option to test that their architecture runs correctly on a couple thousand data points before committing to training on their full data set. It could also be a convenient way to show the effect of increasing dataset size without having to have multiple partially identical files. 

That said, I agree it isn't actually too much work to just make multiple input files if you want to change how much data Chemprop is given. I'll treat this as lower priority and maybe loop back to it later.
