### ISSUE TITLE
[TODO]: Add way to freeze parts of the model during training. 

### ISSUE THREAD

**Issue by KnathanM** [chemprop/chemprop#651]
**Notes**
The v1 README has some details about how `--checkpoint_frzn`, `--frzn_ffn_layers`, and `--freeze_first_only` worked. 

Primarily this functionality is [in](https://github.com/chemprop/chemprop/blob/d58d877fd1d652929b0216e7b0cc11355664fd97/chemprop/utils.py#L195) `chemprop.utils.load_frzn_model`. But also when the model is [created](https://github.com/chemprop/chemprop/blob/d58d877fd1d652929b0216e7b0cc11355664fd97/chemprop/models/model.py#L86), the params that are frozen need `.requires_grad = False`.

**Comment by davidegraff** [comment]
This can be done with a one-liner using [`torch.nn.Module.apply`](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.apply):
```python
Net: torch.nn.Module = ...

Net.apply(lambda m: m.requires_grad(False))
```
The only challenge here is applying it to the correct submodule
