### ISSUE TITLE
Training a multi molecule model ?

### ISSUE THREAD

**Issue by mmagithub** [chemprop/chemprop#670]
Hi,

I am trying to use the multi-molecules training functionality to train a water solubility model based on the most stable tautomeric states for the molecules, but I also need to weight these states by relative Energies where the most stable tautomer will has a relative E = 0 kcal/mol, is this possible given the current chemprop architecture ?  

M

**Comment by kevingreenman** [comment]
If you have a different SMILES string for each tautomer such that each tautomer has a 2D molecular graph distinct from the other tautomers, then you could probably accomplish this using the `--data_weights_path` argument described [here](https://github.com/chemprop/chemprop?tab=readme-ov-file#weighted-training-by-target-and-data).
