### ISSUE TITLE
Sklearn_train.py does not save train/test splits 

### ISSUE THREAD

**Issue by nathanmlim** [chemprop/chemprop#68]
I've tried using the `sklearn_train.py` scripts and they work but they do not seem to save the train/test splits, even when using the `--save_smiles_splits` flag.

**Comment by swansonk14** [comment]
Hi @nathanmlim, thanks for catching that! We had forgotten to include the `save_smiles_splits` in `sklearn_train.py`. I just pushed a fix to enable that: https://github.com/chemprop/chemprop/commit/99fd202966787395757f6ac9371fe02d4111f05e
