### ISSUE TITLE
[QUESTION]: Interpret error: multiprocessing_context option should specify a valid start method in ['spawn'], but got multiprocessing_context='forkserver'

### ISSUE THREAD

**Issue by llzhu** [chemprop/chemprop#689]
I got the following error:
```
multiprocessing_context option should specify a valid start method in ['spawn'], but got multiprocessing_context='forkserver'
```

when running:
`interpret_out = chemprop.interpret.interpret(args=interpret_args)`

Codes are as follows:
```
interpret_arguments = [
        '--data_path', os.path.join(test_checkpoints_req_user, 'fold_0/test_smiles.csv'),
        '--checkpoint_dir', os.path.join(test_checkpoints_req_user, 'fold_0')
    ]
    interpret_args = chemprop.args.InterpretArgs().parse_args(interpret_arguments)

    # interpret_args.num_workers = 0
    interpret_out = chemprop.interpret.interpret(args=interpret_args)
```

I had similar problem when running 
`preds = chemprop.train.make_predictions(args=pred_args)`
but resolved by setting (at the advice of Kevin):
`pred_args.num_workers = 0`

But for interpret, it does not help.
I am on Windows 10. chemprop 1.5.2 (also tried 1.6.1). Please advise me how to fix this.

Thanks,  -Leiming

**Comment by kevingreenman** [comment]
could you please post the full strack trace for the error?

**Comment by kevingreenman** [comment]
I'm pretty sure the reason why the fix of setting `num_workers = 0` is not working for you is that this argument is not passed to `MoleculeDataLoader` during interpretation [here](https://github.com/chemprop/chemprop/blob/1785627d714c17f910af921fe518db76f4892026/chemprop/interpret.py#L59), whereas it is passed to `MoleculeDataLoader` during [training](https://github.com/chemprop/chemprop/blob/1785627d714c17f910af921fe518db76f4892026/chemprop/train/run_training.py#L238), [prediction](https://github.com/chemprop/chemprop/blob/1785627d714c17f910af921fe518db76f4892026/chemprop/train/make_predictions.py#L92), and [fingerprinting](https://github.com/chemprop/chemprop/blob/1785627d714c17f910af921fe518db76f4892026/chemprop/train/molecule_fingerprint.py#L87). I can open a quick PR to fix this.

**Comment by llzhu** [comment]
Thanks, Kevin.
Can you make the changes available on Pypi?
I tried to upgrade from github, but got
ERROR: Package 'chemprop' requires a different Python: 3.9.7 not in '<3.9,>=3.7'

I am using Python 3.9.7, I do not have issue upgrading chemprop from Pypi.

Thanks.  -Leiming

**Comment by kevingreenman** [comment]
The change will be reflected on PyPI once we merge the PR and after we release v1.7.0. However, the v1.7.0 PyPI release will also include this Python version restriction that you are seeing while installing from source (introduced in #618). Chemprop v1 no longer supports python versions outside of the `<3.9,>=3.7` range. I suggest rebuilding your environment using python 3.8.

**Comment by llzhu** [comment]
Hi Kevin - Sorry to bother again. I installed chemprop from github master (your changes have been merged to master, right?). Now the error (multiprocessing_context option should specify a valid start method in ['spawn'], but got multiprocessing_context='forkserver') goes away. But the output of interpret is None. The codes are as below:

interpret_arguments = [
        '--data_path', os.path.join(test_checkpoints_req_user, 'fold_0/test_smiles.csv'),
        '--checkpoint_dir', os.path.join(test_checkpoints_req_user, 'fold_0')
    ]
    interpret_args = chemprop.args.InterpretArgs().parse_args(interpret_arguments)

    interpret_args.num_workers = 0
    interpret_out = chemprop.interpret.interpret(args=interpret_args)

I just wanted to interpret the classification of the test mols in test_smiles.csv. I got None for interpret_out.  test_smiles.csv is just a list of SMILES with 'SMILES' as header (I can predicate correctly with the file). Am I doing the interpret correctly?

**Comment by kevingreenman** [comment]
You're correct that the [interpret function](https://github.com/chemprop/chemprop/blob/76d59ffb0096d96e92c6b7a5072ef95bdc2e883d/chemprop/interpret.py#L298) doesn't return anything (`interpret_out` should be `None` in your script). It should be printing out the results for you from [this line](https://github.com/chemprop/chemprop/blob/76d59ffb0096d96e92c6b7a5072ef95bdc2e883d/chemprop/interpret.py#L345).

**Comment by llzhu** [comment]
Got it. Thank you so much!
To make the interpret function applicable to more scenarios,  I think is is helpful for interpret function to return list of [smiles, score, rational_smiles, rational_score], similar as the output of make_predictions.  I made a function interpret_2 that return the list to accommodate my situation.
Some observations/questions:
1) rationales could be empty even though the mol is predicated positive (1)
2) I still get lots of 'warning?'
          Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9
    although I already kekulized all input mols. I still get the interpretation despite the 'warnings'
3) What rational_score really means?

Thanks a ton!!!

**Comment by kevingreenman** [comment]
Thanks for the suggestion. We're not currently planning to make any more updates to chemprop v1, but we'll take this into consideration for when we [implement](https://github.com/chemprop/chemprop/issues/614) the interpret function in v2.1. 

1. I think this would happen if none of the substructures have a score greater than `prop_delta`. I guess this would happen if none of the substructures on their own produce a property like that of the full molecule.
2. I'm not sure what would cause this.
3. The `rationale_score` is the predicted property of the substructure on its own. The idea is that if a substructure has a high predicted property (e.g. toxicity) when the other parts of the molecule are removed, then that substructure is a "rationale" for why the full molecule has the high property value.
