### ISSUE TITLE
[Question] run hyperopt in parallel over multiple GPUS?

### ISSUE THREAD

**Issue by GMdSilva** [chemprop/chemprop#70]
Hello,

First of all, thanks so much for chemprop. I'm an absolute newbie in statistical learning but your software is so easy to run and to understand the output. My background is entirely on biochemistry so I really appreciate the verbosity and the ease of use. 

Now for my actual question, I have access to an HPC cluster with 8 gpu nodes (tesla v100) and I wanted to run hyperparameter opt in parallel. Is that something that (a) makes sense and (b) is possible? If so, is there an implementation that I can port or can you point me towards where I should look at to implement it myself? When I submit an hyperopt job to our slurm queue it runs in sequential form on one GPU even if I change the number of works (perhaps I misunderstood what this parameter does).

Thanks again!

**Comment by davidegraff** [comment]
the num_workers argument is how many processes the MoleculeDataLoader will parallelize BatchMolGraph preparation over. It is not related to how many 'jobs' it should be running in parallel. Chemprop is not written with distributed setups in mind, and thus cannot make use of multiple GPUs internally. What you can do instead is to launch several hyperoptimization jobs on your cluster as the same time to externally parallelize this step.

You should look up your cluster's architecture to determine the proper number of workers to select and cores to request. For example, if your GPU nodes have 32 cores each and 4 GPUs, you should request 8 cores and 1 GPU per job, so as to maximize the amount of work that any one node can perform.

**Comment by swansonk14** [comment]
Hi @GMdSilva, thank you for the question and I'm so glad you've liked using Chemprop! That's a great question but unfortunately we don't currently support training or hyperparameter optimization across multiple GPUs. @davidegraff's answer is great and captures the best solution currently. I hope that helps and please let us know if you have any other questions!
