### ISSUE TITLE
[Question] neither output nor error reported when interpreting model prediction 

### ISSUE THREAD

**Issue by qianqing-xu** [chemprop/chemprop#71]
Hello,

I've run interpret.py to interpret the model prediction with the Windows computer. But I didn't get any output, and there was no error reported, during running the script. 
I think RAM is enough because there were only 100 SMILES strings in the file. 
What might be the reasons for that?

Thanks in advance.

**Comment by swansonk14** [comment]
Hi @qianqing-xu, thank you for the question! `interpret.py` should print a bunch of results to the screen. When you run it you don't see anything at all? Can you send the exact commands you ran? Offhand I'm not entirely sure what the issue might be, but I can try to reproduce the problem with the commands you send.
