### ISSUE TITLE
[BUG]: v2 Error on training example:  `TypeError: Cannot convert a MPS Tensor to float64 dtype.`

### ISSUE THREAD

**Issue by JamesHWade** [chemprop/chemprop#711]
Thanks for all the hard work on v2. I've been watching all the buzz in the repo, and I know you are putting in an incredible amount of effort. Thank you!

**Describe the bug**

I'm attempting to run the `trainings.ipynb` example notebook `examples/` folder. I get the following error on an M1 MBP.

`TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.`

The error occurs with 

```python
trainer.fit(mpnn, train_loader, val_loader)
```

<details>
  <summary> Here is the full traceback if that helps. </summary>

```python
{
	"name": "TypeError",
	"message": "Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.",
	"stack": "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[21], line 1
----> 1 trainer.fit(mpnn, train_loader, val_loader)

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py:544, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    542 self.state.status = TrainerStatus.RUNNING
    543 self.training = True
--> 544 call._call_and_handle_interrupt(
    545     self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    546 )

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py:44, in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     42     if trainer.strategy.launcher is not None:
     43         return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
---> 44     return trainer_fn(*args, **kwargs)
     46 except _TunerExitException:
     47     _call_teardown_hook(trainer)

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py:580, in Trainer._fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    573 assert self.state.fn is not None
    574 ckpt_path = self._checkpoint_connector._select_ckpt_path(
    575     self.state.fn,
    576     ckpt_path,
    577     model_provided=True,
    578     model_connected=self.lightning_module is not None,
    579 )
--> 580 self._run(model, ckpt_path=ckpt_path)
    582 assert self.state.stopped
    583 self.training = False

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py:963, in Trainer._run(self, model, ckpt_path)
    960 self._logger_connector.reset_metrics()
    962 # strategy will configure model and move it to the device
--> 963 self.strategy.setup(self)
    965 # hook
    966 if self.state.fn == TrainerFn.FITTING:

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/pytorch/strategies/strategy.py:155, in Strategy.setup(self, trainer)
    152 # let the precision plugin convert the module here so that this strategy hook can decide the order
    153 # of operations
    154 self.model = self.precision_plugin.convert_module(self.model)
--> 155 self.model_to_device()
    156 self.model = self._setup_model(self.model)
    158 if trainer.state.fn == TrainerFn.FITTING:

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/pytorch/strategies/single_device.py:79, in SingleDeviceStrategy.model_to_device(self)
     76 @override
     77 def model_to_device(self) -> None:
     78     assert self.model is not None, \"self.model must be set before self.model.to()\"
---> 79     self.model.to(self.root_device)

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/fabric/utilities/device_dtype_mixin.py:55, in _DeviceDtypeModuleMixin.to(self, *args, **kwargs)
     53 device, dtype = torch._C._nn._parse_to(*args, **kwargs)[:2]
     54 _update_properties(self, device=device, dtype=dtype)
---> 55 return super().to(*args, **kwargs)

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py:1152, in Module.to(self, *args, **kwargs)
   1148         return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
   1149                     non_blocking, memory_format=convert_to_format)
   1150     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
-> 1152 return self._apply(convert)

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py:802, in Module._apply(self, fn, recurse)
    800 if recurse:
    801     for module in self.children():
--> 802         module._apply(fn)
    804 def compute_should_use_set_data(tensor, tensor_applied):
    805     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    806         # If the new tensor has compatible tensor type as the existing tensor,
    807         # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    812         # global flag to let the user control whether they want the future
    813         # behavior of overwriting the existing tensor or not.

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py:849, in Module._apply(self, fn, recurse)
    847 for key, buf in self._buffers.items():
    848     if buf is not None:
--> 849         self._buffers[key] = fn(buf)
    851 return self

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py:1150, in Module.to.<locals>.convert(t)
   1147 if convert_to_format is not None and t.dim() in (4, 5):
   1148     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
   1149                 non_blocking, memory_format=convert_to_format)
-> 1150 return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead."
}
```
</details>

**Environment**
- Python 3.11.8
- Packages: 
    <details>
    Package                      Version         Editable project location
    ---------------------------- --------------- ----------------------------
    absl-py                      2.1.0
    aimsim_core                  2.1.3
    aiohttp                      3.9.3
    aiosignal                    1.3.1
    anyio                        4.2.0
    appnope                      0.1.4
    argon2-cffi                  23.1.0
    argon2-cffi-bindings         21.2.0
    arrow                        1.3.0
    astartes                     1.2.2
    asttokens                    2.4.1
    astunparse                   1.6.3
    async-lru                    2.0.4
    attrs                        23.2.0
    Babel                        2.14.0
    beautifulsoup4               4.12.3
    bleach                       6.1.0
    cachetools                   5.3.2
    certifi                      2024.2.2
    cffi                         1.16.0
    charset-normalizer           3.3.2
    chemprop                     2.0.0rc1
    comm                         0.2.1
    contourpy                    1.2.0
    cycler                       0.12.1
    debugpy                      1.8.0
    decorator                    5.1.1
    deepchem                     2.5.0
    defusedxml                   0.7.1
    dill                         0.3.8
    executing                    2.0.1
    fastjsonschema               2.19.1
    filelock                     3.13.1
    flatbuffers                  23.5.26
    fonttools                    4.48.1
    fqdn                         1.5.1
    frozenlist                   1.4.1
    fsspec                       2024.2.0
    gast                         0.5.4
    google-auth                  2.27.0
    google-auth-oauthlib         1.2.0
    google-pasta                 0.2.0
    grpcio                       1.60.1
    h11                          0.14.0
    h5py                         3.10.0
    httpcore                     1.0.2
    httpx                        0.26.0
    idna                         3.6
    ipykernel                    6.29.2
    ipython                      8.21.0
    ipywidgets                   8.1.2
    isoduration                  20.11.0
    jedi                         0.19.1
    Jinja2                       3.1.3
    joblib                       1.3.2
    json5                        0.9.14
    jsonpointer                  2.4
    jsonschema                   4.21.1
    jsonschema-specifications    2023.12.1
    jupyter                      1.0.0
    jupyter_client               8.6.0
    jupyter-console              6.6.3
    jupyter_core                 5.7.1
    jupyter-events               0.9.0
    jupyter-lsp                  2.2.2
    jupyter_server               2.12.5
    jupyter_server_terminals     0.5.2
    jupyterlab                   4.1.0
    jupyterlab_pygments          0.3.0
    jupyterlab_server            2.25.2
    jupyterlab_widgets           3.0.10
    keras                        2.15.0
    kiwisolver                   1.4.5
    libclang                     16.0.6
    lightning                    2.2.1
    lightning-utilities          0.10.1
    llvmlite                     0.42.0
    Markdown                     3.5.2
    MarkupSafe                   2.1.5
    matplotlib                   3.8.2
    matplotlib-inline            0.1.6
    mhfp                         1.9.6
    mistune                      3.0.2
    ml-dtypes                    0.2.0
    mordredcommunity             2.0.5
    mpmath                       1.3.0
    multidict                    6.0.5
    multiprocess                 0.70.16
    nbclient                     0.9.0
    nbconvert                    7.16.0
    nbformat                     5.9.2
    nest-asyncio                 1.6.0
    networkx                     3.2.1
    notebook                     7.0.7
    notebook_shim                0.2.3
    numba                        0.59.0
    numpy                        1.26.4
    oauthlib                     3.2.2
    opt-einsum                   3.3.0
    overrides                    7.7.0
    packaging                    23.2
    padelpy                      0.1.16
    pandas                       2.2.0
    pandocfilters                1.5.1
    parso                        0.8.3
    pexpect                      4.9.0
    pillow                       10.2.0
    pip                          24.0
    platformdirs                 4.2.0
    prometheus-client            0.19.0
    prompt-toolkit               3.0.43
    protobuf                     4.23.4
    psutil                       5.9.8
    ptyprocess                   0.7.0
    pure-eval                    0.2.2
    pyasn1                       0.5.1
    pyasn1-modules               0.3.0
    pycparser                    2.21
    Pygments                     2.17.2
    pynndescent                  0.5.11
    pyparsing                    3.1.1
    python-dateutil              2.8.2
    python-json-logger           2.0.7
    pytorch-lightning            2.2.1
    pytz                         2024.1
    PyYAML                       6.0.1
    pyzmq                        25.1.2
    qtconsole                    5.5.1
    QtPy                         2.4.1
    quarto                       0.1.0
    rdkit                        2023.9.4
    referencing                  0.33.0
    requests                     2.31.0
    requests-oauthlib            1.3.1
    rfc3339-validator            0.1.4
    rfc3986-validator            0.1.1
    rpds-py                      0.17.1
    rsa                          4.9
    scikit-learn                 1.4.0
    scikit-learn-extra           0.3.0
    scipy                        1.12.0
    seaborn                      0.13.2
    Send2Trash                   1.8.2
    setuptools                   69.0.3
    six                          1.16.0
    sniffio                      1.3.0
    soupsieve                    2.5
    stack-data                   0.6.3
    substance-of-concern-phase3  0.0.1+editable  /Users/ua21849/Documents/SoC
    sympy                        1.12
    tabulate                     0.9.0
    tensorboard                  2.15.1
    tensorboard-data-server      0.7.2
    tensorflow                   2.15.0
    tensorflow-estimator         2.15.0
    tensorflow-io-gcs-filesystem 0.36.0
    tensorflow-macos             2.15.0
    termcolor                    2.4.0
    terminado                    0.18.0
    threadpoolctl                3.2.0
    tinycss2                     1.2.1
    torch                        2.2.0
    torch-scatter                2.1.2
    torchmetrics                 1.3.1
    tornado                      6.4
    tqdm                         4.66.2
    traitlets                    5.14.1
    types-python-dateutil        2.8.19.20240106
    typing_extensions            4.9.0
    tzdata                       2023.4
    umap-learn                   0.5.5
    uri-template                 1.3.0
    urllib3                      2.2.0
    wcwidth                      0.2.13
    webcolors                    1.13
    webencodings                 0.5.1
    websocket-client             1.7.0
    Werkzeug                     3.0.1
    wheel                        0.42.0
    widgetsnbextension           4.0.10
    wrapt                        1.14.1
    yarl                         1.9.4
    </details>

- MacOS 14.2.1 (23C71)

**Checklist**
- [x] all dependencies are satisifed: `conda list` shows the packages listed in the `README`
- [ ] the unit tests are working: `pytest -v` reports no errors

**Comment by JacksonBurns** [comment]
@JamesHWade thanks!

Can you add this to the top of the notebook:
```
import torch

torch.set_default_dtype(torch.float32)
```
And restart + re-run the entire thing?

If this does not work I will poke around in the source code locally and try and set float32 within `chemprop` itself.

I suspect that the apple gpus are not working with float64, which `chemprop` is using (for some reason).
This is based on what I found [here](https://github.com/pytorch/pytorch/issues/78168#issuecomment-1241586809).

**Comment by JamesHWade** [comment]
No luck. I'll try a few other permutations to see if I can get it to work.

**Comment by JamesHWade** [comment]
Changing `accelerator="cpu"` works for the examples, but using the GPU would be great.

**Comment by davidegraff** [comment]
what happens if you just create your `MPNN` and try and move it to MPS: `model.to(device="mps")`?

**Comment by JamesHWade** [comment]
Same error

<img width="1053" alt="image" src="https://github.com/chemprop/chemprop/assets/6314313/03d340b2-ceb5-479e-b83c-a4f18e3a570f">

**Comment by davidegraff** [comment]
and what about a base `torch` module: `nn.Linear(10, 1).to(device="mps")`?

**Comment by davidegraff** [comment]
can you share a snippet of how you're building your `MPNN`? I have no problems on my mac (2023 M2) using `torch==2.0.1`:
```python
import torch
torch.backends.mps.is_built()
# True
import chemprop.models
import chemprop.nn
mp = chemprop.nn.message_passing.BondMessagePassing()
agg = chemprop.nn.agg.SumAggregation()
pred = chemprop.nn.predictors.RegressionFFN()
mpnn = chemprop.models.MPNN(mp, agg, pred)
mpnn.to('mps')
# MPNN(
#   (message_passing): BondMessagePassing(
#     (W_i): Linear(in_features=147, out_features=300, bias=False)
#     (W_h): Linear(in_features=300, out_features=300, bias=False)
#     (W_o): Linear(in_features=433, out_features=300, bias=True)
#     (dropout): Dropout(p=0, inplace=False)
#     (tau): ReLU()
#   )

**Comment by JamesHWade** [comment]
```python
import torch
torch.backends.mps.is_built()
import chemprop.models
import chemprop.nn
mp = chemprop.nn.message_passing.BondMessagePassing()
agg = chemprop.nn.agg.SumAggregation()
pred = chemprop.nn.predictors.RegressionFFN()
mpnn = chemprop.models.MPNN(mp, agg, pred)
mpnn.to('mps')
# MPNN(
#   (message_passing): BondMessagePassing(
#     (W_i): Linear(in_features=147, out_features=300, bias=False)
#     (W_h): Linear(in_features=300, out_features=300, bias=False)
#     (W_o): Linear(in_features=433, out_features=300, bias=True)
#     (dropout): Dropout(p=0, inplace=False)
#     (tau): ReLU()
#   )
#   (agg): SumAggregation()
#   (bn): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
#   (predictor): RegressionFFN(
#     (ffn): MLP(
#       (0): Linear(in_features=300, out_features=300, bias=True)
#       (1): ReLU()
#       (2): Dropout(p=0, inplace=False)
#       (3): Linear(in_features=300, out_features=1, bias=True)
#     )
#   )
# )
```

To get the error, I'm running the `examples/training.ipynb` as is.

Here's what the network looks like:

```python
mpnn = models.MPNN(mp, agg, ffn, batch_norm, metric_list)
mpnn
# MPNN(
#   (message_passing): BondMessagePassing(
#     (W_i): Linear(in_features=147, out_features=300, bias=False)
#     (W_h): Linear(in_features=300, out_features=300, bias=False)
#     (W_o): Linear(in_features=433, out_features=300, bias=True)
#     (dropout): Dropout(p=0, inplace=False)
#     (tau): ReLU()
#   )
#   (agg): MeanAggregation()
#   (bn): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
#   (predictor): RegressionFFN(
#     (ffn): MLP(
#       (0): Linear(in_features=300, out_features=300, bias=True)
#       (1): ReLU()
#       (2): Dropout(p=0, inplace=False)
#       (3): Linear(in_features=300, out_features=1, bias=True)
#     )
#   )
# )
```

Here's where the error shows up:

```python
trainer = pl.Trainer(
    logger=False,
    enable_checkpointing=True, # Use `True` if you want to save model checkpoints. The checkpoints will be saved in the `checkpoints` folder.
    enable_progress_bar=True,
    accelerator="auto",
    devices=1,
    max_epochs=20, # number of epochs to train for
)

trainer.fit(mpnn, train_loader, val_loader)
```

Here the full stack trace if your interested:

<details>
{
	"name": "TypeError",
	"message": "Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.",
	"stack": "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[62], line 10
      1 trainer = pl.Trainer(
      2     logger=False,
      3     enable_checkpointing=True, # Use `True` if you want to save model checkpoints. The checkpoints will be saved in the `checkpoints` folder.
   (...)
      7     max_epochs=20, # number of epochs to train for
      8 )
---> 10 trainer.fit(mpnn, train_loader, val_loader)

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py:543, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    541 self.state.status = TrainerStatus.RUNNING
    542 self.training = True
--> 543 call._call_and_handle_interrupt(
    544     self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    545 )

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py:44, in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     42     if trainer.strategy.launcher is not None:
     43         return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
---> 44     return trainer_fn(*args, **kwargs)
     46 except _TunerExitException:
     47     _call_teardown_hook(trainer)

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py:579, in Trainer._fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    572 assert self.state.fn is not None
    573 ckpt_path = self._checkpoint_connector._select_ckpt_path(
    574     self.state.fn,
    575     ckpt_path,
    576     model_provided=True,
    577     model_connected=self.lightning_module is not None,
    578 )
--> 579 self._run(model, ckpt_path=ckpt_path)
    581 assert self.state.stopped
    582 self.training = False

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py:962, in Trainer._run(self, model, ckpt_path)
    959 self._logger_connector.reset_metrics()
    961 # strategy will configure model and move it to the device
--> 962 self.strategy.setup(self)
    964 # hook
    965 if self.state.fn == TrainerFn.FITTING:

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/pytorch/strategies/strategy.py:155, in Strategy.setup(self, trainer)
    152 # let the precision plugin convert the module here so that this strategy hook can decide the order
    153 # of operations
    154 self.model = self.precision_plugin.convert_module(self.model)
--> 155 self.model_to_device()
    156 self.model = self._setup_model(self.model)
    158 if trainer.state.fn == TrainerFn.FITTING:

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/pytorch/strategies/single_device.py:79, in SingleDeviceStrategy.model_to_device(self)
     76 @override
     77 def model_to_device(self) -> None:
     78     assert self.model is not None, \"self.model must be set before self.model.to()\"
---> 79     self.model.to(self.root_device)

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/lightning/fabric/utilities/device_dtype_mixin.py:55, in _DeviceDtypeModuleMixin.to(self, *args, **kwargs)
     53 device, dtype = torch._C._nn._parse_to(*args, **kwargs)[:2]
     54 _update_properties(self, device=device, dtype=dtype)
---> 55 return super().to(*args, **kwargs)

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py:1152, in Module.to(self, *args, **kwargs)
   1148         return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
   1149                     non_blocking, memory_format=convert_to_format)
   1150     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
-> 1152 return self._apply(convert)

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py:802, in Module._apply(self, fn, recurse)
    800 if recurse:
    801     for module in self.children():
--> 802         module._apply(fn)
    804 def compute_should_use_set_data(tensor, tensor_applied):
    805     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    806         # If the new tensor has compatible tensor type as the existing tensor,
    807         # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    812         # global flag to let the user control whether they want the future
    813         # behavior of overwriting the existing tensor or not.

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py:849, in Module._apply(self, fn, recurse)
    847 for key, buf in self._buffers.items():
    848     if buf is not None:
--> 849         self._buffers[key] = fn(buf)
    851 return self

File ~/Documents/SoC/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py:1150, in Module.to.<locals>.convert(t)
   1147 if convert_to_format is not None and t.dim() in (4, 5):
   1148     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
   1149                 non_blocking, memory_format=convert_to_format)
-> 1150 return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead."
}
</details
