### ISSUE TITLE
sklearn_train on chemprop

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#713]
Hello,
I was wondering if you have an example how to use sklearn_train and sklearn_predict through chemprop.

Thank you
Best Regards
Soodabeh

**Comment by JacksonBurns** [comment]
Hi @SoodabehGhaffari we have two documentation pages related to the `sklearn_*` commands [here](https://chemprop.readthedocs.io/en/latest/tutorial.html#missing-target-values) and [here](https://chemprop.readthedocs.io/en/latest/sklearn.html), though we do not have any full examples of using the commands. In general though they are very similar to Chemprop, so you should be able to follow some of our other tutorials and swap out `chemprop_train` with `sklearn_train`. The command line argument parser should let you know where you go wrong.

Additionally, we are currently moving toward a v2 release of Chemprop and this feature is _not_ being carried forward. If you want to continue training baseline models in the future, you want to look at other repos like https://github.com/MolecularAI/Qptuna or https://github.com/deepchem/deepchem
