### ISSUE TITLE
[TODO]: v2 `--show-individual-scores` implementation

### ISSUE THREAD

**Issue by shihchengli** [chemprop/chemprop#719]
Add `--show-individual-scores` to show all scores for individual targets.

**Comment by davidegraff** [comment]
what's this CLI flag intended to do?

**Comment by kevingreenman** [comment]
The predictions of each model in a directory are currently saved as separate files and not automatically averaged. In v2.1 (as part of the other uncertainty functionality in #473 ), we will add this flag so the averaging and std dev is done by default, and the flag will allow for saving the individual scores as well as the averages.

**Comment by JacksonBurns** [comment]
@kevingreenman do we just want to _always_ save the individual scores?

**Comment by kevingreenman** [comment]
> @kevingreenman do we just want to _always_ save the individual scores?

I wouldn't be opposed to that.
