### ISSUE TITLE
[QUESTION]: how to add atom-level features

### ISSUE THREAD

**Issue by tom832** [chemprop/chemprop#728]
**What are you trying to do?**
I am gonna add atom level features to chemprop model for classification task of a molecule.
For each molecule smiles, I have generate a atom-level feature dataframe with shape (n, 100), where n is the number of atoms, and 100 is the atom features I extracted with other tools.
How can I save a npz file  or pkl file to store my features? 

**Previous attempts**
I have tried to convert dataframe to numpy array with shape (n, 100), and then I am not able to ensemble these arrays into one 3D array due to different shape of each molecule array.

**Screenshots**
Can anyone give an example of atom-level feature files, thx a lot!

**Comment by kevingreenman** [comment]
Hi @tom832, are you using chemprop v1? If so, please refer to pages 5-7 of our [paper SI](https://pubs.acs.org/doi/suppl/10.1021/acs.jcim.3c01250/suppl_file/ci3c01250_si_001.pdf) for information on the format of these features.

**Comment by tom832** [comment]
> Hi @tom832, are you using chemprop v1? If so, please refer to pages 5-7 of our [paper SI](https://pubs.acs.org/doi/suppl/10.1021/acs.jcim.3c01250/suppl_file/ci3c01250_si_001.pdf) for information on the format of these features.

THX，I am trying with v1, and it looks working well in Training.

Then I am wondering how to do interpretation with atom-level and molecule-level features which are generated before training/prediction. I found it was not available in document of v1, and only support feature_generator.
So, can I interpret manually ?  Will this be available in v2 ?

**Comment by kevingreenman** [comment]
The interpret function accepts arguments specified in [`InterpretArgs`](https://github.com/chemprop/chemprop/blob/97c03cb658be4081bbc4e8655e6670eff80d26a4/chemprop/args.py#L1042) as well as those specified in [`CommonArgs`](https://github.com/chemprop/chemprop/blob/97c03cb658be4081bbc4e8655e6670eff80d26a4/chemprop/args.py#L66), which `InterpretArgs` inherits from.

However, the interpret function [does not currently work](https://github.com/chemprop/chemprop/blob/97c03cb658be4081bbc4e8655e6670eff80d26a4/chemprop/interpret.py#L35) with atom or bond features/descriptors. 

I'm not sure what you mean by "interpret manually".

We plan to add the interpret function in v2.1 in late 2024.

**Comment by kevingreenman** [comment]
Closing this issue for now, please feel free to reopen if you have more questions.
