### ISSUE TITLE
Question: How to use chemprop to convert SMILES into chemprop fingerprints only?

### ISSUE THREAD

**Issue by jamesymwang** [chemprop/chemprop#735]
I would like to use your pre-trained model to convert SMILES into Chemprop fingerprints. I am working on predicting Kp for free radical polymerization. However, traditional methods like MACCS fingerprints result in the same molecular fragments when the ester side chains are too long, such as heptadecyl and eicosyl. Consequently, the resulting arrays are also identical. I believe your conversion method can solve this problem. 
Due to being a beginner in machine learning, I have been unsuccessful in finding the necessary files to download the pre-trained model on GitHub, as shown in the attempts below. Can you help me resolve this issue?
![question](https://github.com/chemprop/chemprop/assets/153181410/f9bfc971-a56a-491b-b099-f51b43ee01f8)

**Comment by kevingreenman** [comment]
Hi @jamesymwang, there is no pretrained model available for anyone to download. Chemprop is a package that provides the architecture for building, training, and testing your own models on your own data. If you want to get fingerprints for you data, you can do so using the instructions [here](https://github.com/chemprop/chemprop?tab=readme-ov-file#encode-fingerprint-latent-representation), but you will need to train a model on your dataset first. If you have a small dataset or your model isn't very good at predicting your target, then your fingerprints probably won't be very good quality either.

**Comment by kevingreenman** [comment]
By the way, if you're using chemprop within Python scripts, you may find it easier to try our [v2 release candidate](https://github.com/chemprop/chemprop/releases/tag/v2.0.0-rc.1), which offers much easier Python scripting than Chemprop v1.
