### ISSUE TITLE
overfitting in the ensemble of models

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#739]
Hello,
I trained a model using chemprop with hyperparameter tuning and realized one model outperforms an ensemble of models. It shows that overfitting is happening. How can I prevent overfitting in ensembles? Should I increase the number of ensemble size? Currently, I am using 5 models in the ensemble.

Detailed information about the model: It is a classification model with norm aggregation and 50 epochs. Train, validation and tests are predefined.

I appreciate your help.

Best Regards
Soodabeh

**Comment by shihchengli** [comment]
Usually, an ensemble of models can yield a lower prediction error than a single model. However, this is not always guaranteed, as you encountered. The result still depends on the dataset and hyperparameters used during model training. Chemprop would select the model with the lowest validation error as the final model, so overfitting is not supposed to be an issue. Increasing the ensemble size might help.
