### ISSUE TITLE
 aggregation type 

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#743]
Hello,
I reviewed that in all the benchmarks the aggregation "norm" has been used. I was wondering why you selected to have "norm" aggregation instead of the default one.

Best Regards
Soodabeh

**Comment by shihchengli** [comment]
Based on the experience of training Chemprop models within our group, we believe that the `norm` aggregation is more likely to yield better models in many cases. Of course, it depends on the specific problem at hand, so you might consider it as a hyperparameter during HPO.
