### ISSUE TITLE
[QUESTION]: Hyperparameter optimisation in v2

### ISSUE THREAD

**Issue by Rhys-McAlister** [chemprop/chemprop#744]
Hi, I can see that hyperparameter optimisation is a planned feature at some point but for the mean time is there an recommended approach for optimising the various hyper parameters?

**Comment by JacksonBurns** [comment]
No.

You can try manually tuning them, or you can use V1 hyperparameter optimization and re-use the optimized parameters in V2. The latter should have similar performance, though you may want to do some additional manual tuning.

PR #734 will implement the first pass at hyperparameter optimization in V2, and once it is merged you can either try the v2/dev branch or wait for the next release candidate (or just try that development branch now, if you want).
