### ISSUE TITLE
Risk of insufficient memory when using huge training set

### ISSUE THREAD

**Issue by yanfeiguan** [chemprop/chemprop#75]
https://github.com/chemprop/chemprop/blob/71e5e86db15df10bbdbb672f8b06dd574f93f6eb/chemprop/data/data.py#L61

generating a RDKit molecule object for each datapoint during data loading may use lots of memory when training on a huge training set. I trained on 5M molecules, and when trained on a machine with 120G memory, the memory is insufficient with 8 workers. Probably need to allow molecule generating in the Dataloader.

**Comment by swansonk14** [comment]
Hi @yanfeiguan, that's a great idea! I just implemented it in this commit: https://github.com/chemprop/chemprop/commit/a321542b3035140413179c8e3b88fa7c43f14836. Now you can add `--no_cache_mol` to prevent caching of the RDKit molecule.
