### ISSUE TITLE
using multiple GPUs for speeding up chemprop hyperparameter optimization

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#750]
Hello
I am doing hyperparameter optimization with 10 fold cross validation data splitting. With one Gput, it has been running for more than a week. To accelerate the process,  I changed the number of GPU in my slurm job to 4, however, it only uses one GPU. What changes should I make to be able to use multiple GPUs?

Thank you
Best Regards
Soodabeh

**Comment by JacksonBurns** [comment]
Hi @SoodabehGhaffari Chemprop v1 can only run on 1 GPU regardless of how many are available due to internal programming limitations. The upcoming v2.0.0 release will support distributed multi-GPU training and hyperparameter optimization, and you can track the progress towards its release on #517.
