### ISSUE TITLE
using pretraining in chemprop

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#756]
Hello,
I have a model using Chemprop for a big dataset and I would like to do transfer learning using "Pretraining" flag of chemprop for a related small dataset. Based on Chemprop, there are three ways to do transfer learning: 1- Initialization, 2- Freezing D-MPNN, and 3-  Freezing D-MPNN + Freezing n FFN
My questions are about implementing the second and the third approach:
For the second approach, should I add both flags --checkpoint_dir and --checkpoint_frzn and provide the same path (path of pre-trained model) for both flags? Or do I need to use only --checkpoint_frzn?

I have a similar question for the third approach, should I add three flags --checkpoint_dir, --checkpoint_frzn and --frzn_ffn_layers and provide the same path for three flags? In this approach, my understanding is we are using the same model as the pre-trained model with the same architecture and same parameters and we are just running for a different dataset.

Do you know any paper that used Chemprop pretraining?

I really appreciate your help.

Best Regards
Soodabeh

**Comment by shihchengli** [comment]
In both the second and third cases, only the `checkpoint_frzn` flag needs to be used. For the third case, the `frzn_ffn_layers` flag is used to determine how many layers in the readout you want to freeze; therefore, the input to this argument should be an integer, not a path to a model.

Below are some papers that used transfer learning with D-MPNN:
1. https://doi.org/10.1039/D3SC05353A
2. https://doi.org/10.1021/acs.jpca.2c02614
3. https://doi.org/10.1021/acs.jcim.3c00546
4. https://doi.org/10.1021/jacs.2c01768

Hope that helps!
