### ISSUE TITLE
Missing schema.sql when installing from PyPi

### ISSUE THREAD

**Issue by vinhtq115** [chemprop/chemprop#77]
I followed the Option 1 in Installation and it threw this error:

```
(graphNN) vinhtq115@Dell-G7-7588:~/PycharmProjects/graphNN$ chemprop_web
Traceback (most recent call last):
  File "/home/vinhtq115/anaconda3/envs/graphNN/bin/chemprop_web", line 8, in <module>
    sys.exit(chemprop_web())
  File "/home/vinhtq115/anaconda3/envs/graphNN/lib/python3.8/site-packages/chemprop/web/run.py", line 39, in chemprop_web
    run_web(args=WebArgs().parse_args())
  File "/home/vinhtq115/anaconda3/envs/graphNN/lib/python3.8/site-packages/chemprop/web/run.py", line 28, in run_web
    db.init_db()
  File "/home/vinhtq115/anaconda3/envs/graphNN/lib/python3.8/site-packages/chemprop/web/app/db.py", line 30, in init_db
    with current_app.open_resource('schema.sql') as f:
  File "/home/vinhtq115/anaconda3/envs/graphNN/lib/python3.8/site-packages/flask/helpers.py", line 1114, in open_resource
    return open(os.path.join(self.root_path, resource), mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vinhtq115/anaconda3/envs/graphNN/lib/python3.8/site-packages/chemprop/web/app/schema.sql'
```

It seems that the file is not in the folder. Executing `ls` in the `/home/vinhtq115/anaconda3/envs/graphNN/lib/python3.8/site-packages/chemprop/web/app/` returns these files and folders:
`db.py  __init__.py  __pycache__  views.py  web_checkpoints  web_data`

Update: I executed `chemprop_web` again and this time, it showed Flask running but accessing `http://127.0.0.1:5000` returns HTTP error 500.

**Comment by swansonk14** [comment]
Hi @vinhtq115, thanks for reporting the issue! The `schema.sql` file should be there since it's included in Chemprop: https://github.com/chemprop/chemprop/blob/master/chemprop/web/app/schema.sql. What happens when you try running `python web.py` instead of `chemprop_web`? Do you get the same issue?

**Comment by swansonk14** [comment]
Actually I just realized that you said you installed through PyPi not from source. Can you try installing from source and running both `chemprop_web` and `python web.py` to see if they work? That might help determine whether it's an issue with the PyPi installation or a more general issue with the website.

**Comment by vinhtq115** [comment]
I installed from source and everything was fine. Only the one from PyPi have issue.

**Comment by swansonk14** [comment]
Thanks for checking! It looks like `schema.sql` was not included on the package that was uploaded to PyPI and that's causing the problem. I'll make sure that it's included on our next release so that the web version will work from PyPI too. Thanks again for catching the issue!
