### ISSUE TITLE
[TODO]: Standardize PR merge procedure.

### ISSUE THREAD

**Issue by oscarwumit** [chemprop/chemprop#771]
**Notes**
We should standardize the way we merge PR. I vote for rebase before merging, but currently we do not have a consistent way of merging PR so we see a mix of rebase/squash/direct merge.

**Comment by davidegraff** [comment]
whats wrong with:
```
$ git merge origin v2/dev
$ git push BRANCH
```
prior to merging

**Comment by oscarwumit** [comment]
I am thinking of rebase to consolidate similar changes to single commit before finally merging a PR.

For example, in the recent PR we were overhauling the atom featurizers, the same files have been changed over and over again in different commits when we were discussing and reviewing the changes. Without a rebase, this will end up with multiple commits that is hard to track for later on. With rebase, we can group similar changes together and that is usually cleaner.

**Comment by oscarwumit** [comment]
In addition, we should consider remove branches on chemprop main repo, forbid direct push to create new ones, and ask people in general to fork and PR from their forked version.

**Comment by davidegraff** [comment]
re: rebase vs. merge

why not just squash commit? Many PRs will involve a ton of commits that really don't contribute anything of value to the commit history, e.g., make change A, make change B, revert change A, refactor change B, ultimately decide on change C. This collaboration pattern happens frequently, and this history doesn't add much to the repo because it lacks the context, which itself can be found back on the PR. So either you have all of the commits without context and go to the PR to get it, or you have none of the noisy commits and must go to the PR to see it. Either way, you're going to the PR and squashing helps us clean up the commit history.

**Comment by kevingreenman** [comment]
Squashing sounds good to me. Regardless of what we choose, I agree that it would be great to standardize and document this practice rather than leaving it up to personal preferences of different developers on the team.

**Comment by kevingreenman** [comment]
> In addition, we should consider remove branches on chemprop main repo, forbid direct push to create new ones, and ask people in general to fork and PR from their forked version.

I just removed all of the stale branches from the primary repo and archived them to a read-only repo (see discussion in #479). 

I think there are some cases where it makes sense to have branches in the main repo (e.g. the `v2/numpy2_acceptance_testing` branch to test when our upstream dependencies catch up). The Read the Docs can be set up to build docs from other branches, but it can also do this for all new PRs, so this doesn't matter as much. But overall, I agree that we should discourage people from pushing branches to the main repo and encourage them to use local forks, unless there is a good reason to do the former.

**Comment by JacksonBurns** [comment]
Note that we can also enforce number of required reviews with branch protection rules.

We can also disallow the pull->merge approach in favor of rebase->merge, but we cannot force pull->merge.

**Comment by KnathanM** [comment]
The team discussed and decided we prefer to squash then merge PRs. We have disabled using a merge commit. We left rebase then merge as an option if the author/review strongly feel that the work of the PR should show up as multiple commits in the history (though this also suggests the PR could be broken into smaller PRs). The rebase option should not be used without first combining existing commits into a few logically distinct commits (probably not more than 3).
