### ISSUE TITLE
[QUESTION]: is it possible to give the predictions in 0 or 1 (ranther than a real number in the range of 0 and 1)?

### ISSUE THREAD

**Issue by hah2024** [chemprop/chemprop#777]
I have made predictions using the trained models. However, I found a problem, which is that, the predicted results are not 1 or 0? Is it possible to give the predictions in 0 or 1 (ranther than a real number in the range of 0 and 1)? Thanks a lot.

**Comment by kevingreenman** [comment]
The output from the model is the probability of having label 1. So you can convert from the probability to a label using a threshold value, e.g. any predicted probability over 0.5 indicates a predicted label of 1.
