### ISSUE TITLE
Request to share the trained weights.

### ISSUE THREAD

**Issue by SK124** [chemprop/chemprop#78]
Hi!

I was wondering if the authors could share the weights on all the datasets they benchmarked DMPNN's model. I do not have necessary GPU computational power to train on the datasets and I anyway need to train the model on the datasets which authors have already trained on. So it would be of great benefit if somebody could share.

Thanks!

**Comment by swansonk14** [comment]
Hi @SK124, I would be happy to share our weights, but we ran several different versions of the DMPNN on each dataset so which version are you interested in? Do you want just the basic Chemprop model or the optimized model with additional RDKit features and optimized hyperparameters (which performs better but is larger and a bit slower)? The full set of model weights takes up a ton of space so it would be hard to share all of them, but I can send several if there are a few that you are particularly interested in.

**Comment by lukas-folkman** [comment]
Hello!

I was wondering if it was possible to share weights and configuration of the ClinTox model - the one that was used in the paper to remove possibly toxic molecules from the top anitiobiotic predictions.

Thank you!

**Comment by lukas-folkman** [comment]
Hi @swansonk14, I was wondering if it was possible to share weights and configuration of the ClinTox model - the one that was used in the paper to remove possibly toxic molecules from the top anitiobiotic predictions. Thank you!
