### ISSUE TITLE
[QUESTION]: How to carry out hyperparameter optimization using codes

### ISSUE THREAD

**Issue by hah2024** [chemprop/chemprop#781]
Dear Chemprop team.

How to carry out hyperparameter optimization using codes? Does the chemprop automaticly carry out hyperparameter optimization during training? Below is my current codes for training. Do I need to provide additional codes to carry out hyperparameter optimization? Thank you very much.

My current code for training:

import chemprop
arguments = [
'--data_path', 'huixisa.csv',
'--dataset_type', 'classification',
'--save_dir', 'modelhuixisa101',
]
args = chemprop.args.TrainArgs().parse_args(arguments)
mean_score, std_score = chemprop.train.cross_validate(args=args, train_func=chemprop.train.run_training)

**Comment by shihchengli** [comment]
I believe you can do something like below to achieve this:
```
import chemprop
from chemprop.hyperparameter_optimization import hyperopt
arguments = [
'--data_path', 'huixisa.csv',
'--dataset_type', 'classification',
'--save_dir', 'modelhuixisa101',
]
args = chemprop.args.HyperoptArgs().parse_args(arguments)
hyperopt(args=args, train_func=chemprop.train.run_training)
```

**Comment by hah2024** [comment]
Dear Dr. Li, thanks a lot! I tried it using the codes you provided. It returns an error: **the following arguments are required: --config_save_path**

What does this mean? Is it to save the optimized hyperparameters? Then how to load the optimized hyperparameters to run training? 

Many thanks
Shawn

**Comment by kevingreenman** [comment]
https://github.com/chemprop/chemprop?tab=readme-ov-file#hyperparameter-optimization

**Comment by kevingreenman** [comment]
Closing this issue as completed for now, but feel free to re-open or create new issues if you have further questions that aren't answered by our [documentation](https://github.com/chemprop/chemprop/tree/master?tab=readme-ov-file#documentation) or [tutorials/examples](https://github.com/chemprop/chemprop/tree/master?tab=readme-ov-file#tutorials-and-examples).

**Comment by M123hx** [comment]
Hi Chemprop team.

I would like to know how to do hyperparameter optimisation based on custom parameter ranges in Chemprop v1.7.1.

Looking forward to your reply!

Thank you very much!
