### ISSUE TITLE
[QUESTION]: How to further train a model based on a trained model

### ISSUE THREAD

**Issue by hah2024** [chemprop/chemprop#782]
Hi Chemprop team,

I have trained a model using Chemprop. Is it possible to futher train the model using new dataset? In other words, how to further train a model using a previous trained model? I guess I need to load the previous model for futher training? What additional codes do I need to add?

Thank you very much.

My current code for training:

import chemprop
arguments = [
'--data_path', 'huixisa.csv',
'--dataset_type', 'classification',
'--save_dir', 'modelhuixisa101',
]
args = chemprop.args.TrainArgs().parse_args(arguments)
mean_score, std_score = chemprop.train.cross_validate(args=args, train_func=chemprop.train.run_training)

**Comment by shihchengli** [comment]
You can use `--checkpoint_path <path>` flag (please see [here](https://github.com/chemprop/chemprop?tab=readme-ov-file#pretraining)).

**Comment by hah2024** [comment]
Dear Dr. Li, thanks a lot! I will try it shortly

**Comment by kevingreenman** [comment]
Closing this issue as completed for now, but feel free to re-open or create new issues if you have further questions that aren't answered by our [documentation](https://github.com/chemprop/chemprop/tree/master?tab=readme-ov-file#documentation) or [tutorials/examples](https://github.com/chemprop/chemprop/tree/master?tab=readme-ov-file#tutorials-and-examples).
