### ISSUE TITLE
[FEATURE]: Move --ignore-columns to common args

### ISSUE THREAD

**Issue by KnathanM** [chemprop/chemprop#793]
For the sampl [benchmark](https://github.com/chemprop/chemprop_benchmark/blob/v2-scripts/scripts/sampl.sh), the test sets have more columns than just the smiles. I believe currently `chemprop predict` only works if you only have smiles to predict on in your test set. It isn't too hard to delete the extra columns, but we can also just easily move `--ignore-columns` to common.py and then chemprop predict will recognize that.

**Comment by hwpang** [comment]
Closed by https://github.com/chemprop/chemprop/pull/895
