### ISSUE TITLE
[Feature]: Revamp the `Transform` hyperparameter loading

### ISSUE THREAD

**Issue by hwpang** [chemprop/chemprop#810]
**Notes**
From @davidegraff 's comment from https://github.com/chemprop/chemprop/pull/726
> I feel like I'm broadly happy with this PR and there are some minor kinks to work out now. That said, I think there's two main extensions to this PR for the future:
> 
> 1. revamp the hyperparameter loading. The current implementation works and correctly stores the transforms in their respective modules, but it reintroduces duplicated memory that [more efficient module checkpointing #444](https://github.com/chemprop/chemprop/pull/444) attempted to address. In short, by saving the modules themselves as hyperparameters, their respective state dicts are stored **twice** in the checkpoint file: once with the scaler object itself and and once inside the entire model's state dict. Again, not a big deal considering these are O(24)−O(29), i.e, less than 1 KB each. There are only about five of them in the entire model, so this is practically a non-issue. However, it wouldn't be _bad_ for someone to try and address this to maintain thematic consistency with the rest of the code, but it _may_ be more trouble than it's worth...

**Comment by KnathanM** [comment]
Addressed by #898
