### ISSUE TITLE
question about adding weights to data

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#812]
Hello,
I built a classification model using Chemprop. My dataset is imbalanced, to overcome this issue, I tried the random stratified splitting and used --class_balance and also different percentage of oversampling for the minority class. What I have seen that the model performance ROC_AUC is relatively high (75%) and relatively low PRC_AUC (20%). I noticed oversampling does not improve the performance of the model. I was wondering if you have any suggestions in this regard. Do you think adding weights to training data will help? If so, what weights should I use?

Thanks
Best Regards
Soodabeh

**Comment by JacksonBurns** [comment]
Please see: https://github.com/chemprop/chemprop?tab=readme-ov-file#weighted-training-by-target-and-data

**Comment by SoodabehGhaffari** [comment]
Thank you for the link. I was wondering if there is any example/paper using
weights.

Best Regards
Soodabeh
