### ISSUE TITLE
[QUESTION]: Deprecation warning: please use MorganGenerator

### ISSUE THREAD

**Issue by Evert-Homan** [chemprop/chemprop#814]
Hi,

Lately I am getting this warning when training models (chemprop 1.7):

`Deprecation warning: please use MorganGenerator`

I usually use these flags when training models:

`--features_generator rdkit_2d_normalized --no_features_scaling --aggregation sum --epochs 200 --split_type cv --num_folds 10`

Do I need to upgrade RDKit? Please advise.

Thanks/Evert

**Comment by JacksonBurns** [comment]
A future version of RDKit will remove a function which we are using (either directly or indirectly) to calculate features (see this related issue on RDKit: https://github.com/rdkit/rdkit/issues/7349). This won't cause any problems for you until RDKit actually removes this feature at some unknown point in the future. Once that happens, you can simply downgrade your version of RDKit to before it was removed.

We are no longer working on Chemprop v1, so this is not something we will be able to help with. We will fix this in Chemprop v2, if it comes up.
