### ISSUE TITLE
[TODO]: Add CLI tutorial pages for HPO and fingerprinting to docs

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#815]
**Notes**
Similar to existing pages in our v2 docs for training, prediction, and conversion. The content can be based on what's currently in the v1 README for those functions.

**Comment by kevingreenman** [comment]
For hyperparameter optimization, we should make sure we have documentation on how to do this using both hyperopt and optuna.

**Comment by cjmcgill** [comment]
I second this one. The documentation currently says that hyperparameter optimization isn't supported. And that's kind of a core capability. The docs need to be updated.
