### ISSUE TITLE
[TODO]: use best model in notebooks

### ISSUE THREAD

**Issue by KnathanM** [chemprop/chemprop#820]
Our example notebooks use `trainer.test(mpnn, test_loader)`. We may want to show users how to test on their best model. They would do this by making a checkpointing callback and passing that to the trainer:
```
from lightning.pytorch.callbacks import ModelCheckpoint
checkpointing = ModelCheckpoint(
           "tempdir",
            "best-{epoch}-{val_loss:.2f}",
            "val_loss",
            mode="min",
            save_last=True,
        )
trainer = pl.Trainer(callbacks=[checkpointing])
```
Then they don't give the trainer a model: `trainer.test(dataloaders=test_loader)`.
We can do this as part of the documentation after v2.0 is out on pypi.

**Comment by donerancl** [comment]
new PR addressing this #1059
