### ISSUE TITLE
[TODO]: v2 docs build is failing - how to catch with CI?

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#825]
**Notes**
It appears that our `v2/dev` readthedocs build has been failing since [last week](https://readthedocs.org/projects/chemprop/builds/24096541/). How can we make sure this is part of the CI so we don't miss it in the future? I changed some settings and it appears that it's part of the checks starting in #824, but it's not clear to me if this will work for all future PRs, or if it's only for my PRs since my personal account is connected to our chemprop account on readthedocs.

The build is currently failing due to the following error: `AttributeError: module 'docutils.nodes' has no attribute 'reprunicode'`

**Comment by kevingreenman** [comment]
The readthedocs check also showed up on #821 after @KnathanM's recent changes, so I guess the settings changes I made should apply to all future PRs and current PRs that get updated, regardless of who makes them.

**Comment by shihchengli** [comment]
I think this is due to the removal of `docutils.nodes.reprunicode` from `docutils` in their latest release 0.21 version. (see [here](https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-21-2024-04-09)). Downgrading `docutils` version should be able to solve this issue.

**Comment by kevingreenman** [comment]
fixed by #826
