### ISSUE TITLE
[v1 QUESTION]: Training and prediction for directional bond targets

### ISSUE THREAD

**Issue by priabb** [chemprop/chemprop#837]
Hello, I'd like to train a model to predict a directional bond property, i.e., the bond property value depends on the direction of the bond. Does Chemprop V.1.7.0 support this?

Here is what I have tried so far:

1. Train two separate models, one for forward bond property and another for reverse bond property. For each case, I have the input bond property 2D array configured such that the value at index (m,n) is equal to the value at index (n,m)

2. Train one model where the input bond property 2D array is unsymmetrical, such that value at index (m,n) is a forward bond property and value at index (n,m) is the corresponding reverse bond property

I prefer 2 - but I'm wondering if the rmse and r2 calculated during training can differentiate between bond directionality?
Also, is there a way to obtain a 2D bond property array as output when making predictions? This will be useful for the case described in point 2 above.

Thank you!

**Comment by shihchengli** [comment]
Hi @priabb! The implementation doesn't support predicting directional bond properties, so the 2D matrix should be symmetric. I think only the lower or upper triangular matrix is used to generate a list of bond properties (see [here](https://github.com/chemprop/chemprop/blob/master/chemprop/data/utils.py#L517-L522)). The bond properties are returned as a 1-D array. You need to do some post-processing to figure out which property corresponds to which bond. Below is a sample code:
```
mol = Chem.MolFromSmiles(s)
for i, bond in enumerate(mol.GetBonds()):
    begin_indx = bond.GetBeginAtom().GetIdx()
    end_indx = bond.GetEndAtom().GetIdx()
    target = bond_targets[i]
    print(f"begin_indx: {begin_indx}; end_indx: {end_indx}, target: {target}")
```

**Comment by priabb** [comment]
Thanks for your response! I tried approach 1 and 2 for a directional bond property, and got very different r^2 values for the validation set used during training. Do you have any idea why that would be the case if only the lower or upper triangular matrix is used during training? Could the DMPNN architecture play a role?

**Comment by shihchengli** [comment]
For the bond property prediction, Janossy pooling is used (see [here](https://github.com/chemprop/chemprop/blob/master/chemprop/models/ffn.py#L213-L218)). Both forward and backward bonds are used as input for bond property prediction. We cannot expect the model to distinguish the differences between forward and backward bond properties after this operation. Therefore, it is incorrect to use either approach 1 or 2 for directional bond property prediction. Regarding why the results differ between the different models you have tried, I expect the results from approach 2 to be the same as one of your approach 1 models. If they are not, you can use the following code to test for any inconsistencies in the datasets. Again, it is not recommended to use this model for directional bond property prediction as Janossy pooling is used.

```
import numpy as np
from rdkit import Chem
mol = Chem.MolFromSmiles("CCCCC")
n_bonds = len(mol.GetBonds())
random_matrix = np.random.randint(1, 10, size=(n_bonds, n_bonds))
bond_targets_1 = (random_matrix + random_matrix.T) 

bond_targets_1 = []
bond_targets_2 = []
for i, bond in enumerate(mol.GetBonds()):
    begin_indx = bond.GetBeginAtom().GetIdx()
    end_indx = bond.GetEndAtom().GetIdx()
    bond_target_1 = 2D_bond_targets_1[begin_indx, end_indx]
    bond_target_2 = 2D_bond_targets_2[begin_indx, end_indx]
    bond_targets_1.append(bond_target_1)
    bond_targets_2.append(bond_target_2)
assert bond_targets_1 == bond_targets_2
```

**Comment by priabb** [comment]
Thank you!

**Comment by shihchengli** [comment]
Polling is not used in this case. Thus, the input size for the FFN needs to be reduced to half its current size, and the generation of `MoleculeDataset` object needs to be modified to accurately save the order of targets.

**Comment by priabb** [comment]
Thank you!
