### ISSUE TITLE
Error while loading globally installed package

### ISSUE THREAD

**Issue by msteijaert** [chemprop/chemprop#84]
The latest version (master branch) of the package tries to create a new directory inside the installed package. If a user does not have write permissions to that directory, this will cause the following error:

```
Traceback (most recent call last):
  File "trainv2.py", line 3, in <module>
    from chemprop.args import TrainArgs
  File "/opt/conda/lib/python3.6/site-packages/chemprop/__init__.py", line 5, in <module>
    import chemprop.web
  File "/opt/conda/lib/python3.6/site-packages/chemprop/web/__init__.py", line 1, in <module>
    from chemprop.web.run import chemprop_web
  File "/opt/conda/lib/python3.6/site-packages/chemprop/web/run.py", line 10, in <module>
    from chemprop.web.app import app, db
  File "/opt/conda/lib/python3.6/site-packages/chemprop/web/app/__init__.py", line 8, in <module>
    os.makedirs(app.config['CHECKPOINT_FOLDER'], exist_ok=True)
  File "/opt/conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/conda/lib/python3.6/site-packages/chemprop/web/app/web_checkpoints'
```

I'm happy to create a pull request to fix this, but there are various ways to do this. @swansonk14, what would we your preferred solution? The simplest solution would be to modify https://github.com/chemprop/chemprop/blob/master/chemprop/web/config.py, such that the CHECKPOINT_FOLDER points to a temporary directory or a directory in `os.getcwd()`. Alternatively, we could add some options to override default configuration before importing the package (e.g., by setting environment variables).

Side question: is there a good reason why `chemprop.web` is imported in the first place? For user who only interact via python API or command line interface, there seems to be no reason to load this subpackage (and create the corresponding checkpoints directory).

**Comment by swansonk14** [comment]
Hi @msteijaert, thanks for bringing up the great issue! Do you think it would be possible to add an argument to `WebArgs` in `chemprop/web/app/run.py` and then have that argument override the `ROOT_FOLDER` in `chemprop/web/app/config.py`? If possible, I think that might be nice because it would maintain the current default behavior while enabling an easy change through the command line interface. What do you think? If you agree and if you'd be willing to make a PR, that would be amazing!

That's a good question about importing `chemprop.web`. I think I had originally put it in `chemprop/__init__.py` because I thought it might be necessary for the packing and imports to work correctly but I might be wrong about that. Do you know if it would be possible to safely remove it from that init? If so, I think it would be nice to remove it to avoid importing when it isn't needed.

**Comment by msteijaert** [comment]
Hi @swansonk14. I think it's safe to remove `import chemprop.web` from the @__init__.py@. The only effect will be that someone who wants to import chemprop + chemprop.web needs two lines of code instead of one. In other modules where chemprop.web is needed, there is already an @import chemprop.web@, so those places will not be affected.

> Do you think it would be possible to add an argument to WebArgs in chemprop/web/app/run.py and then have that argument override the ROOT_FOLDER in chemprop/web/app/config.py? 
Yes, that should be possible. Note, however that, the ROOT_FOLDER is already used when importing chemprop.web.app, so before the WebArgs are parsed and applied. At that point, the following lines will be executed and may cause issues if the user has not write permissions in the ROOT_FOLDER:
```
os.makedirs(app.config['CHECKPOINT_FOLDER'], exist_ok=True)
os.makedirs(app.config['DATA_FOLDER'], exist_ok=True)
```
Moreover, it means that the ROOT_FOLDER specified with WebArgs does not yet contain a CHECKPOINT_FOLDER and DATA_FOLDER. I don't know the chemprop.web.app code that well, but I guess you can move these lines inside the `run_web()` function, such that they are executed after the user specifies the ROOT_FOLDER.

I have created a pull request (https://github.com/chemprop/chemprop/pull/91) in which I have removed the `import chemprop.web` and in which I modified `chemprop/web/app/config.py`. In the latter I check if the default ROOT_FOLDER is writable and if not change it to a subdirectory of the current working directory. If the latter is also not writable you will receive an error.

**Comment by swansonk14** [comment]
Hi @msteijaert, thanks for making the PR, it looks great! I went ahead and merged it. I thought a bit more about how to create an option to change the root folder, and I ended up coming up with this: https://github.com/chemprop/chemprop/commit/0ff6fd45258899d5d46f50357fefd5458aff1cdd. What do you think? The default remains the same, but now there's an extra argument that can be used to change the root folder, and the root folder is only accessed and modified after the user has had the option to change it. Hopefully that should be a good balance of maintaining the current location and functionality of the root folder while enabling users to change it if they want.

**Comment by msteijaert** [comment]
Hi @swansonk14. This looks like a great improvement! With a globally installed package and the default settings, the app will still raise the above issue, but there is now an easy way to get rid of the error. Maybe you could replace the above with a more user-friendly error message. For example:
```
# Create folders
    if create_folders:
        if not os.access(os.path.dirname(app.config['ROOT_FOLDER']), os.W_OK):
            raise ValueError("You do not have write permissions on the root_folder. Please specify a different root_folder while starting the web app.")
        for folder_name in ['ROOT_FOLDER', 'DATA_FOLDER', 'CHECKPOINT_FOLDER', 'TEMP_FOLDER']:
            os.makedirs(app.config[folder_name], exist_ok=True)
```

**Comment by swansonk14** [comment]
Oh yeah that's a great idea, thanks! I just added it in this commit: https://github.com/chemprop/chemprop/commit/fc35354a629c5294d2c14e800b54feedce86272b
