### ISSUE TITLE
[v2 Feature Request]: automated rdkit2d features

### ISSUE THREAD

**Issue by muammar** [chemprop/chemprop#843]
**What are you trying to do?**
I could run my first training/prediction following the tutorials in a notebook! I had a couple of questions on how to achieve the following: 

1. How to use `rdkit2d` features? Based on the [documentation](https://chemprop.readthedocs.io/en/main/extra_features_from_featurizer.html), I think I should compute these and dump them into a file and then load them. Is that correct? I am unsure how to proceed. 
2. How can I perform a [hyperparameter optimization](https://chemprop.readthedocs.io/en/main/cmd.html#chemprop-hyperparameter-optimization-arguments
)? If I have to do this from the command line, how do I load the hyperparameters from a file?
3. How can I perform a multi-task learning training?

Thank you very much for this new version, it is very exciting. I look forward to hearing from you. 

Best,

**Comment by SteshinSS** [comment]
Also got here looking for ways to use `rdkit2d` features as in v1: `--features_generator rdkit_2d_normalized --no_features_scaling`

**Comment by JacksonBurns** [comment]
- Hyperparameter optimization is now available as of #734, see the docs: https://chemprop.readthedocs.io/en/main/cmd.html#hpopt
 - Multi-task training is possible by specifying multiple target columns, see the docs: https://chemprop.readthedocs.io/en/main/tutorial/cli/train.html#input-data

As far as 2D features go, we had originally not added this to v2 because we wanted people to calculate them on their own and pass them as extra features manually. Since it has now been requested to do this automatically here, in #864 (here: https://github.com/chemprop/chemprop/issues/864#issuecomment-2110307955), and in #849, we will put this feature on the TODO list.

**Comment by KC-Zhang** [comment]
for now how do i manually calculate rdkit_2d_normalized in V2?

**Comment by SteshinSS** [comment]
@KC-Zhang chemprop v1 generated feature by [descriptastorus](https://github.com/bp-kelley/descriptastorus) and it's simple to use. However, I didn't understand how to use those feature during training, as the example notebook from https://github.com/chemprop/chemprop/pull/772 doesn't work.

**Comment by KC-Zhang** [comment]
@SteshinSS  which specific note book are you talking about? is it `examples/extra_features_from_featurizer.ipynb` ? when i try this file, it bugs out at this line ` from chemprop.featurizers import MoleculeFeaturizer`, are you experiencing the same?

**Comment by SteshinSS** [comment]
@KC-Zhang I think `examples/loaded_molecule_features.ipynb` should be the example of additional features usage, but it didn't work for me with the 2.0.0.

**Comment by KnathanM** [comment]
> for now how do i manually calculate --features_generator rdkit_2d_normalized --no_features_scaling in V2?

First install descriptastorus `pip install git+https://github.com/bp-kelley/descriptastorus`
Next run this script:
```
import numpy as np
import pandas as pd
from descriptastorus.descriptors import rdNormalizedDescriptors

# Load data - Example:
df = pd.read_csv("mydata.csv")

generator = rdNormalizedDescriptors.RDKit2DNormalized()
rdkit_descriptors = np.array([generator.process(smi)[1:] for smi in df.smiles])
np.savez("rdkit_descriptors.npz", rdkit_descriptors)
```
Then run chemprop
```
chemprop train --data-path mydata.csv --descriptors-path rdkit_descriptors.npz --no-descriptor-scaling
```

Alternatively, you don't need to install descriptastorus if you use RDKit directly to make the descriptors
```
from rdkit import Chem
from rdkit.Chem import Descriptors
rdkit_descriptors = np.array([[func(Chem.MolFromSmiles(smi)) for name, func in sorted(Descriptors.descList)] for smi in df.smiles])
```
Note however that these descriptors are not scaled so the `--no-descriptor-scaling` flag should not be set if using them. Also the scaling in Chemprop is different than in descriptastorus as it is dataset dependent and not determined beforehand. Lastly the following rdkit descriptors are skipped in descriptastorus `['AvgIpc', 'BCUT2D_CHGHI', 'BCUT2D_CHGLO', 'BCUT2D_LOGPHI', 'BCUT2D_LOGPLOW', 'BCUT2D_MRHI', 'BCUT2D_MRLOW', 'BCUT2D_MWHI', 'BCUT2D_MWLOW', 'SPS']`
