### ISSUE TITLE
[v1 QUESTION]: Split CV by default 33:33:33...why?

### ISSUE THREAD

**Issue by spyda90** [chemprop/chemprop#854]
Hi,
I am running hypopt+training to build a regression model using a dataset of total 213 datapoints.

I initially avoid k-fold cross validation, using random spit. Everything worked fine (with expected split of 80:10:10) and I obtained quite good RMSE value.
To stress a little bit more the model, I'd like to run k-fold cross validation, starting from low k-fold, increasing it gradually.
I started with **--num_folds 3** and, as usual for cv, I used **--split_type cv**. I was expecting a spitting of 80:10:10, instead I saw a 33:33:33 ratio.
Edit: if I use **--num_folds 5** the split is 60:20:20, despite in the paste option at the beginning of calculation there is 'split_sizes: [0.8, 0.1, 0.1]'.

Why is this happening?

Thank you in advance!

**Comment by shihchengli** [comment]
If `--split_type cv` is used, it will divide the dataset into k subsets of approximately equal size. What you are looking for is `--split_type random`, which is the default option.

**Comment by spyda90** [comment]
Hi [shihchengli](https://github.com/shihchengli), I am not sure you got my point.

What I am talking about is not a splitting of the total dataset in subsets, but the splitting in train:val:test.
This, from my knowledge, should not change varying the number of folds. Indeed using:
--num_folds 3 --> The dataset is splitted in 71:71:71 train:val:test (33:33:33)
--num_folds 5 --> The dataset is splitted in 127:43:43 train:val:test (60:20:20)
--num_folds 10 --> The dataset is splitted in 169:22:22 train:val:test (80:10:10)

But every time in the initial optiions I can read 'split_sizes: [0.8, 0.1, 0.1]', that is what I am expecting.

It does not make sense from my side...
Moreover, each fold should use te total dataset randomly splitted in train:val:test 80:10:10 (each time with a different seed).

Thank you for your help!

**Comment by spyda90** [comment]
Thank you very much!
