### ISSUE TITLE
[v2 QUESTION]: Additional features prediction with npz file not working

### ISSUE THREAD

**Issue by Satari45** [chemprop/chemprop#859]
**What are you trying to do?**
I am trying to perform prediction with additional features loaded on a npz file. 

I added `--descriptors-path features.npz` to my training which ran fine just like in the documentation. However, I could not figure out how to perform the prediction with the same amount of additional features. I also tried using the same code for the prediction command `--descriptors-path features_predict.npz` but it gives an error: unrecognized arguments: features_predict.npz.

**Comment by JacksonBurns** [comment]
@Satari45 what was the solution?
