### ISSUE TITLE
[v1 QUESTION]: Leave-one-out CV...how it is the easiest way to go?

### ISSUE THREAD

**Issue by spyda90** [chemprop/chemprop#860]
Hi,

I am currently using Chemprop from command line to build a model starting from a small daataset (213 datapoints).
I have tried three different k values (3, 5, 10). The validation RMSE value +/- SD is quite similar in every trial.

In order to have an extensive test, i read that the best way to evaluate the best k is to use the leave-one-out methodology.

Which is the best way to perform it in an iterative way using Chemprop with command line?
I read something in the issue section about cv-no-test option for splitting, but I did not got how it works.

Thank you for your help!

**Comment by JacksonBurns** [comment]
You can achieve a test set size of 1 by setting the number of folds equal to 213, which will use 1/213th of your data for validation, or one datapoint (see the formula provided by @shihchengli in https://github.com/chemprop/chemprop/issues/854#issuecomment-2096044498) and also specify `cv-no-test` to perform a two way split, which _should_ result in one sample being withheld and validated against in each model.

That being said, **don't do this** - that would train 213 Chemprop models. For deep learning methods LOOCV is not appropriate, and the 10-fold CV you have already done should give you a good idea of the performance.

**Comment by spyda90** [comment]
Thank you for the clarification!
