### ISSUE TITLE
[v2 BUG]: TypeError: 'str' object is not callable...?

### ISSUE THREAD

**Issue by spyda90** [chemprop/chemprop#864]
Hi,

I am using ChempropV2 for the first time. I'd like to re-run model hpopt and training that I have done using V1.
Thus, I have update my launching script following the new options / arguments.

The final command line is the follwing:
`chemprop hpopt --data-path $Database --task-type regression --raytune-num-samples 100 --hpopt-save-dir ./hyperopt/hyperopt_100iter_features_ensemble5_k-fold$kfold --metrics rmse r2 --data-seed 0 --features-generators morgan_binary --no-descriptor-scaling --ensemble-size 5 --split-type cv --num-folds $kfold`

However, I am obtaining the following error message:

```
chemprop 8 <module>
sys.exit(main())

main.py 80 main
func(args)

hpopt.py 101 func
main(args)

hpopt.py 378 main
train_data, val_data, test_data = build_splits(args, format_kwargs, featurization_kwargs)

train.py 596 build_splits
all_data = build_data_from_files(

parsing.py 290 build_data_from_files
mol_data, rxn_data = make_datapoints(

parsing.py 212 make_datapoints
mol_data = [

parsing.py 213 <listcomp>
[

parsing.py 214 <listcomp>
MoleculeDatapoint.from_smi(

datapoints.py 65 from_smi
return cls(mol, *args, **kwargs)

<string> 14 __init__


datapoints.py 98 __post_init__
super().__post_init__(mfs)

datapoints.py 41 __post_init__
self.x_d = self.calc_features(mfs)

datapoints.py 107 calc_features
return np.hstack([mf(self.mol) for mf in mfs])

datapoints.py 107 <listcomp>
return np.hstack([mf(self.mol) for mf in mfs])

TypeError:
'str' object is not callable
```
What am I missing?
The CSV input file is the same I used for V1 hpopt+train.

Thank you in advance!

**Comment by spyda90** [comment]
Thank you!
Additionally, why now there is no more the RDkit_2D features as argument?

**Comment by kevingreenman** [comment]
> Thank you! Additionally, why now there is no more the RDkit_2D features as argument?

@spyda90 we are discussing this internally and will provide an answer in #843

**Comment by spyda90** [comment]
Thank you!
I run the hpopt with no features_generatore and the error did not come up.
Nowe I am trying to run `chemprop train` like as follow:

`chemprop train --data-path $Database --task-type regression --config-path ./hyperopt/hyperopt_pizza/best_params.json --output-dir ./train/train_hyperopt_100iter_ensemble5_k-fold10 --metrics rmse r2 --data-seed 0 --features-generators morgan_binary --no-descriptor-scaling --ensemble-size 5 --split-type cv --num-folds 10 --save-smiles-splits`

But I am obtaining this error:
```
Usage: chemprop [-h] {train,predict,convert,fingerprint,hpopt} ...
chemprop: error: unrecognized arguments: --{=true --"train_loop_config"={ --"ffn_num_layers"=2.0, --"message_hidden_dim"=1400.0, --"ffn_hidden_dim"=400.0, --"dropout"=0.0, --"depth"=3.0 --}=true
```

I am gussing is something wrong with config-path, At the beginning I was specifying the folder (as in V1) but an error came up, telling me I have to specify a file and not a folder as argument. I supposed that was the "best_param.json" file.

Any ideas why is this happening?

Thank you for your support.
