### ISSUE TITLE
v1 Demo Notebook Reaction Bug

### ISSUE THREAD

**Issue by nadeennassif** [chemprop/chemprop#866]
**Describe the bug**
RuntimeError                              Traceback (most recent call last)
[<ipython-input-28-ca01474abf2f>](https://localhost:8080/#) in <cell line: 11>()
      9 
     10 args = chemprop.args.TrainArgs().parse_args(arguments)
---> 11 mean_score, std_score = chemprop.train.cross_validate(args=args, train_func=chemprop.train.run_training)

16 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py](https://localhost:8080/#) in forward(self, input)
    114 
    115     def forward(self, input: Tensor) -> Tensor:
--> 116         return F.linear(input, self.weight, self.bias)
    117 
    118     def extra_repr(self) -> str:

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1847x147 and 193x300)

**Example(s)**
Reaction regression

**Expected behavior**

arguments = [
    '--data_path', 'data/reaction_regression.csv',
    '--dataset_type', 'regression',
    '--save_dir', 'test_checkpoints_reaction',
    '--epochs', '5',
    '--reaction',
    '--save_smiles_splits'
]

args = chemprop.args.TrainArgs().parse_args(arguments)

Command line
python /usr/local/lib/python3.8/dist-packages/ipykernel_launcher.py -f /root/.local/share/jupyter/runtime/kernel-8f687a13-fd1d-4bb6-bf15-8368444c40f1.json
Args
{'activation': 'ReLU',
 'adding_h': False,
 'aggregation': 'mean',
 'aggregation_norm': 100,
 'atom_descriptor_scaling': True,
 'atom_descriptors': None,
 'atom_descriptors_path': None,
 'atom_descriptors_size': 0,
 'atom_features_size': 0,
 'atom_messages': False,
 'batch_size': 50,
 'bias': False,
 'bias_solvent': False,
 'bond_feature_scaling': True,
 'bond_features_path': None,
 'bond_features_size': 0,
 'cache_cutoff': 10000,
 'checkpoint_dir': None,
 'checkpoint_frzn': None,
 'checkpoint_path': None,
 'checkpoint_paths': None,
 'class_balance': False,
 'config_path': None,
 'crossval_index_dir': None,
 'crossval_index_file': None,
 'crossval_index_sets': None,
 'cuda': False,
 'data_path': 'data/reaction_regression.csv',
 'data_weights_path': None,
 'dataset_type': 'regression',
 'depth': 3,
 'depth_solvent': 3,
 'device': device(type='cpu'),
 'dropout': 0.0,
 'empty_cache': False,
 'ensemble_size': 1,
 'epochs': 5,
 'evidential_regularization': 0,
 'explicit_h': False,
 'extra_metrics': [],
 'features_generator': None,
 'features_only': False,
 'features_path': None,
 'features_scaling': True,
 'features_size': None,
 'ffn_hidden_size': 300,
 'ffn_num_layers': 2,
 'final_lr': 0.0001,
 'folds_file': None,
 'freeze_first_only': False,
 'frzn_ffn_layers': 0,
 'gpu': None,
 'grad_clip': None,
 'hidden_size': 300,
 'hidden_size_solvent': 300,
 'ignore_columns': None,
 'init_lr': 0.0001,
 'log_frequency': 10,
 'loss_function': 'mse',
 'max_data_size': None,
 'max_lr': 0.001,
 'metric': 'rmse',
 'metrics': ['rmse'],
 'minimize_score': True,
 'mpn_shared': False,
 'multiclass_num_classes': 3,
 'no_atom_descriptor_scaling': False,
 'no_bond_features_scaling': False,
 'no_cache_mol': False,
 'no_cuda': False,
 'no_features_scaling': False,
 'num_folds': 1,
 'num_lrs': 1,
 'num_tasks': 1,
 'num_workers': 8,
 'number_of_molecules': 1,
 'overwrite_default_atom_features': False,
 'overwrite_default_bond_features': False,
 'phase_features_path': None,
 'pytorch_seed': 0,
 'quiet': False,
 'reaction': True,
 'reaction_mode': 'reac_diff',
 'reaction_solvent': False,
 'resume_experiment': False,
 'save_dir': 'test_checkpoints_reaction',
 'save_preds': False,
 'save_smiles_splits': True,
 'seed': 0,
 'separate_test_atom_descriptors_path': None,
 'separate_test_bond_features_path': None,
 'separate_test_features_path': None,
 'separate_test_path': None,
 'separate_test_phase_features_path': None,
 'separate_val_atom_descriptors_path': None,
 'separate_val_bond_features_path': None,
 'separate_val_features_path': None,
 'separate_val_path': None,
 'separate_val_phase_features_path': None,
 'show_individual_scores': False,
 'smiles_columns': ['AAM'],
 'spectra_activation': 'exp',
 'spectra_phase_mask_path': None,
 'spectra_target_floor': 1e-08,
 'split_key_molecule': 0,
 'split_sizes': [0.8, 0.1, 0.1],
 'split_type': 'random',
 'target_columns': None,
 'target_weights': None,
 'task_names': ['ea'],
 'test': False,
 'test_fold_index': None,
 'train_data_size': None,
 'undirected': False,
 'use_input_features': False,
 'val_fold_index': None,
 'warmup_epochs': 2.0}
Setting molecule featurization parameters to default.
Loading data
500it [00:00, 47996.34it/s]
100%|██████████| 500/500 [00:00<00:00, 127968.76it/s]
100%|██████████| 500/500 [00:00<00:00, 7069.00it/s]
Number of tasks = 1
Fold 0
Splitting data with seed 0
500it [00:00, 63780.06it/s]
Total size = 500 | train size = 400 | val size = 50 | test size = 50
Fitting scaler
Building model 0
MoleculeModel(
  (encoder): MPN(
    (encoder): ModuleList(
      (0): MPNEncoder(
        (dropout_layer): Dropout(p=0.0, inplace=False)
        (act_func): ReLU()
        (W_i): Linear(in_features=193, out_features=300, bias=False)
        (W_h): Linear(in_features=300, out_features=300, bias=False)
        (W_o): Linear(in_features=465, out_features=300, bias=True)
      )
    )
  )
  (ffn): Sequential(
    (0): Dropout(p=0.0, inplace=False)
    (1): Linear(in_features=300, out_features=300, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.0, inplace=False)
    (4): Linear(in_features=300, out_features=1, bias=True)
  )
)
Number of parameters = 378,601
  0%|          | 0/5 [00:00<?, ?it/s]Epoch 0

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|█▎        | 1/8 [00:00<00:00,  7.57it/s]
 25%|██▌       | 2/8 [00:00<00:00,  7.45it/s]
 38%|███▊      | 3/8 [00:00<00:00,  7.91it/s]
 50%|█████     | 4/8 [00:00<00:00,  7.87it/s]
 62%|██████▎   | 5/8 [00:00<00:00,  8.06it/s]
 75%|███████▌  | 6/8 [00:00<00:00,  8.04it/s]
 88%|████████▊ | 7/8 [00:00<00:00,  8.07it/s]
100%|██████████| 8/8 [00:01<00:00,  8.12it/s]
                                             
  0%|          | 0/1 [00:00<?, ?it/s]
                                     Validation rmse = 2.271719
 20%|██        | 1/5 [00:01<00:05,  1.33s/it]Epoch 1

  0%|          | 0/8 [00:00<?, ?it/s]Loss = 7.7459e-01, PNorm = 34.6705, GNorm = 6.2133, lr_0 = 7.1875e-04

 25%|██▌       | 2/8 [00:00<00:00, 10.25it/s]
 50%|█████     | 4/8 [00:00<00:00,  9.73it/s]
 62%|██████▎   | 5/8 [00:00<00:00,  9.57it/s]
 75%|███████▌  | 6/8 [00:00<00:00,  8.95it/s]
100%|██████████| 8/8 [00:00<00:00,  9.80it/s]
                                             
  0%|          | 0/1 [00:00<?, ?it/s]
                                     Validation rmse = 2.165562
 40%|████      | 2/5 [00:02<00:03,  1.23s/it]Epoch 2

  0%|          | 0/8 [00:00<?, ?it/s]
 25%|██▌       | 2/8 [00:00<00:00, 12.25it/s]Loss = 8.0665e-01, PNorm = 34.7094, GNorm = 10.4500, lr_0 = 6.1897e-04

 50%|█████     | 4/8 [00:00<00:00, 11.38it/s]
 75%|███████▌  | 6/8 [00:00<00:00, 10.69it/s]
100%|██████████| 8/8 [00:00<00:00, 10.33it/s]
                                             
  0%|          | 0/1 [00:00<?, ?it/s]
                                     Validation rmse = 2.293178
 60%|██████    | 3/5 [00:03<00:02,  1.09s/it]Epoch 3

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|█▎        | 1/8 [00:00<00:01,  6.24it/s]
 25%|██▌       | 2/8 [00:00<00:00,  6.36it/s]
 38%|███▊      | 3/8 [00:00<00:00,  6.23it/s]
 50%|█████     | 4/8 [00:00<00:00,  6.40it/s]
 62%|██████▎   | 5/8 [00:00<00:00,  6.83it/s]Loss = 7.1648e-01, PNorm = 34.7282, GNorm = 2.6230, lr_0 = 2.3714e-04

 75%|███████▌  | 6/8 [00:00<00:00,  5.82it/s]
 88%|████████▊ | 7/8 [00:01<00:00,  5.71it/s]
100%|██████████| 8/8 [00:01<00:00,  5.45it/s]
                                             
  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
                                             Validation rmse = 2.401798
 80%|████████  | 4/5 [00:04<00:01,  1.28s/it]Epoch 4

  0%|          | 0/8 [00:00<?, ?it/s]
 12%|█▎        | 1/8 [00:00<00:01,  4.01it/s]
 25%|██▌       | 2/8 [00:00<00:01,  3.85it/s]
 38%|███▊      | 3/8 [00:00<00:01,  3.94it/s]
 50%|█████     | 4/8 [00:01<00:01,  3.89it/s]
 62%|██████▎   | 5/8 [00:01<00:00,  4.14it/s]
 75%|███████▌  | 6/8 [00:01<00:00,  4.27it/s]
 88%|████████▊ | 7/8 [00:01<00:00,  5.10it/s]Loss = 6.5946e-01, PNorm = 34.7339, GNorm = 4.1201, lr_0 = 1.0000e-04

100%|██████████| 8/8 [00:01<00:00,  5.93it/s]
                                             
  0%|          | 0/1 [00:00<?, ?it/s]
                                     Validation rmse = 2.034656
100%|██████████| 5/5 [00:06<00:00,  1.40s/it]
Model 0 best validation rmse = 2.034656 on epoch 4
Loading pretrained parameter "encoder.encoder.0.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.0.W_i.weight".
Loading pretrained parameter "encoder.encoder.0.W_h.weight".
Loading pretrained parameter "encoder.encoder.0.W_o.weight".
Loading pretrained parameter "encoder.encoder.0.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
Model 0 test rmse = 1.969818
Ensemble test rmse = 1.969818
1-fold cross validation
	Seed 0 ==> test rmse = 1.969818
Overall test rmse = 1.969818 +/- 0.000000
Elapsed time = 0:00:08
![chemprop_colab_demo ipynb - Colab - Google Chrome 12_05_2024 03_42_53](https://github.com/chemprop/chemprop/assets/65887979/7029dc81-7fb9-4b88-8cc6-5256a7dab58c)

**Error Stack Trace**
If the bug is resulting in an error message, provide the _full_ stack trace (not just the last line). This is helpful for debugging, especially in cases where you aren't able to provide a minimum/isolated working example with accompanying files.

**Screenshots**

**Environment**
- python version: 3.10.12
- package versions: !pip install chemprop
!pip install rdkit-pypi  # should be included in above after Chemprop v1.6 release

# Download test files from GitHub
!apt install subversion
!svn export https://github.com/chemprop/chemprop.git/trunk/tests/data

import chemprop
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.offsetbox import AnchoredText
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.decomposition import PCA
- OS

**Checklist**
- [ ] all dependencies are satisifed: `conda list` or `pip list` shows the packages listed in the `pyproject.toml`
- [ ] the unit tests are working: `pytest -v` reports no errors

**Additional context**
I was working on reaction regression on chemprop demo notebook and I have tried regression and training data files
![chemprop_colab_demo ipynb - Colab - Google Chrome 12_05_2024 03_42_53](https://github.com/chemprop/chemprop/assets/65887979/0e084126-b30d-4833-9ca0-a55af16cf766)

**Comment by JacksonBurns** [comment]
Hi @nadeennassif your issue has a lot of formatting problems so I can't tell what is wrong. Please fix the formatting, provide a couple sentences of explanation for what is going on, and then re-open the issue.

I have edited the name of the issue since you are running the v1 demo notebook found [here](https://colab.research.google.com/github/chemprop/chemprop/blob/master/colab_demo.ipynb). To anyone else trying this, note that you will have to change `!svn export https://github.com/chemprop/chemprop.git/trunk/tests/data` in the first cell to `!git clone -b master https://github.com/chemprop/chemprop.git` followed by `!cp -r chemprop/tests/data .`. We have changed the default branch on github so the former no longer works.

**Comment by nadeennassif** [comment]
What is the latest version that I can run without any trouble shooting
Thanks in advance

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JacksonBurns** [comment]
2.0

**Comment by nadeennassif** [comment]
Where can I find it if you send the link to me this will be appreciated because I’m stuck in this

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JacksonBurns** [comment]
https://chemprop.readthedocs.io/en/main/notebooks.html

**Comment by nadeennassif** [comment]
I've tried this version and gives me errors in packages is there a specific way to run it
________________________________

**Comment by nadeennassif** [comment]
this is the error
________________________________
