### ISSUE TITLE
[v2 BUG]: Configuration file for training...ERROR?

### ISSUE THREAD

**Issue by spyda90** [chemprop/chemprop#869]
Hi, 

I am trying to run `chemprop train` like as follow:

`chemprop train --data-path $Database --task-type regression --config-path ./hyperopt/hyperopt_pizza/best_params.json --output-dir ./train/train_hyperopt_100iter_ensemble5_k-fold10 --metrics rmse r2 --data-seed 0 --features-generators morgan_binary --no-descriptor-scaling --ensemble-size 5 --split-type cv --num-folds 10 --save-smiles-splits`

But I am obtaining this error:

Usage: chemprop [-h] {train,predict,convert,fingerprint,hpopt} ...
`chemprop: error: unrecognized arguments: --{=true --"train_loop_config"={ --"ffn_num_layers"=2.0, --"message_hidden_dim"=1400.0, --"ffn_hidden_dim"=400.0, --"dropout"=0.0, --"depth"=3.0 --}=true`

I am gussing is something wrong with `--config-path`. At the beginning I was specifying the folder (as in V1) but an error came up, telling me I have to specify a file and not a folder as argument. I supposed that was the "best_param.json" file.

Any ideas why is this happening?

Thank you for your support.

**Comment by JacksonBurns** [comment]
Thanks for the report! This is a mistake on our end.

@hwpang I see you added support for this in #775 (see the git blame: https://github.com/chemprop/chemprop/blame/be8340d6ceef3243186ba0ff7d7390bf5484c992/chemprop/cli/train.py#L76) but the added unit test never actually tries to run Chemprop, it just parses args from the file. Could you add a unit test that actually runs chemprop from a config file so this bug can be found/fixed?

I also see [here](https://github.com/chemprop/chemprop/blame/be8340d6ceef3243186ba0ff7d7390bf5484c992/chemprop/cli/train.py#L144) that @KnathanM has config args setup and commented out, with a note to add it in 2.1 - communication breakdown?

**Comment by hwpang** [comment]
Thanks for the report! Yeah, at the moment the config file generated by raytune (used by hpopt) is not the same format that Chemprop train takes. It should be a straight forward fix. I will work on this later today.

**Comment by spyda90** [comment]
Great! 
Please let us know when those fixes (features generators, confi file) will be ready in the next update.

Thank you for your support!
