### ISSUE TITLE
What to do when atom or bond is `None`?

### ISSUE THREAD

**Issue by KnathanM** [chemprop/chemprop#870]
In `featurizers/atom.py` we allow for the `Atom` to be `None` and will return an array of zeros if it is:
```
    def __call__(self, a: Atom | None) -> np.ndarray:
        x = np.zeros(self.__size)

        if a is None:
            return x
```
`featurizers/bond.py` does something similar but sets the first "null" bit to 1 (though note we forgot to include `None` as an option in the type hint):
```
def __call__(self, b: Bond) -> np.ndarray:
    x = np.zeros(len(self), int)

    if b is None:
        x[0] = 1
        return x
```

But in `SimpleMoleculeMolGraphFeaturizer`, we have logic checks that make it so we never pass `None` to the atom and bond featurizers. 
```
if n_atoms == 0:
    V = np.zeros((1, self.atom_fdim), dtype=np.single)
if bond is None:
    continue
```

Does anyone know/remember the rational for having a "null-ity" bit in the bond feature vector? Should the molgraph featurizer be change to not `continue` when a bond is `None`?

**Comment by davidegraff** [comment]
This allows for "virtual' edges in the graph, e.g., 3D graphs, global source/sink nodes, etc.
