### ISSUE TITLE
[v2 QUESTION]:  EvidentialFFN error

### ISSUE THREAD

**Issue by satvikkg** [chemprop/chemprop#879]
I am trying to train a regression model using the following command:
chemprop train --data-path test.csv --task-type regression-evidential --output-dir test1 --features-generators morgan_binary morgan_count 

I am getting the following error:
AttributeError: 'EvidentialFFN' object has no attribute 'scale'

I am not getting the error when the task-type is regression

**Comment by kevingreenman** [comment]
@satvikkg there are no uncertainty techniques implemented in v2.0. This is a milestone for v2.1, which will be released later this year. If you would like to use chemprop with uncertainty quantification/calibration/evaluation, you will need to use v1.7.1 (which has ensemble, evidential, mve, dropout, and conformal methods implemented for regression tasks). Please see the v1.7.1 [README](https://github.com/chemprop/chemprop/tree/master?tab=readme-ov-file#uncertainty-estimation) for details. You can follow #473 for discussion on this.
