### ISSUE TITLE
[v2 BUG]: Multitask predictions columns are unlabeled and in scrambled order

### ISSUE THREAD

**Issue by cjmcgill** [chemprop/chemprop#890]
**Describe the bug**
When training a multitask regression model, the order and names of the tasks don't seem to be saved in the checkpoint file. When the predict task is then used from the checkpoint, the predictions are returned without labeled columns and in a new column order, making matching the tasks to their predictions difficult/not possible. It would be preferred for them to be both labeled and in the original order. By comparison, the `test_predictions.csv` file that is generated during training retains the column labels but is in the new order.

**Example(s)**
These are output prediction files from a test I was doing to see if the target scaling was ignoring empty targets properly (good news, seems to be). The dataset was a very truncated version of qm9 so had 12 targets.

predictions from `chemprop predict`
[preds_0.csv](https://github.com/chemprop/chemprop/files/15489977/preds_0.csv)
test_predictions.csv
[test_predictions.csv](https://github.com/chemprop/chemprop/files/15490117/test_predictions.csv)

**Expected behavior**
I would expect for the outcome of `chemprop predict` to have labeled columns and retain the original target order.

**Environment**
- python version: 3.11.9
- OS: ubuntu

**Checklist**
- [x] all dependencies are satisifed: `conda list` or `pip list` shows the packages listed in the `pyproject.toml`
- [x] the unit tests are working: `pytest -v` reports no errors

**Comment by hwpang** [comment]
@shihchengli Thanks for tagging me. Yes, as you said, in v2 we purposely try only keep information that would be used all the time in the MPNN module. An alternative that I can think of is to save a prediction config file that writes the `--target-names` automatically, and the user can use the config file to make predictions. What do you think?

**Comment by cjmcgill** [comment]
@hwpang could the prediction config dictionary be bundled together inside the pt file? I don't like the idea of generating an additional file and providing an additional path, but it seems like it can bundle together. Or be loaded in from the train args in the pt file, I think that might be how it did it in v1.

**Comment by hwpang** [comment]
@cjmcgill Yeah I like that idea of saving the target column information in the .pt file. I think it went well with our design of the model file (the `.pt` file) as we envision it to be used for prediction, while the checkpoint file (the `.ckpt` file) for training. I can throw together a PR for this
