### ISSUE TITLE
[v2 BUG]: issues related to target columns during inference 

### ISSUE THREAD

**Issue by jonwzheng** [chemprop/chemprop#894]
**Describe the bug**
This is actually 2 bugs that I observed related to inference:

1. Inference on a .csv that has non-numerical columns in addition to the SMILES columns will lead to a ValueError, because `parse_csv` treats the test dataset's `target_cols` like it does during training - so by default assumes every column is a target.
2. CLI argument `--target_columns` during inference doesn't actually get used during `make_prediction_for_model` so it doesn't do anything. This means you can't parse `--target-columns` to fix (1) above; you need to manually modify the test .csv to include _only_ a column with SMILES

**Example(s)**
You can recreate this by training a regression model on anything (I used the `regression.csv` in the `tests/data` dir) and then running inference on this simple minimal dataset:
```
"smiles","descriptor_1","descriptor_2","descriptor_3","descriptor_4"
"CCC","acidic","big","toxic",1.1
"CCCO","basic","small","toxic",1.3
"CCCCO","acidic","big","nontoxic",2.5
"NC","basic","big","toxic",6.6
"N(=O)O","acidic","small","toxic",7.7
```

I ran the following:

```chemprop predict --test-path dummy_test.csv \
    --model-path train_example/model_0/best.pt \
    --preds-path train_example/predictions.csv
```

and encountered this error:
```
ValueError: could not convert string to float: 'acidic'
```

Looking into the codebase it looks like the error is that `parse_csv` tries to convert the relevant target columns `Y` to float, but since `target_cols` is not provided then it behaves like it does during training (treating all columns as targets). 

OK, so I thought maybe I can sidestep this by providing `--target-columns`, but if you do this, you get the same error as above because it's not used in `make_prediction_for_model` (in `format_kwargs = dict(... target_cols=None)`

**Expected behavior**
I expect the model to ignore the other columns, and specify my own target name.

**Error Stack Trace**
```
chemprop predict --test-path lots_of_data_test.csv --model-path train_example/model_0/best.pt --preds-path train_example/preds.csv --target-columns out
/home/jonzheng/miniconda3/envs/chemprop/lib/python3.12/site-packages/lightning/pytorch/utilities/parsing.py:199: Attribute 'graph_transform' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['graph_transform'])`.

Traceback (most recent call last):
  File "/home/jonzheng/miniconda3/envs/chemprop/bin/chemprop", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jonzheng/greengroup/chemprop/chemprop/cli/main.py", line 80, in main
    func(args)
  File "/home/jonzheng/greengroup/chemprop/chemprop/cli/predict.py", line 36, in func
    main(args)
  File "/home/jonzheng/greengroup/chemprop/chemprop/cli/predict.py", line 306, in main
    make_prediction_for_model(args, model_path, multicomponent, output_path)
  File "/home/jonzheng/greengroup/chemprop/chemprop/cli/predict.py", line 203, in make_prediction_for_model
    test_data = build_data_from_files(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonzheng/greengroup/chemprop/chemprop/cli/utils/parsing.py", line 270, in build_data_from_files
    smiss, rxnss, Y, weights, lt_mask, gt_mask = parse_csv(
                                                 ^^^^^^^^^^
  File "/home/jonzheng/greengroup/chemprop/chemprop/cli/utils/parsing.py", line 68, in parse_csv
    Y = Y.to_numpy(np.single)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonzheng/miniconda3/envs/chemprop/lib/python3.12/site-packages/pandas/core/frame.py", line 1993, in to_numpy
    result = self._mgr.as_array(dtype=dtype, copy=copy, na_value=na_value)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonzheng/miniconda3/envs/chemprop/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 1694, in as_array
    arr = self._interleave(dtype=dtype, na_value=na_value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonzheng/miniconda3/envs/chemprop/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 1753, in _interleave
    result[rl.indexer] = arr
    ~~~~~~^^^^^^^^^^^^
ValueError: could not convert string to float: 'acidic'
```

**Environment**
- pulled latest version from GH as of now (commit hash 5db62920445cab1ef060dba0c6dc5038da307f9e)
- python version: 3.12.3 

**Checklist**
- [x] all dependencies are satisifed: `conda list` or `pip list` shows the packages listed in the `pyproject.toml`
- [x] the unit tests are working: `pytest -v` reports no errors

**Additional context**
Happy to help provide a fix some time this or next week.

**Comment by shihchengli** [comment]
For a quick fix, the `target_cols` should be added to `format_kwargs` so you can use `--target-columns` to make predictions on your test data. I also noticed that the target seems to need to be provided in a file so that the `test_data` can be generated and used to make predictions. However, the targets of the test data are not necessary during pure inference, which should also be fixed.
