### ISSUE TITLE
 Problems with molecular structure recognition

### ISSUE THREAD

**Issue by 13811883561** [chemprop/chemprop#92]
Hi，I have read your paper about deep learning, and I am totally impressed by your amazing modle chemprop. I really hope that your model can be used in my current experiment， but I meet some problem in running the modle and I look forward to your reply. 
My system is macOS and  I have already installed rdkit from conda, but I still met two problems when running the modle.
1. When I train my modle (no matter the chemprop install from PyPi or from source),there is a warning:
<img width="894" alt="截屏2020-09-12 下午9 02 02" src="https://user-images.githubusercontent.com/61321436/93413665-59b3d600-f8d2-11ea-9b5f-7548e72fc13e.png">
I wounld like  to know why this problem occurs and I wander if this error will affect my traning results ?

2.When I interpret the model prediction there is also a problem
<img width="1280" alt="截屏2020-09-13 上午12 30 31" src="https://user-images.githubusercontent.com/61321436/93417086-c088bd80-f8d9-11ea-8cf6-ac065ee9d99c.png">
I wounld like  know why this problem occurs.

Sorry to bother you because of the problem of  running  the program, I will be glad if I can get your reply ！

Best wishes！

**Comment by swansonk14** [comment]
Hi @13811883561, thanks for bringing up the issues! Both of the problems you have identified are actually data/RDKit issues. In both cases, there are some SMILES strings in your dataset (or generated during interpretation) that RDKit is not totally happy with and can't process entirely correctly. However, the models should still work fine even with these warnings (we often get the same warnings ourselves), so you can safely ignore all of those warnings. I hope this helps!
