### ISSUE TITLE
The problem with mc_bin_client.py file

### ISSUE THREAD

**Issue by ismorphism** [chemprop/chemprop#93]
Hello, I faced the following errors:

`ModuleNotFoundError: No module named 'exceptions'`

`ModuleNotFoundError: No module named 'memcacheConstants'`

First one can be throwed away by getting rid of exceptions library (It is very Python 2, why do you use it?), but I can still face the second one and installation of memchached libraries (`python_memchached`) didn't help. Any suggestions? By the way I use Windows 10 Enterprise 1909.

**Comment by swansonk14** [comment]
Hi @ismorphism, thanks for sharing the issue! Neither of those packages are direct requirements of chemprop, but it's possible that some of the packages we use in turn rely on those libraries. Just to check, how did you go about installing chemprop? Did you use PyPI or did you install from GitHub? Also how did you create your conda environment, and which command did you try running? If you let me know those details, I can try to help debug.

**Comment by swansonk14** [comment]
Also I just noticed the title about `mc_bin_client.py`. Where did you find that file? Is it in a branch? I don't believe that file is in master.
