### ISSUE TITLE
split_data.py 

### ISSUE THREAD

**Issue by matany58** [chemprop/chemprop#94]
I received the error below when I execute
 python split_data.py --data_path ../data/tox21.csv  --split_type scaffold_balanced --save_dir ../tox21_split

Traceback (most recent call last):
  File "split_data.py", line 68, in <module>
    run_split_data(Args().parse_args())
  File "split_data.py", line 35, in run_split_data
    smiles = get_smiles(path=args.data_path, smiles_column=args.smiles_column)
TypeError: get_smiles() got an unexpected keyword argument 'smiles_column'

**Comment by aviboppana** [comment]
Seems like the field of the argument object is "smiles_columns" and not "smiles_column", so the split_data.py file is attempting to access an argument that doesn't exist.

**Comment by matany58** [comment]
In smiles_column=args.smiles_column which one should change

smiles_columns=args.smiles_column or smiles_column=args.smiles_columns
But I  install it direct from source. This script has worked with one system but when I changed to another system I got this error. I think it may be the system environment libraries/packages but I do not know which one

**Comment by swansonk14** [comment]
Hi @matany58, thanks for bringing up the issue! And thank you @aviboppana for discovering the underlying problem! I went ahead and fixed the problem in this commit: https://github.com/chemprop/chemprop/commit/2c98bf743cf90893dcc7b9f2b70786a2c7735b2f. Please let me know if you're still running into any issues.

**Comment by matany58** [comment]
Please have the github/chemprop being updated with these changes?

**Comment by swansonk14** [comment]
Yes the master branch has been updated with these changes, so if you pull master again you should get the fix.
