### ISSUE TITLE
[v2 QUESTION]: Why does chemprop convert produce a ckpt file?

### ISSUE THREAD

**Issue by KnathanM** [chemprop/chemprop#945]
I'm questioning if it is correct to produce a .ckpt file from a v1 .pt file in `convert_model_file_v1_to_v2` which is used in `chemprop convert`. A checkpoint file is supposed to have details about training so that lightning can restart the training, but these details are not available in the v1 .pt file, so we just set them to `None`. I think it would make more sense to produce a v2 .pt file instead. This would probably be a change for v2.1 because it changes the output of the CLI. 

Side note that the difference between a v1 .pt file and a v2 .pt file is that the keys in the state dict have different names and some hyperparameters also have different names.

**Comment by hwpang** [comment]
Yeah, when I wrote the convert module, we haven't designed the saving pipelines of `.pt` file in V2, so that wasn't an option back then. But we should certainly switch it over now that we have established the intentional use of `.ckpt` and `.pt` in V2.
