### ISSUE TITLE
[v2 FEATURE]: Automatic device handling for loading trained models

### ISSUE THREAD

**Issue by snaeppi** [chemprop/chemprop#949]
**Is your feature request related to a problem? Please describe.**

When attempting to use a model trained on GPU for prediction in a CPU-only environment, the program ends with a RuntimeError. This occurs because PyTorch attempts to load the model to the same device it was trained on.

Issue can be reproduced on a machine with a CUDA device:

Train normally with GPU:

```
chemprop train --accelerator gpu --task-type regression --data-path somedata.csv
```

Try to predict with CPU only:

```
CUDA_VISIBLE_DEVICES=-1 chemprop predict --accelerator cpu --devices 1 -n 1 --model-paths chemprop_training/somedata -i predict_something.csv -o results_something.csv
```

Current error message:
```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Use-cases/examples of this new feature**

Predicting on CPU-only environments with models trained on GPUs etc. accelerators. 

**Desired solution/workflow**

1. Train model with any PyTorch Lightning compatible accelerator.
2. Predict with CPU on any machine (including those with no accelerator devices).

The prediction step should automatically handle the device mismatch and load the model to CPU. 

**Discussion**

Currently, the user can create a separate Python script to load the model to CPU. While this works, it requires an additional step and may not be intuitive for all users, who might expect the `--accelerator` argument to handle such scenarios.

While a full implementation could theoretically enable models trained on any device (e.g., TPU) to be used for prediction on any other device (e.g., CUDA), it may be sufficient and more practical to focus on enabling CPU prediction for models trained on any device.

Alternatively, the model could be moved to CPU before saving.

**Comment by KnathanM** [comment]
Hi @snaeppi, thank you for opening this issue and a PR. I like your solution.

We also noticed this error and considered adding `map_location` as an argument to `load_model` so that the CLI could control the full logic of checking the accelerator and creating the appropriate `torch.device` to then pass as the map location. But now I feel that might be overkill for a simple convenience function `load_model`. Tagging @joelnkn who I talked about this with in case he has other thoughts to add.
