### ISSUE TITLE
transfer learning with Chemprop

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#951]
Hello,
I have a question about doing transfer learning with chemprop. I developed an ensemble of 20 models using chemprop to predict a specific property (named as source task).  I used pretrain feature of chemprop (initialization or keeping some layers frozen) to transfer the knowledge that we gained for the source task to related target tasks where we have smaller datasets.The question that I am facing is that I get a broad distribution of PRC_AUC for the target tasks depending on which model of the ensemble I am using. Moreover, the number of source model in the ensemble leading to maximum PRC_AUC is different for each task. I am not sure if these questions are directly related to chemprop, however, I would like to get your opinion.
I appreciate it if you have any suggestions in this regard.

Best Regards
Soo

**Comment by JacksonBurns** [comment]
Hi @SoodabehGhaffari it is impossible for us to speculate on this without knowing the original training and subsequent transfer learning tasks and having some scientific understanding of how they are related.

In general, it is not surprising that transfer learning can behave erratically, particularly on small datasets. This is not a bug in Chemprop, just an aspect of the practice of ML.

**Comment by SoodabehGhaffari** [comment]
I am not saying it is a bug in Chemprop, I just wanted to ask if there is
any rationale that different initialization of the source model leads to
huge difference in the performance of transferring learning and in turn the
target task. Have you come across this issue before or have you seen any
papers dealing with it?

I appreciate your help.

Best,
Soo

**Comment by JacksonBurns** [comment]
I haven't seen papers about it, I have experienced it in my own work, and it is not an unexpected result because transfer learning on small datasets is notoriously fickle.
