### ISSUE TITLE
[v2 BUG]: 

### ISSUE THREAD

**Issue by HHALee** [chemprop/chemprop#956]
I went to this documentation (https://chemprop.readthedocs.io/en/main/tutorial/python/data/dataloaders.html) to see how to load a dataset to chemprop. I put the following code into my Google Colab notebook but was met with an error.
<img width="1312" alt="Screenshot 2024-07-06 at 10 44 05 PM" src="https://github.com/chemprop/chemprop/assets/174221904/e71c9467-4ae8-4701-a6e3-416d0420228e">

I previously installed chemprop using the following code:
<img width="1349" alt="Screenshot 2024-07-06 at 10 44 44 PM" src="https://github.com/chemprop/chemprop/assets/174221904/c22c90e8-26be-43b9-ae4d-075d2559bfb2">

**Comment by JacksonBurns** [comment]
Chemprop isn't compatible with Google colab right now, see this tracking issue for when it will be compatible: https://github.com/chemprop/chemprop/issues/700
