### ISSUE TITLE
README points to URL incorrectly

### ISSUE THREAD

**Issue by ikmckenz** [chemprop/chemprop#96]
On the REAME, right underneath the Web Interface heading, there is a link that is supposed to go to http://chemprop.csail.mit.edu/. Right now however, the embedded URL points only to chemprop.csail.mit.edu, which GitHub interprets as some part of the code, so it redirects you to https://github.com/chemprop/chemprop/blob/master/chemprop.csail.mit.edu, which of course is not a real page. 

This will be a pretty easy one line fix, I'll make a PR now.

**Comment by swansonk14** [comment]
Thanks for catching the issue and making the PR! I just merged it in.
