### ISSUE TITLE
[TODO]: Problems with infinite training

### ISSUE THREAD

**Issue by k-ujihara** [chemprop/chemprop#968]
# Problems with infinite training

THe follwing line assumes `self.trainer.estimated_stepping_batches` is int, but when infinite training, ie `max_epochs=-1`, `self.trainer.estimated_stepping_batches` is `inf`. In this case, NoamLR initialization will fail.
https://github.com/chemprop/chemprop/blob/3213210c3519c7dc4e5ce452a57087f91b524115/chemprop/models/model.py#L221

See also. <https://github.com/Lightning-AI/pytorch-lightning/blob/f91349c961103af48091654775248789b6e03bd1/src/lightning/pytorch/trainer/trainer.py#L1670-L1671>.

**Comment by davidegraff** [comment]
This is because the `Noam` scheduler needs to know how many steps over which to cool down the scheduler. It's technically incompatible with infinite training by definition. We could potentially just assume a very large number and put a note their, but that seems like a slightly brittle solution.

**Comment by davidegraff** [comment]
Though, looking back at the actual definition of the Noam scheduler, it looks like it isn't necessary:

```math
\nu = \sqrt{n_\text{params}} \cdot \min(\sqrt{t}, t / t_\text{warmup}^{−1.5})
```

So this seems to be an implementation error with the v1 scheduler and something we should look at fixing.
