### ISSUE TITLE
[v2 QUESTION]: Classification model prediction output.

### ISSUE THREAD

**Issue by isabelg-arcia** [chemprop/chemprop#972]
My classification model is returning prediction results in float between 1 and 0.  Is this correct?
shouldn't I get the results in binary?

I'm running :

training:
`chemprop train --data-path ~/Desktop/648_BALANCED_data_smile_target.csv --task-type classification --output-dir ~/Desktop --split-type random --metrics prc`

predicting:
`chemprop predict --test-path ~/Desktop/for_pred.csv --model-path ~/Desktop/model_0/best.pt --preds-path ~/Desktop/model_0/preds_databse.csv`

best regard!

**Comment by shihchengli** [comment]
Hi @isabelg-arcia, that is normal. The output is directly from the sigmoid function. You can define a threshold to classify the output as either 1 or 0.
