### ISSUE TITLE
question about stereochemistry in the smiles

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#976]
Hello Chemprop group,
I am working with a dataset in which some of the smiles have the format as below:
"CCN1C=C(O[C@@H]2CN(C(=O)NC3CCC4=C(OC)C(OC)=CC=C43)C[C@H]2O)C=N1 |&1:6,26|"
I was wondering if Chemprop can handle this type of smiles or should I omit the last part in the smiles (|&1:6,26|). I appreciate any suggestions in this regard.

Best Regards
Soodabeh

**Comment by SoodabehGhaffari** [comment]
I would like to add more information to my question above: 
The notation |&1:6,26| is used to define a specific stereochemical relationship between atoms in a molecule. I tried it with a chemprop predict and it does not validate the SMILES. Is there any way to make the Chemprop validate the SMILE like above?

Thank you for the help
Best Regards
Soodabeh

**Comment by KnathanM** [comment]
We use RDKit to make graphs from the SMILES. Like you said that SMILES doesn't work for me:
```
from rkdit import Chem
mol = Chem.MolFromSmiles('CCN1C=C(O[C@@h]2CN(C(=O)NC3CCC4=C(OC)C(OC)=CC=C43)C[C@H]2O)C=N1 |&1:6,26|')
```
```
[13:39:21] SMILES Parse Error: syntax error while parsing: CCN1C=C(O[C@@h]2CN(C(=O)NC3CCC4=C(OC)C(OC)=CC=C43)C[C@H]2O)C=N1
[13:39:21] SMILES Parse Error: Failed parsing SMILES 'CCN1C=C(O[C@@h]2CN(C(=O)NC3CCC4=C(OC)C(OC)=CC=C43)C[C@H]2O)C=N1' for input: 'CCN1C=C(O[C@@h]2CN(C(=O)NC3CCC4=C(OC)C(OC)=CC=C43)C[C@H]2O)C=N1'
```
But this SMILES does work:
```
mol = Chem.MolFromSmiles('CCN1C=C(O[C@@H]2CN(C(=O)NC3CCC4=C(OC)C(OC)=CC=C43)C[C@H]2O)C=N1')
```
The molecule made looks like this. Is this what you want?
![image](https://github.com/user-attachments/assets/465fd93a-1c65-4c1f-b984-82e5edb5de6a)
