### ISSUE TITLE
find_simliar_mols.py fails due to dimension mismatch

### ISSUE THREAD

**Issue by sunhwan** [chemprop/chemprop#99]
The `sciprt/find_similar_mols.py` fails and produces the following error:

> Finding neighbors
> Traceback (most recent call last):
>   File "../chemprop/scripts/find_similar_mols.py", line 204, in <module>
>     batch_size=args.batch_size
>   File "../chemprop/scripts/find_similar_mols.py", line 181, in save_similar_mols
>     batch_size=batch_size
>   File "../chemprop/scripts/find_similar_mols.py", line 149, in find_similar_mols_from_file
>     batch_size=batch_size
>   File "../chemprop/scripts/find_similar_mols.py", line 99, in find_similar_mols
>     nearest_train_indices = np.argsort(distances[test_index])[:num_neighbors]
> IndexError: index 22 is out of bounds for axis 0 with size 22

I traced it to `compute_molecule_vectors` function and the `model.featurize` method produces `(1, <feature_size>)` vector instead `(<batch_size>, <feature_size>)` vector. Below is my fix for file `chemprop/nn_utils.py`.

```
135c135
<             batch_vecs = model.featurize(batch.mols(), batch.features())
---
>             batch_vecs = model.featurize(batch.batch_graph(), batch.features())
```

**Comment by swansonk14** [comment]
Hi @sunhwan, thank you for bringing up the issue and for suggesting the fix! I made that fix (as well as a couple others that were necessary) in this commit: https://github.com/chemprop/chemprop/commit/17b72cf094eac8c345ca5813a4863649424e5172. Please let me know if you run into any further issues!
