### ISSUE TITLE
[v2 QUESTION]: Is there any example about two components with extra descriptors

### ISSUE THREAD

**Issue by Swordshinehjy** [chemprop/chemprop#997]
**What are you trying to do?**
I have control and target molecules, each of them has extra calculated descriptors. I want to train a MulticomponentMPNN with extra descriptors.

**Comment by KnathanM** [comment]
There isn't a full example, but here are a couple resources to piece together.  
At the bottom of [this](https://github.com/KnathanM/chemprop/blob/rdkit_2d_features/docs/source/tutorial/python/featurizers/molecule_featurizers.ipynb)  notebook under "Using molecule features as extra datapoint descriptors" it says that you concatenate all your extra descriptors into one array. (I haven't merged this notebook into main yet so I'm not surprised you didn't see it.)
Then you need to add those concatentated extra molecule features as datapoint descriptors to the first dataset in your multicomponent dataset. See [here](https://chemprop.readthedocs.io/en/main/tutorial/python/data/datasets.html#Multicomponent-datasets) for multicomponent datasets and [here](https://chemprop.readthedocs.io/en/main/tutorial/python/data/datapoints.html#Extra-features-and-descriptors) for how to give extra data point descriptors to a dataset.

Here's also some quick code to get you started:
```
mol1_features = np.random.rand(n_datapoints, n_features1)
mol2_features = np.random.rand(n_datapoints, n_features2)
x_ds = np.hstack([mol1_features, mol2_features])
mol1s = [List of control molecules]
mol2s = [List of target molecules]
ys = np.random.rand(n_datapoints, n_tasks)
datapoints1 = [MoleculeDatapoint(mol, y, x_d=x_d) for mol, y, x_d in zip(mol1s, ys, x_ds)]
datapoints2 = [MoleculeDatapoint(mol) for mol in mol2s]
dataset1 = MoleculeDataset(datapoints1)
dataset2 = MoleculeDataset(datapoints2)
multi_dataset = MulticomponentDataset(datasets=[dataset1, dataset2])
dataloader = chemprop.data.build_dataloader(multi_dataset)
```

See if that works for you

**Comment by KnathanM** [comment]
Closing for now, feel free to reopen if you still run into errors with this.

**Comment by DengFeng-Zuo** [comment]
> [KnathanM](/KnathanM)

Hi KnathanM,

Thank you for your suggestion here.

But when I was building the **multi_dataset**  according to the code logic you provided, an error occurred. #1085 Could you please give me some advice on how to solve this?
