### ISSUE TITLE
[v2 QUESTION]: Load model for training

### ISSUE THREAD

**Issue by sunhwan** [chemprop/chemprop#999]
**What are you trying to do?**
I'm trying to load a pre-trained model and train with a new set of data. The v2 CLI offers transfer learning, but the MPNN is frozen. Is there a way to load model but without freezing the MPNN portion?

**Comment by JacksonBurns** [comment]
For others, [this is the docs page](https://chemprop.readthedocs.io/en/latest/tutorial/cli/train.html#pretraining-and-transfer-learning) specifying arguments for transfer learning.

To answer the question - no, you cannot run transfer learning with trainable MPNN parameters. This is not something we plan to implement, but we would review a PR if you are interested in contributing.

**Comment by KnathanM** [comment]
@shihchengli will look into making this easier from the CLI
